abort_psblas – Morfeus Framework
abort_psblas Module Procedure
3 statements
Source File
module procedure abort_psblas module subroutine abort_psblas() Interface →
Arguments
None
Calls
Called by
Contents
None
Call graph
abort_psblas calls psb_abort, abort_psblas
alloc_table calls abort_psblas, alloc_table
get_surface_r2 calls abort_psblas, get_surface_r2
scalar_field_dif calls abort_psblas, scalar_field_dif
get_abc_wall_s calls abort_psblas, get_abc_wall_s
create_pde calls abort_psblas, open_file, create_pde
dim_sqrt calls abort_psblas, dim_sqrt
get_conn_csr calls abort_psblas, get_conn_csr
apply_abc_to_boundary_s calls abort_psblas
scalar_field_div calls abort_psblas, scalar_field_div
wr_vtk_mesh calls abort_psblas
get_dual_conn calls abort_psblas, alloc_conn, get_dual_conn
bcast_cell calls abort_psblas, alloc_cell, bcast_cell
alloc_face calls abort_psblas, alloc_face
free_vector calls abort_psblas, free_vector
apply_renum_conn calls abort_psblas, free_conn
solve_vector_pde calls abort_psblas, solve_vector_pde
set_kt_row calls abort_psblas, set_kt_row
bcast_vertex calls abort_psblas, free_vertex, alloc_vertex, bcast_vector, bcast_vertex
max_conn calls abort_psblas, max_conn
l2g_face calls abort_psblas, alloc_face, l2g_face
vector_pde_ddt calls abort_psblas, pde_sign, vector_pde_ddt
get_scalar_field_xp calls abort_psblas, get_scalar_field_xp
set_bc_poly_map_s calls abort_psblas, set_bc_poly_map_s
check_material_consistency calls abort_psblas, check_material_consistency
vector_pde_grad calls abort_psblas, pde_sign, check_mesh_consistency, fld_grad, vector_pde_grad
find_section calls abort_psblas, find_section
laplacian_smooth calls abort_psblas, laplacian_smooth
get_surface_normal calls abort_psblas, get_surface_normal
vector_field_flux calls abort_psblas, free_vector, vector_field_flux
alloc_vertex calls abort_psblas, alloc_vertex
alloc_cell calls abort_psblas, alloc_cell
free_bc_math calls abort_psblas, dealloc_bc_math, free_bc_math
matlaw_v calls abort_psblas
get_row_size calls abort_psblas, get_row_size
create_bc_math calls abort_psblas, rd_inp_bc_math, create_bc_math
alloc_conn calls abort_psblas, alloc_conn
get_kt_row calls abort_psblas, get_kt_row
get_part_graph calls abort_psblas, get_part_graph
wr_mtx_vector calls abort_psblas, wr_mtx_vector
free_cell calls abort_psblas, free_cell
pwl_interp_x_vec calls abort_psblas, pwl_nearest, pwl_interp_x_vec
get_par_i calls abort_psblas
bld_part_graph calls abort_psblas, bld_part_graph
create_bc_wall calls abort_psblas, rd_inp_bc_wall, create_bc_wall
read_par_discretization calls abort_psblas, find_section, open_file
set_vector_field_bound_element calls abort_psblas, set_vector_field_bound_element
create_iterating calls abort_psblas, open_file, create_iterating
free_table calls abort_psblas, free_table
get_par_v calls abort_psblas
free_least_squares calls abort_psblas, free_least_squares
alloc_plane calls abort_psblas, alloc_plane
update_vector_field calls abort_psblas, update_vector_halo, update_vector_field
check_mesh_consistency calls abort_psblas, check_mesh_consistency
get_abc_math_v calls abort_psblas
vector_pde_laplacian calls abort_psblas, pde_sign, check_mesh_consistency, fld_grad, vector_pde_laplacian
rd_inp_bc_wall calls abort_psblas, open_file
set_bc_wall_map_s calls abort_psblas, set_bc_wall_map_s
solve_scalar_pde calls abort_psblas, solve_scalar_pde
set_bc_wall_map_v calls abort_psblas, set_bc_wall_map_v
l2g_conn calls abort_psblas, free_conn, alloc_conn, l2g_conn
bcast_vector calls abort_psblas, alloc_vector, free_vector, bcast_vector
wr_mtx_matrix calls abort_psblas, wr_mtx_matrix
check_field_operands calls abort_psblas, check_mesh_consistency, check_material_consistency, check_field_operands
bcast_conn calls abort_psblas, alloc_conn, bcast_conn
bcast_face calls abort_psblas, alloc_face, bcast_face
set_scalar_field_group calls abort_psblas, set_scalar_field_group
cmp_moving_surf calls abort_psblas, cmp_moving_surf
nconn_ calls abort_psblas, nconn_
write_exo_morfeus calls abort_psblas, l2g_face, l2g_vector, l2g_cell, l2g_conn, l2g_vertex, write_exo_morfeus
scalar_field_mul calls abort_psblas, scalar_field_mul
get_scalar_field_x calls abort_psblas, get_scalar_field_x
pwl_nearest calls abort_psblas, pwl_nearest
pwl_deriv_x_v calls abort_psblas, pwl_nearest, pwl_deriv_x_v
interp_on_faces_s calls abort_psblas, interp_on_faces_s
check_temp_s calls abort_psblas
update_boundary_s calls abort_psblas
cmp_mesh_renum calls abort_psblas, start_renum, cmp_mesh_renum
get_vector_field_x_r calls abort_psblas, get_vector_field_x_r
assign_vector_field_v calls abort_psblas, assign_vector_field_v
free_conn calls abort_psblas, free_conn
scalar_field_scal calls abort_psblas, scalar_field_scal
check_mesh_quality calls abort_psblas, get_cells_type, check_tet_quality, check_mesh_quality
cmp_mesh_f2f calls abort_psblas, alloc_conn, cmp_mesh_f2f
geom_diff calls abort_psblas, geom_diff
write_vector_field calls abort_psblas, l2g_vector, l2g_cell, write_vector_field
g2l_vertex calls abort_psblas, free_vertex, alloc_vertex, g2l_vertex
l2g_cell calls abort_psblas, alloc_cell, l2g_cell
check_tet_quality calls abort_psblas, itoh, check_tet_quality
itoh calls abort_psblas, itoh
supplement_v2f calls abort_psblas, bcast_conn, free_conn, supplement_v2f
pwl_interp_x_v calls abort_psblas, pwl_nearest, pwl_interp_x_v
scalar_field_sum calls abort_psblas, scalar_field_sum
assign_scalar_field_v calls abort_psblas, assign_scalar_field_v
cmp_mesh_c2c calls abort_psblas, alloc_conn, cmp_mesh_c2c
get_dual_table calls abort_psblas, get_dual_table
free_vertex calls abort_psblas, free_vertex
check_mesh_unused_el calls abort_psblas, check_mesh_unused_el
alloc_bc_math calls abort_psblas, alloc_bc_math
vector_pde_source calls abort_psblas, pde_sign
load_water calls abort_psblas, load_water
vector_field_dif calls abort_psblas, vector_field_dif
build_pinv calls abort_psblas, build_pinv
smooth_surf_vtx calls abort_psblas, smooth_surf_vtx
cmp_gps calls abort_psblas, cmp_gps
htoi calls abort_psblas, htoi
cmp_mesh_f2b calls abort_psblas, alloc_conn, cmp_mesh_f2b
update_vector_halo calls abort_psblas, update_vector_halo
vector_field_grad calls abort_psblas, vector_field_grad
create_vector_field calls abort_psblas, alloc_vector, create_vector_field
pwl_interp_dx_v calls abort_psblas, pwl_interp_dx_v
alloc_keytable calls abort_psblas, alloc_keytable
check_vertex_quality calls abort_psblas, check_vertex_quality
update_boundary_wall_s calls abort_psblas
build_pde_prec calls abort_psblas, build_pde_prec
apply_abc_to_boundary_v calls abort_psblas
alloc_vector calls abort_psblas, alloc_vector
free_field calls abort_psblas, free_field, free_vector
write_mesh calls abort_psblas, l2g_face, l2g_cell, l2g_conn, free_conn, l2g_vertex, write_mesh
unused_elements calls abort_psblas, unused_elements
vector_field_ calls abort_psblas
get_cells_type calls abort_psblas, get_cells_type
start_renum calls abort_psblas, build_pinv, cmp_gps, start_renum
move_boundary calls abort_psblas, move_boundary
rd_inp_bc_math calls abort_psblas, find_section, open_file, rd_inp_bc_math
get_scalar_field_bx calls abort_psblas, get_scalar_field_bx
get_vector_field_bx_r calls abort_psblas, get_vector_field_bx_r
set_bc_poly_map_v calls abort_psblas, set_bc_poly_map_v
check_right_handed calls abort_psblas, check_right_handed
rd_inp_bc calls abort_psblas, open_file, rd_inp_bc
pde_sign calls abort_psblas, pde_sign
smooth_interior_vtx calls abort_psblas, smooth_interior_vtx
create_mesh calls abort_psblas, import_mesh, cmp_mesh_f2f, cmp_mesh_v2ve, cmp_mesh_renum, geom_cell, cmp_mesh_v2b, cmp_mesh_part, geom_diff, supplement_v2c, bcast_face, supplement_v2f, cmp_mesh_desc, geom_face, cmp_moving_surf, cmp_mesh_f2b, cmp_mesh_c2c, g2l_mesh, set_least_squares, rd_inp_mesh, create_mesh
free_bc_wall calls abort_psblas, free_bc_wall
set_vector_field_group calls abort_psblas, set_vector_field_group
copy_keytable calls abort_psblas
cmp_mesh_v2e calls abort_psblas, free_conn, alloc_conn, cmp_mesh_v2e
load_copper calls abort_psblas, load_copper
get_par_h calls abort_psblas
vector_pde_d2dt2 calls abort_psblas, pde_sign, vector_pde_d2dt2
rhie_chow calls abort_psblas, rhie_chow
create_motion calls abort_psblas, rd_inp_motion_law, create_motion
update_boundary_wall_v calls abort_psblas
free_material calls abort_psblas, free_material
get_closest_point calls abort_psblas, get_closest_point
bld_part_random calls abort_psblas, bld_part_random
rd_gmsh_mesh calls abort_psblas, alloc_face, alloc_vertex, alloc_cell, rd_gmsh_mesh
supplement_v2c calls abort_psblas, free_conn, supplement_v2c
cmp_mesh_v2v calls abort_psblas, alloc_conn, cmp_mesh_v2v
geins_vector_pde_r calls abort_psblas, geins_vector_pde_r
cmp_mesh_part calls abort_psblas, get_part_graph, bld_part_graph, bld_part_block, bld_part_random, cmp_mesh_part
scalar_pde_source calls abort_psblas, pde_sign, scalar_pde_source
get_abc_wall_v calls abort_psblas, get_abc_wall_v
alloc_cylinder calls abort_psblas, alloc_cylinder
alloc_surface calls abort_psblas, alloc_plane, alloc_surface
check_temp_v calls abort_psblas
scalar_field_dif_s calls abort_psblas, scalar_field_dif_s
get_vector_field calls abort_psblas, l2g_vector, l2g_cell, get_vector_field
rd_gambit_mesh calls abort_psblas, alloc_face, alloc_vertex, alloc_cell, rd_gambit_mesh
geom_face calls abort_psblas, alloc_vector, geom_face
set_scalar_field_element calls abort_psblas, set_scalar_field_element
fcn calls abort_psblas
get_par_d calls abort_psblas
start_psblas calls abort_psblas, start_psblas
get_scalar_field calls abort_psblas, l2g_cell, get_scalar_field
bld_part_block calls abort_psblas, bld_part_block
scalar_field_ calls abort_psblas
set_vector_field_element calls abort_psblas, set_vector_field_element
scalar_pde_laplacian calls abort_psblas, pde_sign, check_mesh_consistency, free_vector, fld_grad, scalar_pde_laplacian
create_output calls abort_psblas, open_file, create_output
cmp_mesh_v2ve calls abort_psblas, free_conn, cmp_mesh_v2e, alloc_conn, cmp_mesh_v2ve
vector_field_scal calls abort_psblas, vector_field_scal
l2g_vector calls abort_psblas, alloc_vector, l2g_vector
write_vtk_mesh calls abort_psblas, wr_vtk_mesh, free_conn
interp_on_faces_v calls abort_psblas, alloc_vector, interp_on_faces_v
create_scalar_field calls abort_psblas, create_scalar_field
rd_inp_motion_law calls abort_psblas, alloc_vector, open_file, bcast_vector, rd_inp_motion_law
pwl_interp_x_s calls abort_psblas, pwl_nearest, pwl_interp_x_s
dealloc_bc_math calls abort_psblas, dealloc_bc_math
cmp_mesh_v2b calls abort_psblas, free_conn, alloc_conn, cmp_mesh_v2b
scalar_pde_ddt calls abort_psblas, pde_sign, check_mesh_consistency, scalar_pde_ddt
rd_exodus_mesh calls abort_psblas, alloc_face, alloc_vertex, alloc_cell, rd_exodus_mesh
vector_field_sum calls abort_psblas, vector_field_sum
open_file calls abort_psblas, open_file
get_vector_field_xp_r calls abort_psblas, get_vector_field_xp_r
pwl_deriv_x_s calls abort_psblas, pwl_nearest, pwl_deriv_x_s
update_scalar_field calls abort_psblas, update_scalar_field
pwl_deriv_x_vec calls abort_psblas, pwl_nearest, pwl_deriv_x_vec
free_bc calls abort_psblas, free_bc
scalar_field_grad calls abort_psblas, update_vector_halo, scalar_field_grad
cmp_mesh_desc calls abort_psblas, bcast_conn, free_conn, cmp_mesh_desc
create_bc calls abort_psblas, create_bc
alloc_least_squares calls abort_psblas, alloc_least_squares
geom_cell calls abort_psblas, alloc_vector, geom_cell
psb_build_prec calls abort_psblas
rd_cgns_mesh calls abort_psblas, alloc_face, alloc_vertex, alloc_cell, rd_cgns_mesh
get_abc_math_s calls abort_psblas
g2l_conn_1d calls abort_psblas
nel_ calls abort_psblas, nel_
vector_pde_div calls abort_psblas, pde_sign, check_mesh_consistency, vector_pde_div
update_boundary_v calls abort_psblas
import_mesh calls abort_psblas, rd_gambit_mesh, rd_gmsh_mesh
smooth_mesh calls abort_psblas, free_least_squares, check_right_handed, geom_cell, laplacian_smooth, geom_diff, free_conn, geom_face, mobile_verts, set_least_squares, update_vertex_halo, smooth_mesh
free_face calls abort_psblas, free_face
set_bc_math_map calls abort_psblas, set_bc_math_map
write_vtk_morfeus calls write_vtk_mesh, write_vtk_morfeus
copy_conn calls alloc_conn
pde_grad calls vector_pde_grad
g2l_conn_core calls free_conn, alloc_conn, g2l_conn_core
apply_renum_cell calls free_cell, alloc_cell
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
vector_pde_d2dt2_fld_phi calls vector_pde_d2dt2, vector_pde_d2dt2_fld_phi
read_par_i calls find_section, open_file
g2l_vector calls alloc_vector, free_vector, g2l_vector
read_par_v calls find_section, open_file
g2l_mesh calls bcast_vertex, g2l_vertex, bcast_cell, bcast_conn, g2l_face, g2l_cell
write_pde calls wr_mtx_matrix, write_pde
write_field calls write_vector_field
scalar_pde_div calls pde_sign, check_mesh_consistency, scalar_pde_div
create_scalar_source calls open_file, create_scalar_source
free_mesh calls free_least_squares, free_cell, free_face, free_conn, free_vertex, free_vector, free_mesh
geins_vector_pde_v calls geins_vector_pde_r, geins_vector_pde_v
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
set_output_path_iter calls itoh, set_output_path_iter
vector_pde_ddt_fld_phi calls vector_pde_ddt, vector_pde_ddt_fld_phi
mobile_verts calls free_conn, mobile_verts
get_motion_displacement calls pwl_nearest, pwl_interp, get_motion_displacement
rd_inp_mesh calls open_file, rd_inp_mesh
write_scalar_pde calls wr_mtx_vector, write_scalar_pde
write_vector_pde calls wr_mtx_vector, write_vector_pde
fld_grad calls vector_field_grad, scalar_field_grad
vector_pde_d2dt2_phi calls vector_pde_d2dt2, vector_pde_d2dt2_phi
check_mesh_consistency_bf calls check_mesh_consistency, check_mesh_consistency_bf
move_boundaries calls move_boundary, move_boundaries
l2g_vertex calls l2g_vector, alloc_vector, free_vector, alloc_vertex, l2g_vertex
pde_source calls scalar_pde_source
scalar_pde_ddt_phi calls scalar_pde_ddt, scalar_pde_ddt_phi
fld_flux calls vector_field_flux
read_par_l calls find_section, open_file
rd_inp_material calls open_file, rd_inp_material
load_material calls load_water, load_copper, load_material
read_par_h calls find_section, open_file
vector_pde_ddt_phi calls vector_pde_ddt, vector_pde_ddt_phi
read_par_d calls open_file
scalar_pde_ddt_fld_phi calls scalar_pde_ddt, scalar_pde_ddt_fld_phi
pde_div calls vector_pde_div, flux_pde_div, scalar_pde_div
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
pwl_deriv calls pwl_deriv_x_s, pwl_deriv_x_vec, pwl_deriv_x_v
pwl_interp calls pwl_interp_x_v, pwl_interp_x_vec, pwl_interp_dx_v, pwl_interp_x_s
set_least_squares calls alloc_least_squares, set_least_squares
scalar_pde_d2dt2 calls pde_sign, check_mesh_consistency, scalar_pde_d2dt2
g2l_cell calls alloc_cell, g2l_cell
g2l_face calls alloc_face, g2l_face
flux_pde_div calls pde_sign, check_mesh_consistency, flux_pde_div
update_vertex_halo calls update_vector_halo, update_vertex_halo
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
get_motion_velocity calls pwl_deriv, pwl_interp, get_motion_velocity
scalar_pde_d2dt2_fld_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_fld_phi
create_material calls load_material, rd_inp_material, create_material
pde_laplacian calls vector_pde_laplacian_phi, scalar_pde_laplacian_gamma_phi, scalar_pde_laplacian_phi, vector_pde_laplacian_gamma_phi
pde_ddt calls vector_pde_ddt_phi, vector_pde_ddt_fld_phi, scalar_pde_ddt_phi, scalar_pde_ddt_fld_phi
scalar_pde_d2dt2_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_phi
pde_d2dt2 calls vector_pde_d2dt2_fld_phi, vector_pde_d2dt2_phi, scalar_pde_d2dt2_phi, scalar_pde_d2dt2_fld_phi