alloc_bc_math – Morfeus Framework
alloc_bc_math Module Procedure
44 statements
Source File
module procedure alloc_bc_math module subroutine alloc_bc_math(bc, id, nbf, a, b, c) Interface →
Uses
tools_bc
Arguments
Type Intent Optional Attributes Name
class(bc_math), intent(inout) :: bc
integer, intent(in) :: id
integer, intent(in) :: nbf
real(kind=psb_dpk_), intent(in) :: a(:)
real(kind=psb_dpk_), intent(in) :: b(:)
real(kind=psb_dpk_), intent(in) :: c(:)
Calls
Called by
Contents
None
Call graph
alloc_bc_math calls abort_psblas, alloc_bc_math
abort_psblas calls abort_psblas, psb_abort