alloc_plane – Morfeus Framework
alloc_plane Module Procedure
109 statements
Source File
module procedure alloc_plane module subroutine alloc_plane(vertices, this_plane) Interface →
Uses
class_psblas
class_vector
tools_math
Arguments
Type Intent Optional Attributes Name
type(vertex), intent(in) :: vertices(:)
type(plane), pointer :: this_plane
Calls
Called by
Contents
None
Call graph
alloc_plane calls solve_sys, factorize, vector_, abort_psblas, alloc_plane
solve_sys calls cholesky_solve_m, psb_solve_sys, lu_solve, cholesky_solve_v
factorize calls choloesky_fact_v, lu_fact, cholesky_fact_m
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
choloesky_fact_v calls choloesky_fact_v
cholesky_solve_m calls cholesky_solve_m
psb_solve_sys calls psb_solve_sys, psb_erractionsave, psb_check_error, psb_erractionrestore, psb_krylov, icontxt_, mypnum_
lu_solve calls lu_solve
lu_fact calls lu_fact, lu_fact_3, lu_fact_2, lu_fact_4
cholesky_fact_m calls cholesky_fact_m
cholesky_solve_v calls cholesky_solve_v
icontxt_ calls icontxt_
mypnum_ calls mypnum_
alloc_surface calls alloc_plane, alloc_surface