alloc_keytable – Morfeus Framework
alloc_keytable Module Procedure
15 statements
Source File
module procedure alloc_keytable module subroutine alloc_keytable(table, lb, ub) Interface →
Uses
class_psblas
Arguments
Type Intent Optional Attributes Name
class(keytable), intent(inout) :: table
integer, intent(in) :: lb
integer, intent(in) :: ub
Calls
Called by
Contents
None
Call graph
alloc_keytable calls abort_psblas, alloc_keytable
abort_psblas calls abort_psblas, psb_abort