alloc_vector – Morfeus Framework
alloc_vector Module Procedure
19 statements
Source File
module procedure alloc_vector module subroutine alloc_vector(vect, n) Interface →
Workaround for Intel 18 error #6053: Structure constructor may not have fields with a PRIVATE attribute
Arguments
Type Intent Optional Attributes Name
type(vector), allocatable :: vect(:)
integer, intent(in) :: n
Calls
Called by
Contents
None
Call graph
alloc_vector calls abort_psblas, alloc_vector
abort_psblas calls abort_psblas, psb_abort
geom_cell calls alloc_vector, geom_cell
l2g_vector calls alloc_vector, l2g_vector
create_vector_field calls alloc_vector, create_vector_field
bcast_vector calls alloc_vector, bcast_vector
g2l_vector calls alloc_vector, g2l_vector
l2g_vertex calls alloc_vector, l2g_vector, l2g_vertex
rd_inp_motion_law calls alloc_vector, bcast_vector, rd_inp_motion_law
geom_face calls alloc_vector, geom_face
interp_on_faces_v calls alloc_vector, interp_on_faces_v
create_mesh calls geom_face, geom_cell, g2l_mesh, create_mesh
create_motion calls rd_inp_motion_law, create_motion
write_exo_morfeus calls l2g_vector, l2g_vertex, write_exo_morfeus
write_vector_field calls l2g_vector, write_vector_field
write_mesh calls l2g_vertex, write_mesh
bcast_vertex calls bcast_vector, bcast_vertex
get_vector_field calls l2g_vector, get_vector_field
smooth_mesh calls geom_face, geom_cell, smooth_mesh
write_field calls write_vector_field
g2l_mesh calls bcast_vertex