alloc_least_squares – Morfeus Framework
alloc_least_squares Module Procedure
29 statements
Source File
module procedure alloc_least_squares module subroutine alloc_least_squares(lsr, n, ncd) Interface →
Arguments
Type Intent Optional Attributes Name
type(least_squares), intent(out), allocatable :: lsr(:)
integer, intent(in) :: n
integer, intent(in) :: ncd
Calls
Called by
Contents
None
Call graph
alloc_least_squares calls abort_psblas, alloc_least_squares
abort_psblas calls abort_psblas, psb_abort
set_least_squares calls alloc_least_squares, set_least_squares
create_mesh calls set_least_squares, create_mesh
smooth_mesh calls set_least_squares, smooth_mesh