alloc_cell – Morfeus Framework
alloc_cell Module Procedure
14 statements
Source File
module procedure alloc_cell module subroutine alloc_cell(cells, n) Interface →
Array constructor
Arguments
Type Intent Optional Attributes Name
type(cell), allocatable :: cells(:)
integer, intent(in) :: n
Calls
Called by
Contents
None
Call graph
alloc_cell calls abort_psblas, alloc_cell
abort_psblas calls abort_psblas, psb_abort
rd_exodus_mesh calls alloc_cell, rd_exodus_mesh
l2g_cell calls alloc_cell, l2g_cell
apply_renum_cell calls alloc_cell
rd_gmsh_mesh calls alloc_cell, rd_gmsh_mesh
rd_gambit_mesh calls alloc_cell, rd_gambit_mesh
rd_cgns_mesh calls alloc_cell, rd_cgns_mesh
g2l_cell calls alloc_cell, g2l_cell
bcast_cell calls alloc_cell, bcast_cell
write_mesh calls l2g_cell, write_mesh
write_exo_morfeus calls l2g_cell, write_exo_morfeus
get_vector_field calls l2g_cell, get_vector_field
g2l_mesh calls g2l_cell, bcast_cell
get_scalar_field calls l2g_cell, get_scalar_field
import_mesh calls rd_gmsh_mesh, rd_gambit_mesh
write_vector_field calls l2g_cell, write_vector_field
create_mesh calls g2l_mesh, import_mesh, create_mesh
write_field calls write_vector_field