alloc_table – Morfeus Framework
alloc_table Module Procedure
34 statements
Source File
module procedure alloc_table module subroutine alloc_table(a2b, nel, ntab) Interface →
Arguments
Type Intent Optional Attributes Name
class(table), intent(inout) :: a2b
integer, intent(in), optional :: nel
integer, intent(in), optional :: ntab
Calls
Called by
Contents
None
Call graph
alloc_table calls abort_psblas, alloc_table
abort_psblas calls abort_psblas, psb_abort