alloc_vertex – Morfeus Framework
alloc_vertex Module Procedure
18 statements
Source File
module procedure alloc_vertex module subroutine alloc_vertex(verts, n) Interface →
Arguments
Type Intent Optional Attributes Name
type(vertex), allocatable :: verts(:)
integer, intent(in) :: n
Calls
Called by
Contents
None
Call graph
alloc_vertex calls abort_psblas, vector_, alloc_vertex
abort_psblas calls abort_psblas, psb_abort
vector_ calls vector_
g2l_vertex calls alloc_vertex, g2l_vertex
rd_gmsh_mesh calls alloc_vertex, rd_gmsh_mesh
l2g_vertex calls alloc_vertex, l2g_vertex
rd_exodus_mesh calls alloc_vertex, rd_exodus_mesh
rd_cgns_mesh calls alloc_vertex, rd_cgns_mesh
rd_gambit_mesh calls alloc_vertex, rd_gambit_mesh
bcast_vertex calls alloc_vertex, bcast_vertex
import_mesh calls rd_gambit_mesh, rd_gmsh_mesh
write_exo_morfeus calls l2g_vertex, write_exo_morfeus
write_mesh calls l2g_vertex, write_mesh
g2l_mesh calls g2l_vertex, bcast_vertex
create_mesh calls import_mesh, g2l_mesh, create_mesh