alloc_surface – Morfeus Framework
alloc_surface Module Procedure
44 statements
Source File
module procedure alloc_surface module subroutine alloc_surface(v2b, ib, vertices, this_surface) Interface →
Uses
class_psblas
class_connectivity
class_cylinder
class_plane
class_vertex
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(in) :: v2b
integer, intent(in) :: ib
type(vertex), intent(in) :: vertices(:)
type(surface), intent(inout) :: this_surface
Calls
Called by
Contents
None
Call graph
alloc_surface calls mypnum_, abort_psblas, alloc_plane, free_plane, alloc_surface
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
alloc_plane calls alloc_plane, abort_psblas, factorize, vector_, solve_sys
free_plane calls free_plane
factorize calls cholesky_fact_m, choloesky_fact_v, lu_fact
vector_ calls vector_
solve_sys calls psb_solve_sys, lu_solve, cholesky_solve_v, cholesky_solve_m
psb_solve_sys calls psb_solve_sys, mypnum_, psb_krylov, psb_erractionsave, icontxt_, psb_check_error, psb_erractionrestore
cholesky_fact_m calls cholesky_fact_m
lu_solve calls lu_solve
choloesky_fact_v calls choloesky_fact_v
cholesky_solve_v calls cholesky_solve_v
lu_fact calls lu_fact, lu_fact_2, lu_fact_3, lu_fact_4
cholesky_solve_m calls cholesky_solve_m
icontxt_ calls icontxt_