alloc_face – Morfeus Framework
alloc_face Module Procedure
15 statements
Source File
module procedure alloc_face module subroutine alloc_face(faces, n) Interface →
Array constructor
Arguments
Type Intent Optional Attributes Name
type(face), allocatable :: faces(:)
integer, intent(in) :: n
Calls
Called by
Contents
None
Call graph
alloc_face calls abort_psblas, alloc_face
abort_psblas calls abort_psblas, psb_abort
rd_gmsh_mesh calls alloc_face, rd_gmsh_mesh
bcast_face calls alloc_face, bcast_face
l2g_face calls alloc_face, l2g_face
rd_exodus_mesh calls alloc_face, rd_exodus_mesh
rd_cgns_mesh calls alloc_face, rd_cgns_mesh
rd_gambit_mesh calls alloc_face, rd_gambit_mesh
g2l_face calls alloc_face, g2l_face
create_mesh calls bcast_face, g2l_mesh, import_mesh, create_mesh
write_exo_morfeus calls l2g_face, write_exo_morfeus
g2l_mesh calls g2l_face
import_mesh calls rd_gambit_mesh, rd_gmsh_mesh
write_mesh calls l2g_face, write_mesh