apply_renum_cell – Morfeus Framework
apply_renum_cell Procedure
14 statements
Source File
module procedure apply_renum_cell module procedure apply_renum_cell()
Uses
class_cell
Arguments
None
Calls
Contents
None
Call graph
apply_renum_cell calls free_cell, pinv, alloc_cell, c
free_cell calls free_cell, abort_psblas
alloc_cell calls alloc_cell, abort_psblas
abort_psblas calls abort_psblas, psb_abort