apply_abc_to_boundary_s – Morfeus Framework
apply_abc_to_boundary_s Procedure
73 statements
Source File
module procedure apply_abc_to_boundary_s module procedure apply_abc_to_boundary_s()
Uses
class_connectivity
class_mesh
tools_bc
WARNING! - Use intent(inout) for BX(:) - Do loop on the faces subset corresponding to IB bc. - Only this section of BX(:) is going to be modified. - BX(:) indexing starts from 1: when BX(:) is referenced an offset equal to the # of boundary faces with flag > 0 and < IB must be added to the I counter.
Arguments
None
Calls
Contents
None
Call graph
apply_abc_to_boundary_s calls abort_psblas, bx, a, c, b, x
abort_psblas calls abort_psblas, psb_abort