apply_renum_conn – Morfeus Framework
apply_renum_conn Procedure
45 statements
Source File
module procedure apply_renum_conn module procedure apply_renum_conn()
Uses
class_connectivity
Arguments
None
Calls
Contents
None
Call graph
apply_renum_conn calls abort_psblas, perm, pinv, free_conn
abort_psblas calls abort_psblas, psb_abort
free_conn calls free_conn, abort_psblas