apply_abc_to_boundary_v – Morfeus Framework
apply_abc_to_boundary_v Procedure
41 statements
Source File
module procedure apply_abc_to_boundary_v module procedure apply_abc_to_boundary_v()
Uses
class_connectivity
class_mesh
class_vector
tools_bc
WARNING! - Use intent(inout) for BX(:) - Do loop on the faces subset corresponding to IB bc. - Only this section of BX(:) is going to be modified. - BX(:) idexing starts from 1: when BX(:) is referenced an offset equal to the # of boundary faces with flag > 0 and < IB must be added to the I counter.
$ write(0,) 'apply_abc_to_boundary_v: Debug: dirichlet',n $ write(0,) 'apply_abc_to_boundary_v: Debug: dirichlet_map',n
Arguments
None
Calls
Contents
None
Call graph
apply_abc_to_boundary_v calls x, c, bx, abort_psblas
abort_psblas calls abort_psblas, psb_abort