bcast_dim – Morfeus Framework
bcast_dim Module Procedure
22 statements
Source File
module procedure bcast_dim module subroutine bcast_dim(dim) Interface →
Arguments
Type Intent Optional Attributes Name
class(dimensions), intent(inout) :: dim
Calls
Called by
Contents
None
Call graph
bcast_dim calls icontxt_, mypnum_, psblas_is_on, psb_bcast, bcast_dim
icontxt_ calls icontxt_
mypnum_ calls mypnum_
psblas_is_on calls psblas_is_on