bcast_face – Morfeus Framework
bcast_face Module Procedure
49 statements
Source File
module procedure bcast_face module subroutine bcast_face(faces) Interface →
Arguments
Type Intent Optional Attributes Name
type(face), allocatable :: faces(:)
Calls
Called by
Contents
None
Call graph
bcast_face calls icontxt_, psb_bcast, alloc_face, mypnum_, abort_psblas, bcast_face
icontxt_ calls icontxt_
alloc_face calls alloc_face, abort_psblas
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
create_mesh calls bcast_face, create_mesh