bcast_vector – Morfeus Framework
bcast_vector Module Procedure
46 statements
Source File
module procedure bcast_vector module subroutine bcast_vector(vect) Interface →
Arguments
Type Intent Optional Attributes Name
type(vector), allocatable :: vect(:)
Calls
Called by
Contents
None
Call graph
bcast_vector calls free_vector, alloc_vector, abort_psblas, icontxt_, psb_bcast, mypnum_, bcast_vector
free_vector calls free_vector, abort_psblas
alloc_vector calls alloc_vector, abort_psblas
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
mypnum_ calls mypnum_
bcast_vertex calls bcast_vector, bcast_vertex
rd_inp_motion_law calls bcast_vector, rd_inp_motion_law
create_motion calls rd_inp_motion_law, create_motion
g2l_mesh calls bcast_vertex
create_mesh calls g2l_mesh, create_mesh