bcast_vertex – Morfeus Framework
bcast_vertex Module Procedure
47 statements
Source File
module procedure bcast_vertex module subroutine bcast_vertex(verts) Interface →
Arguments
Type Intent Optional Attributes Name
type(vertex), allocatable :: verts(:)
Calls
Called by
Contents
None
Call graph
bcast_vertex calls free_vertex, mypnum_, abort_psblas, alloc_vertex, icontxt_, psb_bcast, bcast_vector, bcast_vertex
free_vertex calls free_vertex, abort_psblas
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
alloc_vertex calls alloc_vertex, abort_psblas, vector_
icontxt_ calls icontxt_
bcast_vector calls bcast_vector, mypnum_, abort_psblas, icontxt_, psb_bcast, free_vector, alloc_vector
free_vector calls free_vector, abort_psblas
vector_ calls vector_
alloc_vector calls alloc_vector, abort_psblas
g2l_mesh calls bcast_vertex
create_mesh calls g2l_mesh, create_mesh