bcast_cell – Morfeus Framework
bcast_cell Module Procedure
50 statements
Source File
module procedure bcast_cell module subroutine bcast_cell(cells) Interface →
Arguments
Type Intent Optional Attributes Name
type(cell), allocatable :: cells(:)
Calls
Called by
Contents
None
Call graph
bcast_cell calls abort_psblas, psb_bcast, alloc_cell, icontxt_, mypnum_, bcast_cell
abort_psblas calls abort_psblas, psb_abort
alloc_cell calls alloc_cell, abort_psblas
icontxt_ calls icontxt_
mypnum_ calls mypnum_
g2l_mesh calls bcast_cell
create_mesh calls g2l_mesh, create_mesh