bld_part_random – Morfeus Framework
bld_part_random Module Procedure
31 statements
Source File
module procedure bld_part_random module subroutine bld_part_random(ncells, nprocs, part) Interface →
$ $ if(associated(part) .and. size(part) /= ncells) then $ deallocate(part) $ part => null() $ end if $ $ if(.not.associated(part)) then
$ end if
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncells
integer, intent(in) :: nprocs
integer, intent(out), allocatable :: part(:)
Calls
Called by
Contents
None
Call graph
bld_part_random calls mypnum_, icontxt_, abort_psblas, 16, bld_part_random
mypnum_ calls mypnum_
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort
cmp_mesh_part calls bld_part_random, cmp_mesh_part
create_mesh calls cmp_mesh_part, create_mesh