bld_part_graph – Morfeus Framework
bld_part_graph Module Procedure
60 statements
Source File
module procedure bld_part_graph module subroutine bld_part_graph(xadj_glob, adjncy_glob, ipart) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: xadj_glob(:)
integer, intent(in) :: adjncy_glob(:)
integer, intent(in) :: ipart
Calls
Called by
Contents
None
Call graph
bld_part_graph calls abort_psblas, perm, metis_partgraphkway, part_glob, nprocs_, pinv, 16, bld_part_graph
abort_psblas calls abort_psblas, psb_abort
nprocs_ calls nprocs_
cmp_mesh_part calls bld_part_graph, cmp_mesh_part
create_mesh calls cmp_mesh_part, create_mesh