bld_part_block – Morfeus Framework
bld_part_block Module Procedure
30 statements
Source File
module procedure bld_part_block module subroutine bld_part_block(ncells, nprocs, part) Interface →
$ end if
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncells
integer, intent(in) :: nprocs
integer, intent(out), allocatable :: part(:)
Calls
Called by
Contents
None
Call graph
bld_part_block calls 16, mypnum_, icontxt_, abort_psblas, bld_part_block
mypnum_ calls mypnum_
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort
cmp_mesh_part calls bld_part_block, cmp_mesh_part
create_mesh calls cmp_mesh_part, create_mesh