cell_ – Morfeus Framework
cell_ Module Procedure
6 statements
Source File
module procedure cell_ elemental module function cell_(nv, nf, group, geo) Interface →
Public default constructor
Workaround for Intel 18.0.5 error #6053: Structure constructor may not have fields with a PRIVATE attribute
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nv
integer, intent(in) :: nf
integer, intent(in) :: group
character(len=nlen), intent(in) :: geo
Return Value type(cell)
Called by
Contents
None
Call graph
cell_ calls cell_
rd_cgns_mesh calls cell_, rd_cgns_mesh
rd_exodus_mesh calls cell_, rd_exodus_mesh
rd_gmsh_mesh calls cell_, rd_gmsh_mesh
rd_gambit_mesh calls cell_, rd_gambit_mesh
import_mesh calls rd_gambit_mesh, rd_gmsh_mesh
create_mesh calls import_mesh, create_mesh