check_tet_quality – Morfeus Framework
check_tet_quality Module Procedure
64 statements
Source File
module procedure check_tet_quality module subroutine check_tet_quality(msh, ic, fmt) Interface →
Uses
class_psblas
class_cell
class_connectivity
class_mesh
class_vector
class_vertex
tools_math
tools_mesh_basics
tools_output_basics
Old call:
call wr_vtk_tet_cell(trim(file_name)//'.vtk',& & (/msh%verts(iv1),msh%verts(iv2),msh%verts(iv3),msh%verts(iv4)/)) interface subroutine wr_vtk_tet_cell(file_name,verts) use class_vertex character(len=*), intent(in) :: file_name type(vertex), intent(in) :: verts(4) end subroutine wr_vtk_tet_cell end interface
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(in) :: msh
integer, intent(in) :: ic
integer, intent(in), optional :: fmt
Calls
Called by
Contents
None
Call graph
check_tet_quality calls abort_psblas, geom_tet_dihedral_angle, loc_to_glob_, mypnum_, 3, geom_tet_quality, itoh, check_tet_quality
abort_psblas calls abort_psblas, psb_abort
geom_tet_dihedral_angle calls geom_tet_dihedral_angle
mypnum_ calls mypnum_
geom_tet_quality calls geom_tet_quality
itoh calls itoh, abort_psblas
check_mesh_quality calls check_tet_quality, check_mesh_quality