check_right_handed – Morfeus Framework
check_right_handed Module Procedure
64 statements
Source File
module procedure check_right_handed module subroutine check_right_handed(msh, shared, shared_flag, tangled, all_tets) Interface →
Uses
class_psblas
class_cell
class_connectivity
class_keytable
class_mesh
class_vector
class_vertex
tools_mesh_basics
tools_mesh_check
tools_mesh_optimize
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(in) :: msh
integer, intent(in), allocatable :: shared(:)
logical, intent(in), allocatable :: shared_flag(:)
integer, intent(out) :: tangled
logical, intent(in) :: all_tets(:)
Calls
Called by
Contents
None
Call graph
check_right_handed calls abort_psblas, psb_glob_to_loc, loc_to_glob_, right_handed, psb_cd_get_local_rows, check_right_handed
abort_psblas calls abort_psblas, psb_abort
smooth_mesh calls check_right_handed, smooth_mesh