check_vertex_quality – Morfeus Framework
check_vertex_quality Module Procedure
29 statements
Source File
module procedure check_vertex_quality module function check_vertex_quality(msh, ic2v) result(quality) Interface →
Uses
class_psblas
class_connectivity
class_mesh
tools_mesh_basics
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(in) :: msh
integer :: ic2v(:)
Return Value real(kind=psb_dpk_)
Calls
Called by
Contents
None
Call graph
check_vertex_quality calls geom_tet_quality, abort_psblas, check_vertex_quality
geom_tet_quality calls geom_tet_quality
abort_psblas calls abort_psblas, psb_abort