check_mesh_quality – Morfeus Framework
check_mesh_quality Module Procedure
241 statements
Source File
module procedure check_mesh_quality module subroutine check_mesh_quality(msh, fquality, tol, bad_cells, quiet) Interface →
Uses
class_psblas
class_cell
class_connectivity
class_mesh
class_scalar_field
class_vector
class_vertex
tools_math
tools_mesh_basics
tools_mesh_check
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(in) :: msh
type(scalar_field), intent(inout) :: fquality
real(kind=psb_dpk_), intent(in), optional :: tol
integer, intent(out), optional allocatable :: bad_cells(:)
logical, optional :: quiet
Calls
Called by
Contents
None
Call graph
check_mesh_quality calls psb_amx, psb_sum, geom_hex_quality, abort_psblas, psb_erractionsave, geom_tet_quality, psb_amn, psb_cd_get_local_rows, geom_tet_dihedral_angle, psb_erractionrestore, psb_get_loc_to_glob, icontxt_, check_tet_quality, mypnum_, geom_hex_dihedral_angle, get_cells_type, check_mesh_quality
geom_hex_quality calls geom_hex_quality
abort_psblas calls abort_psblas, psb_abort
geom_tet_quality calls geom_tet_quality
geom_tet_dihedral_angle calls geom_tet_dihedral_angle
icontxt_ calls icontxt_
check_tet_quality calls check_tet_quality, abort_psblas, geom_tet_quality, geom_tet_dihedral_angle, mypnum_, 3, loc_to_glob_, itoh
mypnum_ calls mypnum_
geom_hex_dihedral_angle calls geom_hex_dihedral_angle
get_cells_type calls get_cells_type, abort_psblas, psb_erractionsave, psb_erractionrestore, icontxt_, mypnum_, psb_cd_get_global_cols, psb_geall, psb_check_error, psb_gefree, psb_cd_get_local_cols, psb_gather
itoh calls itoh, abort_psblas