check_mesh_unused_el – Morfeus Framework
check_mesh_unused_el Module Procedure
31 statements
Source File
module procedure check_mesh_unused_el module subroutine check_mesh_unused_el(msh) Interface →
Arguments
Type Intent Optional Attributes Name
class(mesh), intent(in) :: msh
Calls
Called by
Contents
None
Call graph
check_mesh_unused_el calls mypnum_, abort_psblas, check_mesh_unused_el
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort