cmp_mesh_v2v – Morfeus Framework
cmp_mesh_v2v Module Procedure
69 statements
Source File
module procedure cmp_mesh_v2v module subroutine cmp_mesh_v2v(nverts, v2c, v2v) Interface →
Uses
class_psblas
class_connectivity
$Id: cmp_mesh_v2v.f90 3093 2008-04-22 14:51:09Z sfilippo $
Description: Provides the Vertex To Vertex adjacency graph. The criterium for associating the graph nodes is arbitrarly defined by the user. In this case, using a co-located cell-centered strategy for variable displacement, the V2V connectivity is obtained by linking each vertex to all the ones belonging to the cells which share it.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nverts
type(connectivity), intent(in) :: v2c
type(connectivity), intent(out) :: v2v
Calls
Called by
Contents
None
Call graph
cmp_mesh_v2v calls mypnum_, stopwatch_, abort_psblas, alloc_conn, icontxt_, cmp_mesh_v2v
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
alloc_conn calls alloc_conn, abort_psblas
icontxt_ calls icontxt_