cmp_mesh_f2b – Morfeus Framework
cmp_mesh_f2b Module Procedure
49 statements
Source File
module procedure cmp_mesh_f2b module subroutine cmp_mesh_f2b(faces, nbc, f2b) Interface →
Uses
class_psblas
class_connectivity
$Id: cmp_mesh_f2b.f90 3175 2008-06-13 12:59:07Z sfilippo $
Description:
$ iconn(1:n) = pack(iface,flag == ib)
Arguments
Type Intent Optional Attributes Name
type(face), intent(in) :: faces(:)
integer, intent(in) :: nbc
type(connectivity), intent(out) :: f2b
Calls
Called by
Contents
None
Call graph
cmp_mesh_f2b calls mypnum_, abort_psblas, alloc_conn, cmp_mesh_f2b
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
alloc_conn calls alloc_conn, abort_psblas
create_mesh calls cmp_mesh_f2b, create_mesh