cmp_mesh_desc – Morfeus Framework
cmp_mesh_desc Module Procedure
168 statements
Source File
module procedure cmp_mesh_desc module subroutine cmp_mesh_desc(v2v, v2c, f2f, f2c, c2c, desc_v, desc_f, desc_c) Interface →
Uses
class_connectivity
class_psblas
tools_part
tools_mesh_basics
$Id: cmp_mesh_desc.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description:
FACES brodcasting
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(inout) :: v2v
type(connectivity), intent(inout) :: v2c
type(connectivity), intent(inout) :: f2f
type(connectivity), intent(inout) :: f2c
type(connectivity), intent(inout) :: c2c
type(psb_desc_type), intent(out) :: desc_v
type(psb_desc_type), intent(out) :: desc_f
type(psb_desc_type), intent(out) :: desc_c
Calls
Called by
Contents
None
Call graph
cmp_mesh_desc calls g2l_conn, psb_get_loc_to_glob, psb_cdasb, psb_cdall, abort_psblas, mypnum_, icontxt_, psb_erractionsave, psb_cdins, psb_bcast, psb_check_error, free_conn, psb_cd_get_local_rows, bcast_conn, psb_erractionrestore, cmp_mesh_desc
abort_psblas calls abort_psblas, psb_abort
mypnum_ calls mypnum_
icontxt_ calls icontxt_
free_conn calls free_conn, abort_psblas
bcast_conn calls bcast_conn, abort_psblas, mypnum_, icontxt_, psb_bcast, alloc_conn
alloc_conn calls alloc_conn, abort_psblas
create_mesh calls cmp_mesh_desc, create_mesh