cmp_mesh_v2b – Morfeus Framework
cmp_mesh_v2b Module Procedure
54 statements
Source File
module procedure cmp_mesh_v2b module subroutine cmp_mesh_v2b(v2f, faces, nbc, v2b) Interface →
Uses
class_psblas
class_connectivity
$Id: cmp_mesh_v2b.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description: Sets up vertex to boundary connectivity, so that given a boundary, the GET_ITH_CONN method can be used to obtain the list of vertices that belong to the boundary. Boundary ID's correspond to those used to flag faces:
---------------------------| Vertex Flag | Vertex Type | ---------------------------| 0 | interior | < 0 | proc. bndry | > 0 | phys. bndry | ---------------------------|
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(in) :: v2f
type(face), intent(in) :: faces(:)
integer, intent(in) :: nbc
type(connectivity), intent(out) :: v2b
Calls
Called by
Contents
None
Call graph
cmp_mesh_v2b calls mypnum_, alloc_conn, free_conn, abort_psblas, cmp_mesh_v2b
mypnum_ calls mypnum_
alloc_conn calls alloc_conn, abort_psblas
free_conn calls free_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort
create_mesh calls cmp_mesh_v2b, create_mesh