cmp_mesh_f2f – Morfeus Framework
cmp_mesh_f2f Module Procedure
45 statements
Source File
module procedure cmp_mesh_f2f module subroutine cmp_mesh_f2f(nfaces, f2c, f2f) Interface →
Uses
class_psblas
class_connectivity
$Id: cmp_mesh_f2f.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description: Provides the Face To Face adjacency graph. The criterium for associating the graph nodes is arbitrarly defined by the user. In this case, using a co-located cell-centered strategy for variable displacement, the F2F connectivity is obtained by linking each face to all the ones belonging to its master and slave cells.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nfaces
type(connectivity), intent(in) :: f2c
type(connectivity), intent(out) :: f2f
Calls
Called by
Contents
None
Call graph
cmp_mesh_f2f calls mypnum_, alloc_conn, abort_psblas, cmp_mesh_f2f
mypnum_ calls mypnum_
alloc_conn calls alloc_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort
create_mesh calls cmp_mesh_f2f, create_mesh