cmp_mesh_c2c – Morfeus Framework
cmp_mesh_c2c Module Procedure
45 statements
Source File
module procedure cmp_mesh_c2c module subroutine cmp_mesh_c2c(faces, f2c, c2c) Interface →
Uses
class_psblas
class_connectivity
$Id: cmp_mesh_c2c.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description:
Arguments
Type Intent Optional Attributes Name
type(face), intent(in) :: faces(:)
type(connectivity), intent(in) :: f2c
type(connectivity), intent(out) :: c2c
Calls
Called by
Contents
None
Call graph
cmp_mesh_c2c calls mypnum_, alloc_conn, abort_psblas, cmp_mesh_c2c
mypnum_ calls mypnum_
alloc_conn calls alloc_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort
create_mesh calls cmp_mesh_c2c, create_mesh