cmp_mesh_v2ve – Morfeus Framework
cmp_mesh_v2ve Module Procedure
73 statements
Source File
module procedure cmp_mesh_v2ve module subroutine cmp_mesh_v2ve(ncd, v2f, v2v) Interface →
Uses
class_psblas
class_connectivity
tools_mesh
$Id: cmp_mesh_v2ve.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description: Builds a vertex to vertex connectivity based on edge connections.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncd
type(connectivity), intent(in) :: v2f
type(connectivity), intent(out) :: v2v
Calls
Called by
Contents
None
Call graph
cmp_mesh_v2ve calls mypnum_, stopwatch_, free_conn, abort_psblas, alloc_conn, icontxt_, cmp_mesh_v2e, cmp_mesh_v2ve
mypnum_ calls mypnum_
free_conn calls free_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort
alloc_conn calls alloc_conn, abort_psblas
icontxt_ calls icontxt_
cmp_mesh_v2e calls cmp_mesh_v2e, mypnum_, stopwatch_, free_conn, abort_psblas, alloc_conn, icontxt_
create_mesh calls cmp_mesh_v2ve, create_mesh