cmp_moving_surf – Morfeus Framework
cmp_moving_surf Module Procedure
21 statements
Source File
module procedure cmp_moving_surf module subroutine cmp_moving_surf(nbc, v2b, verts, surf) Interface →
Uses
class_psblas
class_connectivity
class_surface
class_vertex
$Id: cmp_moving_surf.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description: Allocates and calculates shapes of moving surfaces
$ if (associated (surf)) then $ call abort_psblas $ endif
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nbc
type(connectivity), intent(in) :: v2b
type(vertex), intent(in) :: verts(:)
type(surface), intent(out), allocatable :: surf(:)
Calls
Called by
Contents
None
Call graph
cmp_moving_surf calls mypnum_, abort_psblas, cmp_moving_surf
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
create_mesh calls cmp_moving_surf, create_mesh