cmp_mesh_part – Morfeus Framework
cmp_mesh_part Module Procedure
51 statements
Source File
module procedure cmp_mesh_part module subroutine cmp_mesh_part(ipart, nswpref, c2c) Interface →
Uses
class_psblas
class_connectivity
tools_part
part_graph
part_block
part_random
$Id: cmp_mesh_part.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description:
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ipart
integer, intent(in) :: nswpref
type(connectivity), intent(in) :: c2c
Calls
Called by
Contents
None
Call graph
cmp_mesh_part calls mypnum_, abort_psblas, bld_part_graph, nprocs_, bld_part_random, bld_part_block, get_part_graph, cmp_mesh_part
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
bld_part_graph calls bld_part_graph, abort_psblas, nprocs_, perm, 16, pinv, part_glob, metis_partgraphkway
nprocs_ calls nprocs_
bld_part_random calls bld_part_random, mypnum_, abort_psblas, icontxt_, 16
bld_part_block calls bld_part_block, mypnum_, abort_psblas, icontxt_, 16
get_part_graph calls get_part_graph, abort_psblas, free_part_graph, part_glob
icontxt_ calls icontxt_
create_mesh calls cmp_mesh_part, create_mesh