cmp_mesh_renum – Morfeus Framework
cmp_mesh_renum Module Procedure
34 statements
Source File
module procedure cmp_mesh_renum module subroutine cmp_mesh_renum(irenum, cells, faces, c2c, f2c, v2c, c2g) Interface →
Uses
class_psblas
class_cell
class_connectivity
renum
$Id: cmp_mesh_renum.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description:
 call print_renum(0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: irenum
type(cell), intent(inout) :: cells(:)
type(face), intent(inout) :: faces(:)
type(connectivity), intent(inout) :: c2c
type(connectivity), intent(inout) :: f2c
type(connectivity), intent(inout) :: v2c
type(connectivity), intent(inout) :: c2g
Calls
Called by
Contents
None
Call graph
cmp_mesh_renum calls apply_renum, abort_psblas, icontxt_, start_renum, mypnum_, stop_renum, cmp_mesh_renum
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
start_renum calls start_renum, abort_psblas, mypnum_, perm, build_pinv, cmp_gps
mypnum_ calls mypnum_
stop_renum calls stop_renum
build_pinv calls build_pinv, abort_psblas, icontxt_, mypnum_, perm, pinv
cmp_gps calls cmp_gps, abort_psblas, perm, psb_gps_reduce
create_mesh calls cmp_mesh_renum, create_mesh