cmp_mesh_v2e – Morfeus Framework
cmp_mesh_v2e Module Procedure
89 statements
Source File
module procedure cmp_mesh_v2e module subroutine cmp_mesh_v2e(ncd, v2f, v2e) Interface →
Uses
class_psblas
class_connectivity
$Id: cmp_mesh_v2e.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description: Provides the Vertex To Edge connectivity.
$ if((iv4 == iv1 .and. iv3 == iv2) .or.& $ iv4 == iv2 .and. iv3 == iv1) then $ twice(ie2) = .true. $ end if
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncd
type(connectivity), intent(in) :: v2f
type(connectivity), intent(out) :: v2e
Calls
Called by
Contents
None
Call graph
cmp_mesh_v2e calls abort_psblas, free_conn, icontxt_, stopwatch_, mypnum_, alloc_conn, cmp_mesh_v2e
abort_psblas calls abort_psblas, psb_abort
free_conn calls free_conn, abort_psblas
icontxt_ calls icontxt_
mypnum_ calls mypnum_
alloc_conn calls alloc_conn, abort_psblas
cmp_mesh_v2ve calls cmp_mesh_v2e, cmp_mesh_v2ve
create_mesh calls cmp_mesh_v2ve, create_mesh