concatenate_columns – Morfeus Framework
concatenate_columns Module Procedure
12 statements
Source File
module procedure concatenate_columns pure module function concatenate_columns(a, b) result(concatenated) Interface →
Using RESHAPE rather than manipulating array elements directly frees the compiler to decide the particular order of array element references that best exploits the given platform. Alternatively, DO CONCURRENT could instead free the compiler to order element accesses however is best. Trade-off: RESHAPE requires the creation of temporary array results but RESHAPE is likely to have more mature compiler support than DO CONCURRENT. If this code turns out to be a critical performance bottleneck, try replacing this implementation with element-by-element copying using DO CONCURRENT.
Arguments
Type Intent Optional Attributes Name
real(kind=r8k), intent(in), dimension(:,:) :: a
real(kind=r8k), intent(in), dimension(:,:) :: b
Return Value real(kind=r8k), dimension(:,:),allocatable
Called by
Contents
None
Call graph
concatenate_columns calls concatenate_columns
operator(.catcolumns.) calls concatenate_columns
concatenate_rows calls concatenate_columns, concatenate_rows
operator(.catrows.) calls concatenate_rows