copy_conn – Morfeus Framework
copy_conn Procedure
9 statements
Source File
module procedure copy_conn module procedure copy_conn()
Arguments
None
Calls
Contents
None
Call graph
copy_conn calls alloc_conn
alloc_conn calls alloc_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort