create_iterating – Morfeus Framework
create_iterating Module Procedure
40 statements
Source File
module procedure create_iterating module subroutine create_iterating(iter, input_file, sec, itype) Interface →
Uses
class_psblas
tools_input
tools_math
json_module
Arguments
Type Intent Optional Attributes Name
class(iterating), intent(out) :: iter
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
integer, intent(in) :: itype
Calls
Called by
Contents
None
Call graph
create_iterating calls open_file, abort_psblas, create_iterating
open_file calls open_file, abort_psblas
abort_psblas calls abort_psblas, psb_abort