create_scalar_source – Morfeus Framework
create_scalar_source Module Procedure
20 statements
Source File
module procedure create_scalar_source module subroutine create_scalar_source(src, input_file, sec, dim) Interface →
Uses
tools_input
json_module
Arguments
Type Intent Optional Attributes Name
class(scalar_source), intent(inout) :: src
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
type(dimensions), intent(in) :: dim
Calls
Called by
Contents
None
Call graph
create_scalar_source calls open_file, mypnum_, create_scalar_source
open_file calls open_file, abort_psblas
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort