create_mesh – Morfeus Framework
create_mesh Module Procedure
77 statements
Source File
module procedure create_mesh module subroutine create_mesh(msh, input_file, sec) Interface →
Uses
tools_mesh
tools_mesh_basics
tools_output_basics
class_least_squares
Global constructor $ call cmp_mesh_v2v(nverts,msh%v2c,msh%v2v) ! Computes MESH%V2V $ call wr_mtx_pattern(msh%v2v,'pattern_vert_1.mtx') $ call wr_mtx_pattern(msh%v2v,'pattern_vert_2.mtx') ! to be done bcast_surf
Arguments
Type Intent Optional Attributes Name
class(mesh), intent(out) :: msh
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
Calls
Called by
Contents
None
Call graph
create_mesh calls abort_psblas, cmp_mesh_desc, import_mesh, cmp_moving_surf, cmp_mesh_f2b, cmp_mesh_part, bcast_face, geom_cell, geom_diff, rd_inp_mesh, mypnum_, cmp_mesh_v2b, geom_face, cmp_mesh_c2c, g2l_mesh, nprocs_, cmp_mesh_renum, wr_mtx_pattern, cmp_mesh_f2f, supplement_v2f, icontxt_, set_least_squares, supplement_v2c, cmp_mesh_v2ve, create_mesh
abort_psblas calls abort_psblas, psb_abort
cmp_mesh_desc calls cmp_mesh_desc, abort_psblas, mypnum_, icontxt_, psb_bcast, bcast_conn, g2l_conn, free_conn, psb_cd_get_local_rows, psb_cdasb, psb_cdall, psb_erractionrestore, psb_get_loc_to_glob, psb_cdins, psb_check_error, psb_erractionsave
import_mesh calls abort_psblas, mypnum_, icontxt_, rd_gmsh_mesh, psb_bcast, rd_gambit_mesh
cmp_moving_surf calls cmp_moving_surf, abort_psblas, mypnum_
cmp_mesh_f2b calls cmp_mesh_f2b, abort_psblas, mypnum_, alloc_conn
cmp_mesh_part calls cmp_mesh_part, abort_psblas, mypnum_, nprocs_, get_part_graph, bld_part_graph, bld_part_random, bld_part_block
bcast_face calls bcast_face, abort_psblas, mypnum_, icontxt_, psb_bcast, alloc_face
geom_cell calls geom_cell, abort_psblas, vector_, geom_tet_center, vertex_, geom_tet_volume, alloc_vector, 3
geom_diff calls geom_diff, abort_psblas, mypnum_, icontxt_, vector_, psb_sum, 3
rd_inp_mesh calls rd_inp_mesh, mypnum_, icontxt_, psb_bcast, open_file
mypnum_ calls mypnum_
cmp_mesh_v2b calls cmp_mesh_v2b, abort_psblas, mypnum_, free_conn, alloc_conn
geom_face calls geom_face, abort_psblas, vector_, alloc_vector, 3
cmp_mesh_c2c calls cmp_mesh_c2c, abort_psblas, mypnum_, alloc_conn
g2l_mesh calls mypnum_, bcast_cell, g2l_cell, bcast_conn, bcast_vertex, g2l_face, g2l_conn, g2l_vertex
nprocs_ calls nprocs_
cmp_mesh_renum calls cmp_mesh_renum, abort_psblas, mypnum_, icontxt_, apply_renum, stop_renum, start_renum
wr_mtx_pattern calls wr_mtx_pattern, mypnum_
cmp_mesh_f2f calls cmp_mesh_f2f, abort_psblas, mypnum_, alloc_conn
supplement_v2f calls supplement_v2f, abort_psblas, mypnum_, nprocs_, icontxt_, bcast_conn, free_conn, psb_loc_to_glob, psb_erractionrestore, psb_get_overlap, psb_erractionsave
icontxt_ calls icontxt_
set_least_squares calls set_least_squares, mypnum_, psb_cd_get_local_rows, alloc_least_squares
supplement_v2c calls supplement_v2c, abort_psblas, mypnum_, nprocs_, icontxt_, free_conn, psb_loc_to_glob, psb_erractionrestore, psb_get_overlap, psb_erractionsave
cmp_mesh_v2ve calls cmp_mesh_v2ve, abort_psblas, mypnum_, icontxt_, free_conn, alloc_conn, stopwatch_, cmp_mesh_v2e
bcast_cell calls bcast_cell, abort_psblas, mypnum_, icontxt_, psb_bcast, alloc_cell
rd_gmsh_mesh calls rd_gmsh_mesh, abort_psblas, vertex_, alloc_face, cell_, 8, alloc_vertex, alloc_cell, 6, face_
g2l_cell calls g2l_cell, psb_get_loc_to_glob, alloc_cell, psb_cd_get_local_cols
bcast_conn calls bcast_conn, abort_psblas, mypnum_, icontxt_, psb_bcast, alloc_conn
rd_gambit_mesh calls rd_gambit_mesh, abort_psblas, vertex_, alloc_face, 3, cell_, 8, alloc_vertex, alloc_cell, 6, face_
bcast_vertex calls bcast_vertex, abort_psblas, mypnum_, icontxt_, psb_bcast, alloc_vertex, bcast_vector, free_vertex
g2l_face calls g2l_face, alloc_face, psb_get_loc_to_glob, psb_get_glob_to_loc, psb_cd_get_local_cols
g2l_vertex calls g2l_vertex, abort_psblas, psb_get_loc_to_glob, alloc_vertex, psb_cd_get_local_cols, free_vertex
free_conn calls free_conn, abort_psblas
vector_ calls vector_
geom_tet_center calls geom_tet_center
geom_tet_volume calls geom_tet_volume
get_part_graph calls get_part_graph, abort_psblas, part_glob, free_part_graph
bld_part_graph calls bld_part_graph, abort_psblas, nprocs_, perm, metis_partgraphkway, part_glob, pinv, 16
stop_renum calls stop_renum
alloc_face calls alloc_face, abort_psblas
open_file calls open_file, abort_psblas
alloc_vector calls alloc_vector, abort_psblas
alloc_conn calls alloc_conn, abort_psblas
start_renum calls start_renum, abort_psblas, mypnum_, build_pinv, cmp_gps, perm
bld_part_random calls bld_part_random, abort_psblas, mypnum_, icontxt_, 16
bld_part_block calls bld_part_block, abort_psblas, mypnum_, icontxt_, 16
cmp_mesh_v2e calls cmp_mesh_v2e, abort_psblas, mypnum_, icontxt_, free_conn, alloc_conn, stopwatch_
alloc_least_squares calls alloc_least_squares, abort_psblas
cell_ calls cell_
alloc_vertex calls alloc_vertex, abort_psblas, vector_
alloc_cell calls alloc_cell, abort_psblas
bcast_vector calls bcast_vector, abort_psblas, mypnum_, icontxt_, psb_bcast, alloc_vector, free_vector
face_ calls face_
free_vertex calls free_vertex, abort_psblas
build_pinv calls build_pinv, abort_psblas, mypnum_, icontxt_, perm, pinv
cmp_gps calls cmp_gps, abort_psblas, perm, psb_gps_reduce
free_vector calls free_vector, abort_psblas