create_scalar_field – Morfeus Framework
create_scalar_field Module Procedure
98 statements
Source File
module procedure create_scalar_field module subroutine create_scalar_field(fld, msh, dim, bc, mats, on_faces, x0, name) Interface →
Uses
class_bc
class_connectivity
class_dimensions
class_material
class_mesh
class_cell
class_face
tools_material
Arguments
Type Intent Optional Attributes Name
class(scalar_field), intent(out) :: fld
type(mesh), intent(in), target :: msh
type(dimensions), intent(in), optional :: dim
type(bc_poly), intent(in), optional target :: bc(:)
type(matptr), intent(in), optional target :: mats(:)
logical, intent(in), optional :: on_faces
real(kind=psb_dpk_), intent(in), optional :: x0
character(len=*), intent(in), optional :: name
Calls
Called by
Contents
None
Call graph
create_scalar_field calls matlaw, abort_psblas, create_scalar_field
abort_psblas calls abort_psblas, psb_abort