create_output – Morfeus Framework
create_output Module Procedure
47 statements
Source File
module procedure create_output module function create_output(input_file, sec) result(out) Interface →
Uses
tools_input
tools_output_basics
class_psblas
json_module
class_vtk_output
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
Return Value class(output), allocatable
Calls
Called by
Contents
None
Call graph
create_output calls open_file, mypnum_, abort_psblas, create_output
open_file calls open_file, abort_psblas
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort