create_bc – Morfeus Framework
create_bc Module Procedure
51 statements
Source File
module procedure create_bc module subroutine create_bc(bc, input_file, sec, msh) Interface →
Uses
class_mesh
tools_bc
tools_input
Global constructor
Arguments
Type Intent Optional Attributes Name
type(bc_poly), allocatable :: bc(:)
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
type(mesh), intent(in) :: msh
Calls
Called by
Contents
None
Call graph
create_bc calls mypnum_, abort_psblas, create_bc
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort