create_bc_math – Morfeus Framework
create_bc_math Module Procedure
19 statements
Source File
module procedure create_bc_math module subroutine create_bc_math(bc, input_file, sec, nbf) Interface →
Uses
class_mesh
tools_bc
Arguments
Type Intent Optional Attributes Name
type(bc_math), pointer :: bc
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
integer, intent(in) :: nbf
Calls
Called by
Contents
None
Call graph
create_bc_math calls rd_inp_bc_math, abort_psblas, create_bc_math
rd_inp_bc_math calls rd_inp_bc_math, abort_psblas, open_file, mypnum_, find_section, icontxt_, psb_bcast
abort_psblas calls abort_psblas, psb_abort
open_file calls open_file, abort_psblas
mypnum_ calls mypnum_
find_section calls find_section, abort_psblas
icontxt_ calls icontxt_