create_motion – Morfeus Framework
create_motion Module Procedure
14 statements
Source File
module procedure create_motion module subroutine create_motion(mot, surface_motion, vertex_motion, ml_file) Interface →
Uses
class_psblas
tools_mesh_move
Arguments
Type Intent Optional Attributes Name
class(motion), intent(inout) :: mot
integer, intent(in) :: surface_motion
integer, intent(in) :: vertex_motion
character(len=*), intent(in) :: ml_file
Calls
Called by
Contents
None
Call graph
create_motion calls abort_psblas, rd_inp_motion_law, create_motion
abort_psblas calls abort_psblas, psb_abort
rd_inp_motion_law calls rd_inp_motion_law, abort_psblas, open_file, mypnum_, icontxt_, vector_, psb_bcast, alloc_vector, bcast_vector
open_file calls open_file, abort_psblas
mypnum_ calls mypnum_
icontxt_ calls icontxt_
vector_ calls vector_
alloc_vector calls alloc_vector, abort_psblas
bcast_vector calls bcast_vector, abort_psblas, mypnum_, icontxt_, psb_bcast, alloc_vector, free_vector
free_vector calls free_vector, abort_psblas