create_bc_wall – Morfeus Framework
create_bc_wall Module Procedure
17 statements
Source File
module procedure create_bc_wall module subroutine create_bc_wall(bc, input_file, sec, nbf) Interface →
Arguments
Type Intent Optional Attributes Name
type(bc_wall), pointer :: bc
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
integer, intent(in) :: nbf
Calls
Called by
Contents
None
Call graph
create_bc_wall calls rd_inp_bc_wall, abort_psblas, create_bc_wall
rd_inp_bc_wall calls abort_psblas, open_file, icontxt_, psb_bcast, mypnum_
abort_psblas calls abort_psblas, psb_abort
open_file calls open_file, abort_psblas
icontxt_ calls icontxt_
mypnum_ calls mypnum_