create_material – Morfeus Framework
create_material Module Procedure
7 statements
Source File
module procedure create_material module subroutine create_material(mat, input_file, block_id) Interface →
Uses
tools_material
Global Constructor
Arguments
Type Intent Optional Attributes Name
class(material), intent(out) :: mat
character(len=*), intent(in) :: input_file
integer, intent(in) :: block_id
Calls
Called by
Contents
None
Call graph
create_material calls set_material_ids, load_material, rd_inp_material, create_material
load_material calls load_material, load_water, load_copper
rd_inp_material calls rd_inp_material, icontxt_, psb_bcast, mypnum_, open_file, 4
icontxt_ calls icontxt_
mypnum_ calls mypnum_
load_water calls load_water, abort_psblas
load_copper calls load_copper, abort_psblas
open_file calls open_file, abort_psblas
abort_psblas calls abort_psblas, psb_abort