create_pde – Morfeus Framework
create_pde Module Procedure
11 statements
Source File
module procedure create_pde module subroutine create_pde(eqn, input_file, sec, msh, dim) Interface →
Uses
class_dimensions
class_mesh
Arguments
Type Intent Optional Attributes Name
class(vector_pde), intent(out) :: eqn
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
type(mesh), intent(inout), target :: msh
type(dimensions), intent(in) :: dim
Calls
Called by
Contents
None
Call graph
create_pde calls psb_geall, psb_erractionrestore, psb_erractionsave, icontxt_, create_pde
icontxt_ calls icontxt_