exists – Morfeus Framework
exists Function
5 statements
Source File
elemental function exists(image) result(image_exists)
Result true if image number is within the closed range [1,num_images()]
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: image
Return Value logical
Called by
Contents
None
Call graph
co_broadcast_integer calls exists, co_broadcast_integer
co_sum_integer calls exists, co_sum_integer
co_sum calls co_sum_integer
co_broadcast calls co_broadcast_integer