file_extension – Morfeus Framework
file_extension Module Procedure
11 statements
Source File
module procedure file_extension pure module function file_extension(file_name) result(extension) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name
Return Value character(len=:), allocatable
Called by
Contents
None
Call graph
file_extension calls file_extension
set_grid_specification calls file_extension, set_grid_specification
write_output calls file_extension, write_output