find_section – Morfeus Framework
find_section Module Procedure
38 statements
Source File
module procedure find_section module subroutine find_section(sec, nemo_json) Interface →
Uses
class_psblas
json_module
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: sec
type(json_file), intent(inout) :: nemo_json
Calls
Called by
Contents
None
Call graph
find_section calls abort_psblas, find_section
abort_psblas calls abort_psblas, psb_abort
read_par_h calls find_section
rd_inp_bc_math calls find_section, rd_inp_bc_math
read_par_discretization calls find_section
read_par_i calls find_section
read_par_l calls find_section
read_par_v calls find_section
create_bc_math calls rd_inp_bc_math, create_bc_math