first_index – Morfeus Framework
first_index Function
10 statements
Source File
pure function first_index(block_id) result(outbox_1st_index)
result is the halo_outbox first index corresponding to the block identifier block_id
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: block_id
Return Value integer
Called by
Contents
None
Call graph
get_normal_scalar_fluxes calls first_index, get_normal_scalar_fluxes
is_external_boundary calls first_index, is_external_boundary
get_neighbor_block_id calls first_index, get_neighbor_block_id
get_surface_positions calls first_index, get_surface_positions
set_normal_scalar_fluxes calls first_index, set_normal_scalar_fluxes