flux_pde_div – Morfeus Framework
flux_pde_div Module Procedure
140 statements
Source File
module procedure flux_pde_div module subroutine flux_pde_div(sign, pde, flux, side, ds) Interface →
Uses
class_psblas
class_discretization
class_dimensions
class_vector
class_mesh
tools_operators
class_mesh
This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: flux
real(kind=psb_dpk_), intent(in), optional :: side
type(discretization), intent(in), optional :: ds
Calls
Called by
Contents
None
Call graph
flux_pde_div calls abort_psblas, pde_sign, geins_pde, check_mesh_consistency, size_blk, psb_get_loc_to_glob, mypnum_, flux_pde_div
pde_sign calls pde_sign, abort_psblas
check_mesh_consistency calls check_mesh_consistency, abort_psblas
size_blk calls size_blk
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
pde_div calls flux_pde_div