free_part_graph – Morfeus Framework
free_part_graph Subroutine
7 statements
Source File
subroutine free_part_graph()
Arguments
None
Called by
Contents
Source Code
free_part_graph
Source Code
    SUBROUTINE free_part_graph
        DEALLOCATE(part_glob)
        IF(ALLOCATED(xadj))    DEALLOCATE(xadj)
        IF(ALLOCATED(adjncy))  DEALLOCATE(adjncy)
        IF(ALLOCATED(perm))    DEALLOCATE(perm)
        IF(ALLOCATED(pinv))    DEALLOCATE(pinv)
    END SUBROUTINE free_part_graph
Call graph
get_part_graph calls free_part_graph, get_part_graph
cmp_mesh_part calls get_part_graph, cmp_mesh_part
create_mesh calls cmp_mesh_part, create_mesh