free_mesh – Morfeus Framework
free_mesh Module Procedure
51 statements
Source File
module procedure free_mesh module subroutine free_mesh(msh) Interface →
Uses
psb_base_mod
class_least_squares
----- Destructor -----
Arguments
Type Intent Optional Attributes Name
class(mesh), intent(inout) :: msh
Calls
Called by
Contents
None
Call graph
free_mesh calls free_vector, free_vertex, psb_check_error, mypnum_, psb_erractionsave, free_conn, free_least_squares, icontxt_, free_face, psb_cdfree, free_cell, psb_erractionrestore, free_mesh
free_vector calls free_vector, abort_psblas
free_vertex calls free_vertex, abort_psblas
mypnum_ calls mypnum_
free_conn calls free_conn, abort_psblas
free_least_squares calls free_least_squares, abort_psblas
icontxt_ calls icontxt_
free_face calls free_face, abort_psblas
free_cell calls free_cell, abort_psblas
abort_psblas calls abort_psblas, psb_abort