free_face – Morfeus Framework
free_face Module Procedure
12 statements
Source File
module procedure free_face module subroutine free_face(faces) Interface →
Arguments
Type Intent Optional Attributes Name
type(face), allocatable :: faces(:)
Calls
Called by
Contents
None
Call graph
free_face calls abort_psblas, free_face
abort_psblas calls abort_psblas, psb_abort
free_mesh calls free_face, free_mesh