g2l_face – Morfeus Framework
g2l_face Module Procedure
42 statements
Source File
module procedure g2l_face module subroutine g2l_face(faces, desc_f, desc_c) Interface →
Uses
psb_base_mod
Arguments
Type Intent Optional Attributes Name
type(face), allocatable :: faces(:)
type(psb_desc_type), intent(in) :: desc_f
type(psb_desc_type), intent(in) :: desc_c
Calls
Called by
Contents
None
Call graph
g2l_face calls psb_cd_get_local_cols, psb_get_loc_to_glob, psb_get_glob_to_loc, alloc_face, g2l_face
alloc_face calls alloc_face, abort_psblas
abort_psblas calls abort_psblas, psb_abort
g2l_mesh calls g2l_face
create_mesh calls g2l_mesh, create_mesh