g2l_vector – Morfeus Framework
g2l_vector Module Procedure
19 statements
Source File
module procedure g2l_vector module subroutine g2l_vector(verts, desc_v) Interface →
Uses
psb_base_mod
Arguments
Type Intent Optional Attributes Name
type(vector), allocatable :: verts(:)
type(psb_desc_type), intent(in) :: desc_v
Calls
Called by
Contents
None
Call graph
g2l_vector calls alloc_vector, psb_get_loc_to_glob, free_vector, psb_cd_get_local_cols, g2l_vector
alloc_vector calls alloc_vector, abort_psblas
free_vector calls free_vector, abort_psblas
abort_psblas calls abort_psblas, psb_abort