g2l_mesh – Morfeus Framework
g2l_mesh Subroutine
21 statements
Source File
subroutine g2l_mesh(msh)
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(inout) :: msh
Calls
Called by
Contents
Source Code
g2l_mesh
Source Code
    SUBROUTINE g2l_mesh(msh)
        IMPLICIT NONE
        !!
        TYPE(mesh), INTENT(INOUT) :: msh
        CALL sw_g2l%tic()
        IF(mypnum_() == 0) THEN
            WRITE(*,*) 'Global to local reallocation of MESH object'
            WRITE(*,*)
        END IF
        CALL g2l_conn(msh%v2f,msh%desc_v,msh%desc_f)    ! Reallocates MSH%V2F
        CALL g2l_face(msh%faces,msh%desc_f,msh%desc_c)  ! Reallocates MSH%FACES
        CALL bcast_cell(msh%cells)                      ! Broadcast   MSH%CELLS
        CALL g2l_cell(msh%cells,msh%desc_c)             ! Reallocates MSH%CELLS
        CALL bcast_vertex(msh%verts)                    ! Broadcast   MSH%VERTS
        CALL g2l_vertex(msh%verts,msh%desc_v)           ! Reallocates MSH%VERTS
        CALL g2l_conn(msh%v2c,msh%desc_v,msh%desc_c)    ! Reallocates MSH%V2C
        CALL bcast_conn(msh%c2g)                        ! Broadcast   MSH%C2G
        CALL g2l_conn(msh%c2g,msh%desc_c)               ! Reallocates MSH%C2G
        !
        CALL bcast_conn(msh%v2b)                        ! Broadcast   MSH%V2B
        CALL g2l_conn(msh%v2b,msh%desc_v)               ! Reallocates MSH%V2B
        CALL sw_g2l%toc()
    END SUBROUTINE g2l_mesh
Call graph
g2l_mesh calls bcast_vertex, mypnum_, bcast_cell, bcast_conn, g2l_vertex, g2l_cell, g2l_conn, g2l_face
bcast_vertex calls bcast_vertex, mypnum_, free_vertex, abort_psblas, alloc_vertex, icontxt_, psb_bcast, bcast_vector
mypnum_ calls mypnum_
bcast_cell calls bcast_cell, mypnum_, abort_psblas, alloc_cell, icontxt_, psb_bcast
bcast_conn calls bcast_conn, mypnum_, abort_psblas, alloc_conn, icontxt_, psb_bcast
g2l_vertex calls g2l_vertex, free_vertex, abort_psblas, psb_cd_get_local_cols, alloc_vertex, psb_get_loc_to_glob
g2l_cell calls g2l_cell, psb_cd_get_local_cols, alloc_cell, psb_get_loc_to_glob
g2l_face calls g2l_face, alloc_face, psb_get_glob_to_loc, psb_cd_get_local_cols, psb_get_loc_to_glob
free_vertex calls free_vertex, abort_psblas
abort_psblas calls abort_psblas, psb_abort
alloc_face calls alloc_face, abort_psblas
alloc_conn calls alloc_conn, abort_psblas
alloc_cell calls alloc_cell, abort_psblas
alloc_vertex calls alloc_vertex, abort_psblas, vector_
icontxt_ calls icontxt_
bcast_vector calls bcast_vector, mypnum_, abort_psblas, icontxt_, psb_bcast, free_vector, alloc_vector
free_vector calls free_vector, abort_psblas
vector_ calls vector_
alloc_vector calls alloc_vector, abort_psblas
create_mesh calls g2l_mesh, create_mesh