g2l_conn_core – Morfeus Framework
g2l_conn_core Module Procedure
40 statements
Source File
module procedure g2l_conn_core module subroutine g2l_conn_core(a2b, iglob_to_loc_a, iloc_to_glob_b) Interface →
Arguments
Type Intent Optional Attributes Name
class(connectivity), intent(inout) :: a2b
integer, intent(in) :: iglob_to_loc_a(:)
integer, intent(in) :: iloc_to_glob_b(:)
IP - 5/27/2019: This work-around fixes an ICE with Intel 18.0.5.274 Note: The ICE only shows up when building the submodule that implements this procedure
Calls
Called by
Contents
None
Call graph
g2l_conn_core calls alloc_conn, free_conn, g2l_conn_core
alloc_conn calls alloc_conn, abort_psblas
free_conn calls free_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort