g2l_vertex – Morfeus Framework
g2l_vertex Module Procedure
27 statements
Source File
module procedure g2l_vertex module subroutine g2l_vertex(verts, desc_v) Interface →
Uses
psb_base_mod
Arguments
Type Intent Optional Attributes Name
type(vertex), allocatable :: verts(:)
type(psb_desc_type), intent(in) :: desc_v
Calls
Called by
Contents
None
Call graph
g2l_vertex calls alloc_vertex, abort_psblas, free_vertex, psb_cd_get_local_cols, psb_get_loc_to_glob, g2l_vertex
alloc_vertex calls alloc_vertex, abort_psblas, vector_
abort_psblas calls abort_psblas, psb_abort
free_vertex calls free_vertex, abort_psblas
vector_ calls vector_
g2l_mesh calls g2l_vertex
create_mesh calls g2l_mesh, create_mesh