g2l_cell – Morfeus Framework
g2l_cell Module Procedure
21 statements
Source File
module procedure g2l_cell module subroutine g2l_cell(cells, desc_c) Interface →
Uses
psb_base_mod
Arguments
Type Intent Optional Attributes Name
type(cell), allocatable :: cells(:)
type(psb_desc_type), intent(in) :: desc_c
Calls
Called by
Contents
None
Call graph
g2l_cell calls psb_get_loc_to_glob, psb_cd_get_local_cols, alloc_cell, g2l_cell
alloc_cell calls alloc_cell, abort_psblas
abort_psblas calls abort_psblas, psb_abort
g2l_mesh calls g2l_cell
create_mesh calls g2l_mesh, create_mesh