geom_cell – Morfeus Framework
geom_cell Module Procedure
195 statements
Source File
module procedure geom_cell module subroutine geom_cell(verts, faces, cells, v2f, v2c, f2c, ncd, cell_cntr, vol, quiet) Interface →
Uses
class_psblas
class_connectivity
class_vector
class_vertex
tools_mesh_basics
$ if(allocated(cell_cntr) .or. & $ & allocated(vol)) then $ call abort_psblas $ end if
Arguments
Type Intent Optional Attributes Name
type(vertex), intent(in), allocatable :: verts(:)
type(face), intent(in), allocatable :: faces(:)
type(cell), intent(in), allocatable :: cells(:)
type(connectivity), intent(in) :: v2f
type(connectivity), intent(in) :: v2c
type(connectivity), intent(in) :: f2c
integer, intent(in) :: ncd
type(vector), intent(out), allocatable :: cell_cntr(:)
real(kind=psb_dpk_), intent(out), allocatable :: vol(:)
logical, intent(in), optional :: quiet
Calls
Called by
Contents
None
Call graph
geom_cell calls vector_, alloc_vector, geom_tet_center, abort_psblas, geom_tet_volume, vertex_, 3, geom_cell
vector_ calls vector_
alloc_vector calls alloc_vector, abort_psblas
geom_tet_center calls geom_tet_center
abort_psblas calls abort_psblas, psb_abort
geom_tet_volume calls geom_tet_volume
create_mesh calls geom_cell, create_mesh
smooth_mesh calls geom_cell, smooth_mesh