geom_diff – Morfeus Framework
geom_diff Module Procedure
88 statements
Source File
module procedure geom_diff module subroutine geom_diff(faces, f2b, face_cntr, af, cell_cntr, df, dist, int_fact) Interface →
Uses
class_psblas
class_connectivity
$ if(allocated(df) .or. & $ & allocated(dist) .or. & $ & allocated(int_fact)) then $ call abort_psblas $ end if
Arguments
Type Intent Optional Attributes Name
type(face), intent(in), allocatable :: faces(:)
type(connectivity), intent(in) :: f2b
type(vector), intent(in), allocatable :: face_cntr(:)
type(vector), intent(in), allocatable :: af(:)
type(vector), intent(in), allocatable :: cell_cntr(:)
type(vector), intent(out), allocatable :: df(:)
real(kind=psb_dpk_), intent(out), allocatable :: dist(:)
real(kind=psb_dpk_), intent(out), allocatable :: int_fact(:)
Calls
Called by
Contents
None
Call graph
geom_diff calls mypnum_, abort_psblas, psb_sum, icontxt_, 3, vector_, geom_diff
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
vector_ calls vector_
create_mesh calls geom_diff, create_mesh
smooth_mesh calls geom_diff, smooth_mesh