geom_face – Morfeus Framework
geom_face Module Procedure
77 statements
Source File
module procedure geom_face module subroutine geom_face(verts, v2f, ncd, face_cntr, af, area) Interface →
Uses
class_psblas
class_connectivity
class_vertex
$ if(allocated(face_cntr) .or. & $ & allocated(af) .or. & $ & allocated(area)) then $ call abort_psblas $ end if
Arguments
Type Intent Optional Attributes Name
type(vertex), intent(in), allocatable :: verts(:)
type(connectivity), intent(in) :: v2f
integer, intent(in) :: ncd
type(vector), intent(out), allocatable :: face_cntr(:)
type(vector), intent(out), allocatable :: af(:)
real(kind=psb_dpk_), intent(out), allocatable :: area(:)
Calls
Called by
Contents
None
Call graph
geom_face calls alloc_vector, 3, vector_, abort_psblas, geom_face
alloc_vector calls alloc_vector, abort_psblas
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
smooth_mesh calls geom_face, smooth_mesh
create_mesh calls geom_face, create_mesh