geom_tet_center – Morfeus Framework
geom_tet_center Module Procedure
5 statements
Source File
module procedure geom_tet_center module function geom_tet_center(v1, v2, v3, v4) Interface →
Uses
class_vertex
Computes center of mass
Arguments
Type Intent Optional Attributes Name
type(vertex), intent(in) :: v1
type(vertex), intent(in) :: v2
type(vertex), intent(in) :: v3
type(vertex), intent(in) :: v4
Return Value type(vector)
Called by
Contents
None
Call graph
geom_tet_center calls geom_tet_center
geom_cell calls geom_tet_center, geom_cell
create_mesh calls geom_cell, create_mesh
smooth_mesh calls geom_cell, smooth_mesh