geom_tet_dihedral_angle – Morfeus Framework
geom_tet_dihedral_angle Module Procedure
20 statements
Source File
module procedure geom_tet_dihedral_angle module subroutine geom_tet_dihedral_angle(af, largest, smallest) Interface →
Uses
class_psblas
tools_math
Initialize to smallest possible value Initialize to largest possible value
Arguments
Type Intent Optional Attributes Name
type(vector), intent(in) :: af(4)
real(kind=psb_dpk_), intent(out) :: largest
real(kind=psb_dpk_), intent(out) :: smallest
Called by
Contents
None
Call graph
geom_tet_dihedral_angle calls geom_tet_dihedral_angle
check_tet_quality calls geom_tet_dihedral_angle, check_tet_quality
check_mesh_quality calls geom_tet_dihedral_angle, check_tet_quality, check_mesh_quality