geom_tet_quality – Morfeus Framework
geom_tet_quality Module Procedure
19 statements
Source File
module procedure geom_tet_quality module function geom_tet_quality(v1, v2, v3, v4, vol) Interface →
Uses
class_psblas
class_vector
class_vertex
Arguments
Type Intent Optional Attributes Name
type(vertex), intent(in) :: v1
type(vertex), intent(in) :: v2
type(vertex), intent(in) :: v3
type(vertex), intent(in) :: v4
real(kind=psb_dpk_), intent(in) :: vol
Return Value real(kind=psb_dpk_)
Called by
Contents
None
Call graph
geom_tet_quality calls geom_tet_quality
check_tet_quality calls geom_tet_quality, check_tet_quality
check_mesh_quality calls geom_tet_quality, check_tet_quality, check_mesh_quality
check_vertex_quality calls geom_tet_quality, check_vertex_quality