get_par_d – Morfeus Framework
get_par_d Procedure
38 statements
Source File
module procedure get_par_d module procedure get_par_d()
Uses
class_psblas
tools_input
Arguments
None
Calls
Contents
None
Call graph
get_par_d calls abort_psblas
abort_psblas calls abort_psblas, psb_abort