get_abc_math_s – Morfeus Framework
get_abc_math_s Procedure
36 statements
Source File
module procedure get_abc_math_s module procedure get_abc_math_s()
Uses
class_mesh
tools_bc
Arguments
None
Calls
Contents
None
Call graph
get_abc_math_s calls b, abort_psblas, a, c
abort_psblas calls abort_psblas, psb_abort