get_vector_field – Morfeus Framework
get_vector_field Module Procedure
42 statements
Source File
module procedure get_vector_field module function get_vector_field(fld) result(x_glob) Interface →
Uses
class_psblas
class_cell
class_vector
class_iterating
class_mesh
class_output
class_vector_field
tools_output_basics
class_scalar_field
$ msh => msh_(fld)
$ call psb_check_error(info,'set_vector_field','psb_gather',icontxt)
Arguments
Type Intent Optional Attributes Name
type(vector_field), intent(in) :: fld
Return Value real(kind=psb_dpk_), allocatable,(:,:)
Calls
Called by
Contents
None
Call graph
get_vector_field calls mypnum_, psb_erractionsave, abort_psblas, l2g_vector, icontxt_, psb_cd_get_global_cols, psb_erractionrestore, l2g_cell, get_vector_field
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
l2g_vector calls l2g_vector, mypnum_, psb_erractionsave, abort_psblas, icontxt_, psb_cd_get_global_cols, psb_erractionrestore, psb_check_error, psb_geall, psb_ovrl, psb_gefree, psb_gather, alloc_vector
icontxt_ calls icontxt_
l2g_cell calls l2g_cell, mypnum_, psb_erractionsave, abort_psblas, icontxt_, psb_cd_get_global_cols, psb_erractionrestore, psb_check_error, psb_geall, psb_gefree, alloc_cell, psb_gather
alloc_cell calls alloc_cell, abort_psblas
alloc_vector calls alloc_vector, abort_psblas