get_cells_type – Morfeus Framework
get_cells_type Module Procedure
108 statements
Source File
module procedure get_cells_type module subroutine get_cells_type(cells, nctype, ictype, desc) Interface →
Uses
psb_base_mod
$ No longer necessary because of INTENT(OUT) $ ! Checks that NCTYPE (output) is not associated $ if(associated(nctype)) then $ deallocate(nctype) $ end if $ $ ! Checks that ICTYPE (output) is not associated $ if(associated(ictype)) then $ deallocate(ictype) $ end if
$ call psb_gather(glob_vect,loc_vect,desc,info,root=-1) ! BUG!!
Arguments
Type Intent Optional Attributes Name
type(cell), intent(in) :: cells(:)
array of cells structs
integer, intent(out), allocatable :: nctype(:)
count of each type
integer, intent(out), allocatable :: ictype(:)
array of cell id's sorted by type
type(psb_desc_type), intent(in), optional :: desc
Calls
Called by
Contents
None
Call graph
get_cells_type calls psb_cd_get_global_cols, abort_psblas, psb_geall, psb_erractionsave, psb_check_error, psb_gefree, psb_erractionrestore, psb_cd_get_local_cols, psb_gather, icontxt_, mypnum_, get_cells_type
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
mypnum_ calls mypnum_
check_mesh_quality calls get_cells_type, check_mesh_quality