get_abc_math_v – Morfeus Framework
get_abc_math_v Procedure
37 statements
Source File
module procedure get_abc_math_v module procedure get_abc_math_v()
Uses
class_mesh
class_vector
tools_bc
WARNING! Use intent(inout) for A, B and C. REMARK: BC(:) elements are supposed to differ only in "C" term
Arguments
None
Calls
Contents
None
Call graph
get_abc_math_v calls b, abort_psblas, a, c, bc, vector_
abort_psblas calls abort_psblas, psb_abort
vector_ calls vector_