get_par_i – Morfeus Framework
get_par_i Procedure
38 statements
Source File
module procedure get_par_i module procedure get_par_i()
Uses
class_psblas
tools_input
Arguments
None
Calls
Contents
None
Call graph
get_par_i calls abort_psblas
abort_psblas calls abort_psblas, psb_abort