get_par_h – Morfeus Framework
get_par_h Procedure
42 statements
Source File
module procedure get_par_h module procedure get_par_h()
Uses
class_psblas
tools_input
Arguments
None
Calls
Contents
None
Call graph
get_par_h calls abort_psblas
abort_psblas calls abort_psblas, psb_abort