get_motion_displacement – Morfeus Framework
get_motion_displacement Module Procedure
29 statements
Source File
module procedure get_motion_displacement module function get_motion_displacement(mot, x1, x2) Interface →
Uses
tools_math
tools_mesh_move
Arguments
Type Intent Optional Attributes Name
class(motion), intent(in) :: mot
real(kind=psb_dpk_), intent(in) :: x1
real(kind=psb_dpk_), intent(in) :: x2
Return Value type(vector)
Calls
Called by
Contents
None
Call graph
get_motion_displacement calls pwl_nearest, pwl_interp, vector_, get_motion_displacement
pwl_nearest calls pwl_nearest, abort_psblas
pwl_interp calls pwl_interp_x_vec, pwl_interp_x_s, pwl_interp_x_v, pwl_interp_dx_s, pwl_interp_dx_v
vector_ calls vector_
pwl_interp_x_vec calls pwl_interp_x_vec, pwl_nearest, abort_psblas
pwl_interp_x_s calls pwl_interp_x_s, pwl_nearest, abort_psblas
pwl_interp_x_v calls pwl_interp_x_v, pwl_nearest, abort_psblas
pwl_interp_dx_s calls pwl_interp_dx_s
pwl_interp_dx_v calls pwl_interp_dx_v, abort_psblas
abort_psblas calls abort_psblas, psb_abort