get_part_graph – Morfeus Framework
get_part_graph Module Procedure
17 statements
Source File
module procedure get_part_graph module subroutine get_part_graph(part) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(out), allocatable :: part(:)
Calls
Called by
Contents
None
Call graph
get_part_graph calls part_glob, free_part_graph, abort_psblas, get_part_graph
abort_psblas calls abort_psblas, psb_abort
cmp_mesh_part calls get_part_graph, cmp_mesh_part
create_mesh calls cmp_mesh_part, create_mesh