get_motion_velocity – Morfeus Framework
get_motion_velocity Module Procedure
18 statements
Source File
module procedure get_motion_velocity module function get_motion_velocity(mot, x) Interface →
Uses
tools_math
tools_mesh_move
Arguments
Type Intent Optional Attributes Name
class(motion), intent(in) :: mot
real(kind=psb_dpk_), intent(in) :: x
Return Value type(vector)
Calls
Called by
Contents
None
Call graph
get_motion_velocity calls pwl_interp, vector_, pwl_deriv, get_motion_velocity
pwl_interp calls pwl_interp_dx_v, pwl_interp_x_vec, pwl_interp_x_v, pwl_interp_x_s, pwl_interp_dx_s
vector_ calls vector_
pwl_deriv calls pwl_deriv_x_s, pwl_deriv_x_v, pwl_deriv_x_vec
pwl_deriv_x_s calls pwl_deriv_x_s, pwl_nearest, abort_psblas
pwl_interp_dx_v calls pwl_interp_dx_v, abort_psblas
pwl_interp_x_vec calls pwl_interp_x_vec, pwl_nearest, abort_psblas
pwl_deriv_x_v calls pwl_deriv_x_v, pwl_nearest, abort_psblas
pwl_interp_x_v calls pwl_interp_x_v, pwl_nearest, abort_psblas
pwl_interp_x_s calls pwl_interp_x_s, pwl_nearest, abort_psblas
pwl_interp_dx_s calls pwl_interp_dx_s
pwl_deriv_x_vec calls pwl_deriv_x_vec, pwl_nearest, abort_psblas
pwl_nearest calls pwl_nearest, abort_psblas
abort_psblas calls abort_psblas, psb_abort