get_scalar_field – Morfeus Framework
get_scalar_field Module Procedure
35 statements
Source File
module procedure get_scalar_field module function get_scalar_field(fld) result(x_glob) Interface →
Uses
class_psblas
class_cell
class_iterating
class_mesh
class_output
class_scalar_field
tools_output_basics
$ msh => msh_(fld)
Arguments
Type Intent Optional Attributes Name
type(scalar_field), intent(in) :: fld
Return Value real(kind=psb_dpk_), allocatable,(:)
Calls
Called by
Contents
None
Call graph
get_scalar_field calls psb_gather, abort_psblas, psb_erractionsave, icontxt_, psb_check_error, psb_cd_get_global_cols, l2g_cell, psb_erractionrestore, get_scalar_field
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
l2g_cell calls l2g_cell, psb_gather, abort_psblas, psb_erractionsave, icontxt_, psb_check_error, psb_cd_get_global_cols, psb_erractionrestore, alloc_cell, psb_geall, psb_gefree, mypnum_
alloc_cell calls alloc_cell, abort_psblas
mypnum_ calls mypnum_