icontxt_ – Morfeus Framework
icontxt_ Module Procedure
3 statements
Source File
module procedure icontxt_ module function icontxt_() Interface →
Arguments
None
Return Value integer
Called by
Contents
None
Call graph
icontxt_ calls icontxt_
create_mesh calls icontxt_, import_mesh, cmp_mesh_desc, bcast_face, geom_diff, rd_inp_mesh, cmp_mesh_renum, supplement_v2f, supplement_v2c, cmp_mesh_v2ve, g2l_mesh, cmp_mesh_part, create_mesh
read_par_i calls icontxt_
geom_diff calls icontxt_, geom_diff
free_mesh calls icontxt_, free_mesh
bcast_face calls icontxt_, bcast_face
write_vtk_mesh calls icontxt_
free_pde_prec calls icontxt_, free_pde_prec
import_mesh calls icontxt_
geins_vector_pde_r calls icontxt_, geins_vector_pde_r
wr_mtx_matrix calls icontxt_, wr_mtx_matrix
geins_scalar_pde calls icontxt_, geins_scalar_pde
read_par_h calls icontxt_
l2g_cell calls icontxt_, l2g_cell
cmp_mesh_renum calls icontxt_, start_renum, cmp_mesh_renum
free_pde calls icontxt_, free_pde
rd_inp_mesh calls icontxt_, rd_inp_mesh
psb_solve_sys calls icontxt_, psb_solve_sys
laplacian_smooth calls icontxt_, solve_sys, laplacian_smooth
read_par_discretization calls icontxt_
write_scalar_field calls icontxt_, write_scalar_field
bcast_vector calls icontxt_, bcast_vector
rd_inp_bc_math calls icontxt_, rd_inp_bc_math
rd_inp_bc calls icontxt_, rd_inp_bc
get_scalar_field calls icontxt_, l2g_cell, get_scalar_field
get_cells_type calls icontxt_, get_cells_type
read_par_l calls icontxt_
asb_pde_ calls icontxt_, asb_pde_
bcast_vertex calls icontxt_, bcast_vector, bcast_vertex
bld_part_block calls icontxt_, bld_part_block
l2g_conn calls icontxt_, l2g_conn
bcast_dim calls icontxt_, bcast_dim
smooth_mesh calls icontxt_, geom_diff, laplacian_smooth, update_vertex_halo, smooth_mesh
rd_inp_material calls icontxt_, rd_inp_material
supplement_v2f calls icontxt_, bcast_conn, supplement_v2f
bcast_conn calls icontxt_, bcast_conn
bcast_cell calls icontxt_, bcast_cell
nemo_mesh_size calls icontxt_
update_vector_halo calls icontxt_, update_vector_halo
l2g_vertex calls icontxt_, l2g_vector, l2g_vertex
build_pinv calls icontxt_, build_pinv
cmp_mesh_desc calls icontxt_, bcast_conn, cmp_mesh_desc
cmp_mesh_v2ve calls icontxt_, cmp_mesh_v2e, cmp_mesh_v2ve
supplement_v2c calls icontxt_, supplement_v2c
write_exo_morfeus calls icontxt_, l2g_vertex, l2g_face, l2g_conn, l2g_cell, l2g_vector, write_exo_morfeus
wr_mtx_vector calls icontxt_, wr_mtx_vector
rd_inp_bc_wall calls icontxt_
write_vector_field calls icontxt_, l2g_cell, l2g_vector, write_vector_field
write_mesh calls icontxt_, l2g_vertex, l2g_face, l2g_conn, l2g_cell, write_mesh
rd_inp_motion_law calls icontxt_, bcast_vector, rd_inp_motion_law
create_pde calls icontxt_, create_pde
read_par_v calls icontxt_
cmp_mesh_v2e calls icontxt_, cmp_mesh_v2e
check_mesh_quality calls icontxt_, get_cells_type, check_mesh_quality
solve_vector_pde calls icontxt_, solve_vector_pde
update_scalar_field calls icontxt_, update_scalar_field
l2g_vector calls icontxt_, l2g_vector
spins_pde calls icontxt_, spins_pde
read_par_d calls icontxt_
l2g_face calls icontxt_, l2g_face
reinit_pde calls icontxt_, reinit_pde
bld_part_random calls icontxt_, bld_part_random
cmp_mesh_v2v calls icontxt_, cmp_mesh_v2v
psb_build_prec calls icontxt_
get_vector_field calls icontxt_, l2g_cell, l2g_vector, get_vector_field
solve_scalar_pde calls icontxt_, solve_scalar_pde
write_vtk_morfeus calls write_vtk_mesh, write_vtk_morfeus
create_bc_wall calls rd_inp_bc_wall, create_bc_wall
update_vertex_halo calls update_vector_halo, update_vertex_halo
create_bc_math calls rd_inp_bc_math, create_bc_math
create_motion calls rd_inp_motion_law, create_motion
solve_sys calls psb_solve_sys
write_field calls write_vector_field, write_scalar_field
scalar_field_grad calls update_vector_halo, scalar_field_grad
g2l_mesh calls bcast_cell, bcast_conn, bcast_vertex
create_material calls rd_inp_material, create_material
write_scalar_pde calls wr_mtx_vector, write_scalar_pde
start_renum calls build_pinv, start_renum
write_vector_pde calls wr_mtx_vector, write_vector_pde
geins_vector_pde_v calls geins_vector_pde_r, geins_vector_pde_v
write_pde calls wr_mtx_matrix, write_pde
cmp_mesh_part calls bld_part_random, bld_part_block, cmp_mesh_part
update_vector_field calls update_vector_halo, update_vector_field
solve_pde_sys calls solve_sys, solve_pde_sys
solve_least_squares calls solve_sys, solve_least_squares
alloc_plane calls solve_sys, alloc_plane
fld_grad calls scalar_field_grad
vector_pde_grad calls fld_grad, vector_pde_grad
scalar_pde_laplacian calls fld_grad, scalar_pde_laplacian
alloc_surface calls alloc_plane, alloc_surface
vector_pde_laplacian calls fld_grad, vector_pde_laplacian
pde_grad calls vector_pde_grad
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
pde_laplacian calls scalar_pde_laplacian_phi, vector_pde_laplacian_phi, vector_pde_laplacian_gamma_phi, scalar_pde_laplacian_gamma_phi