import_mesh – Morfeus Framework
import_mesh Subroutine
50 statements
Source File
subroutine import_mesh(msh, mesh_file)
Uses
tools_mesh
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(inout) :: msh
character(len=*), intent(inout) :: mesh_file
Calls
Called by
Contents
Source Code
import_mesh
Source Code
    SUBROUTINE import_mesh(msh,mesh_file)
        USE tools_mesh
        IMPLICIT NONE
        !
        TYPE(mesh), INTENT(INOUT) :: msh
        CHARACTER(len=*), INTENT(INOUT) :: mesh_file
        !
        INTEGER :: i, intbuf(2)
        INTEGER :: icontxt, mypnum
        CHARACTER(len=4) :: fmt
        icontxt = icontxt_()
        mypnum  = mypnum_()
        CALL sw_msh%tic()
        ! Reads the mesh object on P0...
        IF(mypnum == 0) THEN
            ! Sets mesh format
            mesh_file = ADJUSTR(mesh_file)
            i = SCAN(mesh_file,'.',back=.TRUE.)
            IF(i == 0) THEN
                WRITE(*,100)
                WRITE(*,'(a24,a80)')'Expected to find file: ',mesh_file
                CALL abort_psblas
            END IF
            i = i + 1
            fmt = mesh_file(i:LEN(mesh_file))
            SELECT CASE (fmt)
            CASE('cgns')
#ifdef HAVE_CGNS
                CALL rd_cgns_mesh(mesh_file, msh%id, msh%nbc, msh%ncd, &
                    & msh%verts, msh%faces, msh%cells, &
                    & msh%v2f, msh%v2c, msh%f2c, msh%c2g)
#else
                ERROR STOP "MORFEUS built without CNGS support! Unable to continue."
#endif
            CASE('e')
#ifdef HAVE_EXODUS
                CALL rd_exodus_mesh(mesh_file, msh%id, msh%nbc, msh%ncd, &
                    & msh%verts, msh%faces, msh%cells, &
                    & msh%v2f, msh%v2c, msh%f2c, msh%c2g)
#else
                ERROR STOP "MORFEUS built without exodus support! Unable to continue."
#endif
            CASE('msh')
                CALL rd_gmsh_mesh(mesh_file, msh%id, msh%nbc, msh%ncd, &
                    & msh%verts, msh%faces, msh%cells, &
                    & msh%v2f, msh%v2c, msh%f2c, msh%c2g)
            CASE('neu')
                CALL rd_gambit_mesh(mesh_file, msh%id, msh%nbc, msh%ncd, &
                    & msh%verts, msh%faces, msh%cells, &
                    & msh%v2f, msh%v2c, msh%f2c, msh%c2g)
            CASE DEFAULT
                WRITE(*,200)
                CALL abort_psblas
            END SELECT
        END IF
        ! ... then bcast msh%(id,nbc,ncd)
        IF(mypnum == 0) THEN
            CALL psb_bcast(icontxt,msh%id)
            intbuf(1) = msh%nbc
            intbuf(2) = msh%ncd
            CALL psb_bcast(icontxt,intbuf)
        ELSE
            CALL psb_bcast(icontxt,msh%id)
            CALL psb_bcast(icontxt,intbuf)
            msh%nbc = intbuf(1)
            msh%ncd = intbuf(2)
        END IF
        CALL sw_msh%toc()
100     FORMAT('ERROR! Unsupported mesh filename in IMPORT_MESH')
200     FORMAT('ERROR! Unsupported mesh format in IMPORT_MESH')
    END SUBROUTINE import_mesh
Call graph
import_mesh calls abort_psblas, rd_gambit_mesh, psb_bcast, rd_gmsh_mesh, icontxt_, mypnum_
abort_psblas calls abort_psblas, psb_abort
rd_gambit_mesh calls rd_gambit_mesh, abort_psblas, 3, alloc_vertex, face_, 8, alloc_cell, vertex_, alloc_face, 6, cell_
rd_gmsh_mesh calls rd_gmsh_mesh, abort_psblas, alloc_vertex, face_, 8, alloc_cell, vertex_, alloc_face, 6, cell_
icontxt_ calls icontxt_
mypnum_ calls mypnum_
alloc_vertex calls alloc_vertex, abort_psblas, vector_
face_ calls face_
alloc_cell calls alloc_cell, abort_psblas
alloc_face calls alloc_face, abort_psblas
cell_ calls cell_
vector_ calls vector_
create_mesh calls import_mesh, create_mesh