initialize_from_sphere_1d – Morfeus Framework
initialize_from_sphere_1d Module Procedure
27 statements
Source File
module procedure initialize_from_sphere_1d module subroutine initialize_from_sphere_1d(this, sphere_1d_geometry) Interface →
Uses
spherical_grid_interface
partition a block-structured grids across images
Arguments
Type Intent Optional Attributes Name
class(problem_discretization), intent(inout) :: this
type(sphere_1d), intent(in) :: sphere_1d_geometry
Calls
Called by
Contents
None
Call graph
initialize_from_sphere_1d calls my_blocks, initialize_from_sphere_1d
my_blocks calls my_blocks