initialize_from_cylinder_2d – Morfeus Framework
initialize_from_cylinder_2d Module Procedure
26 statements
Source File
module procedure initialize_from_cylinder_2d module subroutine initialize_from_cylinder_2d(this, cylinder_2d_geometry) Interface →
Uses
cylindrical_grid_interface
partition a block-structured grids across images
Arguments
Type Intent Optional Attributes Name
class(problem_discretization), intent(inout) :: this
type(cylinder_2d), intent(in) :: cylinder_2d_geometry
Calls
Called by
Contents
None
Call graph
initialize_from_cylinder_2d calls my_blocks, initialize_from_cylinder_2d
my_blocks calls my_blocks