l2g_vector – Morfeus Framework
l2g_vector Module Procedure
42 statements
Source File
module procedure l2g_vector module subroutine l2g_vector(verts_loc, verts_glob, desc_v) Interface →
Uses
psb_base_mod
Arguments
Type Intent Optional Attributes Name
type(vector) :: verts_loc(:)
type(vector), allocatable :: verts_glob(:)
type(psb_desc_type), intent(in) :: desc_v
Calls
Called by
Contents
None
Call graph
l2g_vector calls psb_check_error, psb_ovrl, psb_geall, abort_psblas, psb_erractionsave, mypnum_, psb_gefree, icontxt_, psb_cd_get_global_cols, psb_gather, alloc_vector, psb_erractionrestore, l2g_vector
abort_psblas calls abort_psblas, psb_abort
mypnum_ calls mypnum_
icontxt_ calls icontxt_
alloc_vector calls alloc_vector, abort_psblas
l2g_vertex calls l2g_vector, l2g_vertex
write_vector_field calls l2g_vector, write_vector_field
write_exo_morfeus calls l2g_vector, l2g_vertex, write_exo_morfeus
get_vector_field calls l2g_vector, get_vector_field
write_field calls write_vector_field
write_mesh calls l2g_vertex, write_mesh