l2g_face – Morfeus Framework
l2g_face Module Procedure
53 statements
Source File
module procedure l2g_face module subroutine l2g_face(faces_loc, faces_glob, desc_f, desc_c) Interface →
Uses
psb_base_mod
WARNING! The global results is allocated only on P0. After its usage it must be deallocated in the calling unit by means of the statement: "if(associated(glob_res)) deallocate(glob_res)"
Arguments
Type Intent Optional Attributes Name
type(face), allocatable :: faces_loc(:)
type(face), allocatable :: faces_glob(:)
type(psb_desc_type), intent(in) :: desc_f
type(psb_desc_type), intent(in) :: desc_c
Calls
Called by
Contents
None
Call graph
l2g_face calls psb_check_error, psb_geall, abort_psblas, psb_erractionsave, mypnum_, alloc_face, psb_gefree, icontxt_, psb_get_loc_to_glob, psb_cd_get_global_cols, psb_gather, psb_erractionrestore, l2g_face
abort_psblas calls abort_psblas, psb_abort
mypnum_ calls mypnum_
alloc_face calls alloc_face, abort_psblas
icontxt_ calls icontxt_
write_mesh calls l2g_face, write_mesh
write_exo_morfeus calls l2g_face, write_exo_morfeus