l2g_vertex – Morfeus Framework
l2g_vertex Module Procedure
25 statements
Source File
module procedure l2g_vertex module subroutine l2g_vertex(verts_loc, verts_glob, desc_v) Interface →
Uses
psb_base_mod
Arguments
Type Intent Optional Attributes Name
type(vertex), allocatable :: verts_loc(:)
type(vertex), allocatable :: verts_glob(:)
type(psb_desc_type), intent(in) :: desc_v
Calls
Called by
Contents
None
Call graph
l2g_vertex calls free_vector, l2g_vector, alloc_vertex, alloc_vector, psb_erractionsave, icontxt_, mypnum_, psb_cd_get_global_cols, psb_erractionrestore, l2g_vertex
free_vector calls free_vector, abort_psblas
l2g_vector calls l2g_vector, alloc_vector, psb_erractionsave, icontxt_, mypnum_, psb_cd_get_global_cols, psb_erractionrestore, psb_gather, psb_ovrl, abort_psblas, psb_check_error, psb_geall, psb_gefree
alloc_vertex calls alloc_vertex, vector_, abort_psblas
alloc_vector calls alloc_vector, abort_psblas
icontxt_ calls icontxt_
mypnum_ calls mypnum_
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
write_mesh calls l2g_vertex, write_mesh
write_exo_morfeus calls l2g_vertex, write_exo_morfeus