laplacian_smooth – Morfeus Framework
laplacian_smooth Module Procedure
147 statements
Source File
module procedure laplacian_smooth module subroutine laplacian_smooth(desc_v, v2v, n_unconstrained, unconstrained, verts, mixed) Interface →
Uses
class_psblas
class_connectivity
class_vector
class_vertex
tools_mesh_basics
tools_math
Arguments
Type Intent Optional Attributes Name
type(psb_desc_type), intent(inout) :: desc_v
type(connectivity), intent(inout) :: v2v
integer, intent(in) :: n_unconstrained
integer, intent(in) :: unconstrained(:)
type(vertex), intent(inout), allocatable :: verts(:)
logical, intent(in) :: mixed(:)
Calls
Called by
Contents
None
Call graph
laplacian_smooth calls psb_cd_get_local_rows, abort_psblas, icontxt_, solve_sys, psb_geasb, psb_erractionsave, psb_ovrl, psb_erractionrestore, psb_precfree, psb_geall, psb_spall, psb_geins, vector_, psb_spasb, psb_spfree, psb_gefree, psb_check_error, psb_spins, loc_to_glob_, build_prec, laplacian_smooth
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
solve_sys calls cholesky_solve_m, psb_solve_sys, lu_solve, cholesky_solve_v
vector_ calls vector_
build_prec calls psb_build_prec
cholesky_solve_m calls cholesky_solve_m
psb_solve_sys calls psb_solve_sys, icontxt_, psb_erractionsave, psb_erractionrestore, psb_check_error, mypnum_, psb_krylov
lu_solve calls lu_solve
cholesky_solve_v calls cholesky_solve_v
mypnum_ calls mypnum_
smooth_mesh calls laplacian_smooth, smooth_mesh