lin_interp_v – Morfeus Framework
lin_interp_v Module Procedure
6 statements
Source File
module procedure lin_interp_v module function lin_interp_v(f1, f2, fac) Interface →
Uses
class_psblas
class_vector
Arguments
Type Intent Optional Attributes Name
type(vector), intent(in) :: f1
type(vector), intent(in) :: f2
real(kind=psb_dpk_), intent(in) :: fac
Return Value type(vector)
Called by
Contents
None
Call graph
lin_interp_v calls lin_interp_v
lin_interp calls lin_interp_v
interp_on_faces_s calls lin_interp, interp_on_faces_s
update_scalar_field calls lin_interp, update_scalar_field
interp_on_faces_v calls lin_interp, interp_on_faces_v