load_material – Morfeus Framework
load_material Module Procedure
14 statements
Source File
module procedure load_material module subroutine load_material(name, state, dtemp, tmin, tmax, rho, mu, lambda, sh) Interface →
Uses
mat_copper
mat_water
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
character(len=1), intent(out) :: state
real(kind=psb_dpk_), intent(out) :: dtemp
real(kind=psb_dpk_), intent(out) :: tmin
real(kind=psb_dpk_), intent(out) :: tmax
real(kind=psb_dpk_), intent(out), allocatable :: rho(:)
real(kind=psb_dpk_), intent(out), allocatable :: mu(:)
real(kind=psb_dpk_), intent(out), allocatable :: lambda(:)
real(kind=psb_dpk_), intent(out), allocatable :: sh(:)
Calls
Called by
Contents
None
Call graph
load_material calls load_water, load_copper, load_material
load_water calls load_water, abort_psblas
load_copper calls load_copper, abort_psblas
abort_psblas calls abort_psblas, psb_abort
create_material calls load_material, create_material