loc_to_glob_ – Morfeus Framework
loc_to_glob_ Module Procedure
10 statements
Source File
module procedure loc_to_glob_ module function loc_to_glob_(desc, iloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(psb_desc_type), intent(in) :: desc
integer, intent(in) :: iloc
Return Value integer
Calls
Called by
Contents
None
Call graph
loc_to_glob_ calls psb_check_error, psb_loc_to_glob, psb_erractionsave, psb_erractionrestore, psb_cd_get_context, loc_to_glob_
psb_check_error calls psb_check_error, psb_error, psb_errpush