lu_fact_2 – Morfeus Framework
lu_fact_2 Subroutine
51 statements
Source File
subroutine lu_fact_2(a, ipiv, info)
Uses
class_psblas
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(inout) :: a(2,2)
integer, intent(out) :: ipiv(2)
integer, intent(out) :: info
Called by
Contents
Source Code
lu_fact_2
Source Code
    SUBROUTINE  lu_fact_2(a,ipiv,info)
        USE class_psblas, ONLY : psb_dpk_
        REAL(psb_dpk_), INTENT(INOUT) :: A(2,2)
        INTEGER, INTENT(OUT) :: ipiv(2)
        INTEGER, INTENT(OUT) :: info
        !
        REAL(psb_dpk_) ::tmp, swp(2)
        INTEGER :: j, k, jp
        REAL(psb_dpk_), PARAMETER :: tol = 1.d-20
        info = 0
        IF (.FALSE.) THEN
            DO j = 1, 2
                jp = j - 1 + MAXLOC(ABS(a(j:,j)),dim=1)
                ipiv(j) = jp
                IF (jp /= j) THEN
                    DO k=1,2
                        tmp     = a(j,k)
                        a(j,k)  = a(jp,k)
                        a(jp,k) = tmp
                    END DO
                END IF
                IF(ABS(a(j,j)) < tol) THEN
                    info = j
                ELSE
                    a(j+1:,j) = a(j+1:,j) * (1.d0/a(j,j))
                END IF
                DO k = j + 1, 2
                    a(j+1:,k) = a(j+1:,k) - a(j,k) * a(j+1:,j)
                END DO
            END DO
        ELSE
            jp = 1 - 1 + MAXLOC(ABS(a(1:,1)),dim=1)
            ipiv(1) = jp
            IF (jp /= 1) THEN
                swp(1:2) = a(1,1:2)
                a(1,1:2) = a(jp,1:2)
                a(jp,1:2) = swp(1:2)
            END IF
            IF(ABS(a(1,1)) < tol) THEN
                info = 1
            ELSE
                a(1+1:,1) = a(1+1:,1) * (1.d0/a(1,1))
            END IF
            DO k = 1 + 1, 2
                a(1+1:,k) = a(1+1:,k) - a(1,k) * a(1+1:,1)
            END DO
            ipiv(2) = 2
            IF(ABS(a(2,2)) < tol) THEN
                info = 2
            END IF
        ENDIF
    END SUBROUTINE lu_fact_2
Call graph
lu_fact calls lu_fact_2, lu_fact
factorize calls lu_fact
alloc_plane calls factorize, alloc_plane
alloc_surface calls alloc_plane, alloc_surface