lu_solve – Morfeus Framework
lu_solve Module Procedure
22 statements
Source File
module procedure lu_solve module subroutine lu_solve(n, a, ipiv, b, info) Interface →
Uses
class_psblas
Solve a system Ax=b where A has already been factored. Adapted from LAPACK, this is supposed to be called with small sizes (4 or thereabout)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=psb_dpk_), intent(in) :: a(n,n)
integer, intent(in) :: ipiv(n)
real(kind=psb_dpk_), intent(inout) :: b(n)
integer, intent(out) :: info
Called by
Contents
None
Call graph
lu_solve calls lu_solve
solve_sys calls lu_solve
laplacian_smooth calls solve_sys, laplacian_smooth
solve_pde_sys calls solve_sys, solve_pde_sys
solve_least_squares calls solve_sys, solve_least_squares
alloc_plane calls solve_sys, alloc_plane
alloc_surface calls alloc_plane, alloc_surface
smooth_mesh calls laplacian_smooth, smooth_mesh