mobile_verts – Morfeus Framework
mobile_verts Module Procedure
75 statements
Source File
module procedure mobile_verts module subroutine mobile_verts(msh, bc, c2v, shared_flag, unconstrained, n_unconstrained, constrained, n_constrained, all_tets, mixed) Interface →
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(in) :: msh
type(bc_poly), intent(in) :: bc(:)
type(connectivity), intent(in) :: c2v
logical, intent(in) :: shared_flag(:)
integer, intent(out) :: unconstrained(:)
integer, intent(out) :: n_unconstrained
integer, intent(out) :: constrained(:)
integer, intent(out) :: n_constrained
logical, intent(inout) :: all_tets(:)
logical, intent(inout) :: mixed(:)
Calls
Called by
Contents
None
Call graph
mobile_verts calls psb_cd_get_local_rows, loc_to_glob_, free_conn, mobile_verts
free_conn calls free_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort
smooth_mesh calls mobile_verts, smooth_mesh