move_boundaries – Morfeus Framework
move_boundaries Module Procedure
12 statements
Source File
module procedure move_boundaries module subroutine move_boundaries(msh, bc, t1, t2) Interface →
Uses
class_mesh
class_vector
loop over all boundaries, moving the vertices and conceptual surfaces from the time interval t1 to t2
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(inout) :: msh
type(bc_poly), intent(in) :: bc(:)
real(kind=psb_dpk_) :: t1
real(kind=psb_dpk_) :: t2
Calls
Called by
Contents
None
Call graph
move_boundaries calls move_boundary, move_boundaries
move_boundary calls move_boundary, abort_psblas
abort_psblas calls abort_psblas, psb_abort