mypnum_ – Morfeus Framework
mypnum_ Module Procedure
3 statements
Source File
module procedure mypnum_ module function mypnum_() Interface →
Arguments
None
Return Value integer
Called by
Contents
None
Call graph
mypnum_ calls mypnum_
free_mesh calls mypnum_, free_mesh
cmp_moving_surf calls mypnum_, cmp_moving_surf
create_output calls mypnum_, create_output
vector_pde_grad calls mypnum_, vector_pde_grad
psb_build_prec calls mypnum_
rd_inp_motion_law calls mypnum_, bcast_vector, rd_inp_motion_law
set_least_squares calls mypnum_, set_least_squares
create_scalar_source calls mypnum_, create_scalar_source
bcast_vertex calls mypnum_, bcast_vector, bcast_vertex
import_mesh calls mypnum_
vector_pde_source calls mypnum_
create_bc calls mypnum_, create_bc
vector_pde_ddt calls mypnum_, vector_pde_ddt
bcast_vector calls mypnum_, bcast_vector
check_mesh_quality calls mypnum_, check_tet_quality, get_cells_type, check_mesh_quality
bcast_face calls mypnum_, bcast_face
wr_mtx_vector calls mypnum_, wr_mtx_vector
read_par_i calls mypnum_
wr_mtx_matrix calls mypnum_, wr_mtx_matrix
debug_material calls mypnum_, debug_material
asb_pde_ calls mypnum_, asb_pde_
l2g_cell calls mypnum_, l2g_cell
bcast_dim calls mypnum_, bcast_dim
build_pde_prec calls mypnum_, build_pde_prec
write_scalar_field calls mypnum_, write_scalar_field
scalar_pde_laplacian calls mypnum_, scalar_pde_laplacian
bcast_conn calls mypnum_, bcast_conn
wr_mtx_pattern calls mypnum_, wr_mtx_pattern
supplement_v2f calls mypnum_, bcast_conn, supplement_v2f
cmp_mesh_f2b calls mypnum_, cmp_mesh_f2b
rd_inp_bc_math calls mypnum_, rd_inp_bc_math
smooth_surf_vtx calls mypnum_, smooth_surf_vtx
write_vector_field calls mypnum_, l2g_vector, l2g_cell, write_vector_field
rd_inp_material calls mypnum_, rd_inp_material
cmp_mesh_v2ve calls mypnum_, cmp_mesh_v2e, cmp_mesh_v2ve
write_vector_pde calls mypnum_, wr_mtx_vector, write_vector_pde
vector_pde_div calls mypnum_, vector_pde_div
l2g_vector calls mypnum_, l2g_vector
read_par_v calls mypnum_
supplement_v2c calls mypnum_, supplement_v2c
read_par_d calls mypnum_
psb_solve_sys calls mypnum_, psb_solve_sys
cmp_mesh_desc calls mypnum_, bcast_conn, cmp_mesh_desc
geom_diff calls mypnum_, geom_diff
rd_inp_mesh calls mypnum_, rd_inp_mesh
scalar_pde_ddt calls mypnum_, scalar_pde_ddt
scalar_pde_div calls mypnum_, scalar_pde_div
smooth_mesh calls mypnum_, set_least_squares, geom_diff, laplacian_smooth, smooth_mesh
check_tet_quality calls mypnum_, check_tet_quality
write_vtk_mesh calls mypnum_
check_mesh_unused_el calls mypnum_, check_mesh_unused_el
flux_pde_div calls mypnum_, flux_pde_div
write_mesh calls mypnum_, l2g_face, l2g_cell, l2g_vertex, l2g_conn, write_mesh
cmp_mesh_renum calls mypnum_, start_renum, cmp_mesh_renum
cmp_mesh_c2c calls mypnum_, cmp_mesh_c2c
create_pde calls mypnum_, create_pde
cmp_mesh_v2v calls mypnum_, cmp_mesh_v2v
nemo_mesh_size calls mypnum_
cmp_mesh_v2b calls mypnum_, cmp_mesh_v2b
rd_inp_bc calls mypnum_, rd_inp_bc
read_par_h calls mypnum_
l2g_face calls mypnum_, l2g_face
start_renum calls mypnum_, build_pinv, start_renum
l2g_vertex calls mypnum_, l2g_vector, l2g_vertex
scalar_pde_source calls mypnum_, scalar_pde_source
l2g_conn calls mypnum_, l2g_conn
cmp_mesh_v2e calls mypnum_, cmp_mesh_v2e
write_exo_morfeus calls mypnum_, l2g_face, l2g_vector, l2g_cell, l2g_vertex, l2g_conn, write_exo_morfeus
build_pinv calls mypnum_, build_pinv
read_par_discretization calls mypnum_
smooth_interior_vtx calls mypnum_, smooth_interior_vtx
vector_pde_d2dt2 calls mypnum_, vector_pde_d2dt2
g2l_mesh calls mypnum_, bcast_vertex, bcast_conn, bcast_cell
bld_part_random calls mypnum_, bld_part_random
cmp_mesh_f2f calls mypnum_, cmp_mesh_f2f
rd_inp_bc_wall calls mypnum_
write_scalar_pde calls mypnum_, wr_mtx_vector, write_scalar_pde
bld_part_block calls mypnum_, bld_part_block
scalar_pde_d2dt2 calls mypnum_, scalar_pde_d2dt2
cmp_mesh_part calls mypnum_, bld_part_random, bld_part_block, cmp_mesh_part
alloc_surface calls mypnum_, alloc_plane, alloc_surface
bcast_cell calls mypnum_, bcast_cell
create_mesh calls mypnum_, import_mesh, g2l_mesh, set_least_squares, cmp_mesh_f2b, wr_mtx_pattern, cmp_mesh_v2b, supplement_v2c, cmp_mesh_f2f, rd_inp_mesh, cmp_mesh_part, cmp_mesh_renum, cmp_mesh_v2ve, cmp_moving_surf, supplement_v2f, cmp_mesh_c2c, geom_diff, cmp_mesh_desc, bcast_face, create_mesh
vector_pde_laplacian calls mypnum_, vector_pde_laplacian
read_par_l calls mypnum_
free_keytable calls mypnum_, free_keytable
get_cells_type calls mypnum_, get_cells_type
get_vector_field calls mypnum_, l2g_vector, l2g_cell, get_vector_field
write_vtk_morfeus calls write_vtk_mesh, write_vtk_morfeus
create_bc_wall calls rd_inp_bc_wall, create_bc_wall
pde_div calls flux_pde_div, vector_pde_div, scalar_pde_div
solve_sys calls psb_solve_sys
scalar_pde_ddt_fld_phi calls scalar_pde_ddt, scalar_pde_ddt_fld_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
scalar_pde_d2dt2_fld_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_fld_phi
write_field calls write_scalar_field, write_vector_field
vector_pde_ddt_phi calls vector_pde_ddt, vector_pde_ddt_phi
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
scalar_pde_d2dt2_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_phi
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
scalar_pde_ddt_phi calls scalar_pde_ddt, scalar_pde_ddt_phi
pde_source calls scalar_pde_source
create_motion calls rd_inp_motion_law, create_motion
get_scalar_field calls l2g_cell, get_scalar_field
create_material calls rd_inp_material, create_material
vector_pde_d2dt2_fld_phi calls vector_pde_d2dt2, vector_pde_d2dt2_fld_phi
write_pde calls wr_mtx_matrix, write_pde
vector_pde_d2dt2_phi calls vector_pde_d2dt2, vector_pde_d2dt2_phi
vector_pde_ddt_fld_phi calls vector_pde_ddt, vector_pde_ddt_fld_phi
create_bc_math calls rd_inp_bc_math, create_bc_math
pde_grad calls vector_pde_grad
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
alloc_plane calls solve_sys, alloc_plane
solve_least_squares calls solve_sys, solve_least_squares
laplacian_smooth calls solve_sys, laplacian_smooth
solve_pde_sys calls solve_sys, solve_pde_sys
pde_ddt calls vector_pde_ddt_phi, scalar_pde_ddt_fld_phi, scalar_pde_ddt_phi, vector_pde_ddt_fld_phi
pde_d2dt2 calls scalar_pde_d2dt2_fld_phi, vector_pde_d2dt2_fld_phi, vector_pde_d2dt2_phi, scalar_pde_d2dt2_phi
pde_laplacian calls scalar_pde_laplacian_gamma_phi, vector_pde_laplacian_phi, vector_pde_laplacian_gamma_phi, scalar_pde_laplacian_phi