nemo_scalar_field_normi – Morfeus Framework
nemo_scalar_field_normi Module Procedure
12 statements
Source File
module procedure nemo_scalar_field_normi module function nemo_scalar_field_normi(fld) result(norm) Interface →
Uses
class_mesh
tools_psblas
$ msh => msh_(fld%field)
Arguments
Type Intent Optional Attributes Name
class(scalar_field), intent(in) :: fld
Return Value real(kind=psb_dpk_)
Calls
Called by
Contents
None
Call graph
nemo_scalar_field_normi calls psb_erractionsave, psb_geamax, psb_erractionrestore, nemo_scalar_field_normi