nemo_mesh_size – Morfeus Framework
nemo_mesh_size Subroutine
29 statements
Source File
subroutine nemo_mesh_size(msh)
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(in) :: msh
Calls
Contents
Source Code
nemo_mesh_size
Source Code
    SUBROUTINE nemo_mesh_size(msh)
        IMPLICIT NONE
        TYPE(mesh), INTENT(IN) :: msh
        INTEGER(kind=nemo_int_long_)   ::isz
        REAL:: sz,sz1
        INTEGER :: icontxt, mypnum, nprocs,ip
        icontxt=icontxt_()
        mypnum = mypnum_()
        nprocs = nprocs_()
        isz = msh%nemo_sizeof()
        sz=isz
        IF(mypnum == 0) THEN
            WRITE(*,'()')
            WRITE(*,*) 'On process',mypnum, 'mesh size',sz
        END IF
        DO ip = 1, nprocs - 1
            IF(mypnum == ip) THEN
                CALL psb_snd(icontxt,sz,0)
            ELSEIF(mypnum == 0) THEN
                CALL psb_rcv(icontxt,sz1,ip)
                WRITE(*,*) 'On process',ip, 'mesh size', sz1
            END IF
        END DO
        CALL psb_sum(icontxt,isz)
        IF (mypnum==0) THEN
            WRITE(*,*) 'Total size of mesh   :',isz
            WRITE(*,*)
        ENDIF
    END SUBROUTINE nemo_mesh_size
Call graph
nemo_mesh_size calls psb_sum, nprocs_, psb_rcv, icontxt_, mypnum_, psb_snd
nprocs_ calls nprocs_
icontxt_ calls icontxt_
mypnum_ calls mypnum_