nemo_scalar_field_norm1 – Morfeus Framework
nemo_scalar_field_norm1 Module Procedure
12 statements
Source File
module procedure nemo_scalar_field_norm1 module function nemo_scalar_field_norm1(fld) result(norm) Interface →
Uses
class_mesh
tools_psblas
$ msh => msh_(fld%field)
Arguments
Type Intent Optional Attributes Name
class(scalar_field), intent(in) :: fld
Return Value real(kind=psb_dpk_)
Calls
Called by
Contents
None
Call graph
nemo_scalar_field_norm1 calls psb_erractionrestore, psb_erractionsave, psb_geasum, nemo_scalar_field_norm1