nprocs_ – Morfeus Framework
nprocs_ Module Procedure
3 statements
Source File
module procedure nprocs_ module function nprocs_() Interface →
Arguments
None
Return Value integer
Called by
Contents
None
Call graph
nprocs_ calls nprocs_
supplement_v2c calls nprocs_, supplement_v2c
bld_part_graph calls nprocs_, bld_part_graph
supplement_v2f calls nprocs_, supplement_v2f
wr_mtx_matrix calls nprocs_, wr_mtx_matrix
cmp_mesh_part calls nprocs_, bld_part_graph, cmp_mesh_part
create_mesh calls nprocs_, cmp_mesh_part, supplement_v2f, supplement_v2c, create_mesh
nemo_mesh_size calls nprocs_
write_pde calls wr_mtx_matrix, write_pde