open_file – Morfeus Framework
open_file Module Procedure
29 statements
Source File
module procedure open_file module subroutine open_file(input_file, nemo_json) Interface →
Uses
class_psblas
json_module
Opens a file
Undefined Good Something went wrong
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_file
type(json_file), intent(out) :: nemo_json
Calls
Called by
Contents
None
Call graph
open_file calls abort_psblas, open_file
abort_psblas calls abort_psblas, psb_abort
read_par_h calls open_file
create_iterating calls open_file, create_iterating
create_pde calls open_file, create_pde
rd_inp_bc_math calls open_file, rd_inp_bc_math
create_scalar_source calls open_file, create_scalar_source
read_par_d calls open_file
rd_inp_motion_law calls open_file, rd_inp_motion_law
read_par_i calls open_file
rd_inp_bc_wall calls open_file
rd_inp_bc calls open_file, rd_inp_bc
read_par_l calls open_file
read_par_discretization calls open_file
create_output calls open_file, create_output
rd_inp_mesh calls open_file, rd_inp_mesh
rd_inp_material calls open_file, rd_inp_material
read_par_v calls open_file
create_bc_wall calls rd_inp_bc_wall, create_bc_wall
create_material calls rd_inp_material, create_material
create_bc_math calls rd_inp_bc_math, create_bc_math
create_motion calls rd_inp_motion_law, create_motion
create_mesh calls rd_inp_mesh, create_mesh