overflow – Morfeus Framework
overflow Function
5 statements
Source File
pure function overflow(image, remainder) result(filler)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: image
integer, intent(in) :: remainder
Return Value integer
Called by
Contents
None
Call graph
first_block calls overflow
last_block calls overflow, first_block
partition calls first_block, last_block, partition