psb_get_glob_to_loc – Morfeus Framework
psb_get_glob_to_loc Module Procedure
17 statements
Source File
module procedure psb_get_glob_to_loc module subroutine psb_get_glob_to_loc(desc, iglob_to_loc) Interface →
Arguments
Type Intent Optional Attributes Name
type(psb_desc_type), intent(in) :: desc
integer, allocatable :: iglob_to_loc(:)
Calls
Called by
Contents
None
Call graph
psb_get_glob_to_loc calls psb_erractionsave, psb_realloc, psb_glob_to_loc, psb_abort, psb_cd_get_context, psb_cd_get_global_rows, psb_check_error, psb_erractionrestore, psb_get_glob_to_loc
psb_check_error calls psb_check_error, psb_error, psb_errpush