psb_check_error – Morfeus Framework
psb_check_error Module Procedure
7 statements
Source File
module procedure psb_check_error module subroutine psb_check_error(info, where, from, icontxt) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: info
character(len=*), intent(in) :: where
character(len=*), intent(in) :: from
integer, intent(in) :: icontxt
Calls
Called by
Contents
None
Call graph
psb_check_error calls psb_errpush, psb_error, psb_check_error
psb_get_glob_to_loc calls psb_check_error, psb_get_glob_to_loc
glob_to_loc_ calls psb_check_error, glob_to_loc_
psb_get_loc_to_glob calls psb_check_error, psb_get_loc_to_glob
loc_to_glob_ calls psb_check_error, loc_to_glob_