psb_solve_sys – Morfeus Framework
psb_solve_sys Module Procedure
43 statements
Source File
module procedure psb_solve_sys module subroutine psb_solve_sys(a, prec, b, x, desc, cmethod, eps, itmax, iter, err) Interface →
Uses
class_psblas
psb_base_mod
psb_prec_mod
psb_krylov_mod
Arguments
Type Intent Optional Attributes Name
type(psb_dspmat_type), intent(in) :: a
type(psb_dprec_type), intent(inout) :: prec
real(kind=psb_dpk_), intent(in) :: b(:)
real(kind=psb_dpk_), intent(inout) :: x(:)
type(psb_desc_type), intent(in) :: desc
character(len=*), intent(in) :: cmethod
real(kind=psb_dpk_), intent(in) :: eps
integer, intent(in) :: itmax
integer, intent(out) :: iter
real(kind=psb_dpk_), intent(out) :: err
Calls
Called by
Contents
None
Call graph
psb_solve_sys calls psb_krylov, psb_erractionsave, icontxt_, psb_check_error, mypnum_, psb_erractionrestore, psb_solve_sys
icontxt_ calls icontxt_
mypnum_ calls mypnum_
solve_sys calls psb_solve_sys
solve_least_squares calls solve_sys, solve_least_squares
laplacian_smooth calls solve_sys, laplacian_smooth
solve_pde_sys calls solve_sys, solve_pde_sys
alloc_plane calls solve_sys, alloc_plane
smooth_mesh calls laplacian_smooth, smooth_mesh
alloc_surface calls alloc_plane, alloc_surface