psb_get_loc_to_glob – Morfeus Framework
psb_get_loc_to_glob Module Procedure
17 statements
Source File
module procedure psb_get_loc_to_glob module subroutine psb_get_loc_to_glob(desc, iloc_to_glob) Interface →
Arguments
Type Intent Optional Attributes Name
type(psb_desc_type), intent(in) :: desc
integer, allocatable :: iloc_to_glob(:)
Calls
Called by
Contents
None
Call graph
psb_get_loc_to_glob calls psb_erractionsave, psb_realloc, psb_cd_get_local_cols, psb_abort, psb_cd_get_context, psb_loc_to_glob, psb_check_error, psb_erractionrestore, psb_get_loc_to_glob
psb_check_error calls psb_check_error, psb_error, psb_errpush