pwl_deriv_x_v – Morfeus Framework
pwl_deriv_x_v Module Procedure
13 statements
Source File
module procedure pwl_deriv_x_v module subroutine pwl_deriv_x_v(dydx, x, y_data, x_data) Interface →
Uses
class_psblas
tools_math
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(out) :: dydx(:)
real(kind=psb_dpk_), intent(in) :: x
real(kind=psb_dpk_), intent(in) :: y_data(:,:)
real(kind=psb_dpk_), intent(in) :: x_data(:)
Calls
Called by
Contents
None
Call graph
pwl_deriv_x_v calls pwl_nearest, abort_psblas, pwl_deriv_x_v
pwl_nearest calls pwl_nearest, abort_psblas
abort_psblas calls abort_psblas, psb_abort
pwl_deriv calls pwl_deriv_x_v
get_motion_velocity calls pwl_deriv, get_motion_velocity