pwl_deriv_x_s – Morfeus Framework
pwl_deriv_x_s Module Procedure
13 statements
Source File
module procedure pwl_deriv_x_s module subroutine pwl_deriv_x_s(dydx, x, y_data, x_data) Interface →
Uses
class_psblas
tools_math
$Id: pwl_deriv_x.f90 3093 2008-04-22 14:51:09Z sfilippo $
Description: Compute the first derivative of a piecewise linear x-y data series. Type REAL, rank = 0
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(out) :: dydx
real(kind=psb_dpk_), intent(in) :: x
real(kind=psb_dpk_), intent(in) :: y_data(:)
real(kind=psb_dpk_), intent(in) :: x_data(:)
Calls
Called by
Contents
None
Call graph
pwl_deriv_x_s calls pwl_nearest, abort_psblas, pwl_deriv_x_s
pwl_nearest calls pwl_nearest, abort_psblas
abort_psblas calls abort_psblas, psb_abort
pwl_deriv calls pwl_deriv_x_s
get_motion_velocity calls pwl_deriv, get_motion_velocity