pwl_nearest – Morfeus Framework
pwl_nearest Module Procedure
24 statements
Source File
module procedure pwl_nearest module subroutine pwl_nearest(x, x_data, i1, i2) Interface →
Uses
class_psblas
$Id: pwl_nearest.f90 3093 2008-04-22 14:51:09Z sfilippo $
Description: Given an array X_DATA and a scalar X returns the subscripts of the two nearest elements in the data series.
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(in) :: x
real(kind=psb_dpk_), intent(in) :: x_data(:)
integer, intent(out) :: i1
integer, intent(out) :: i2
Calls
Called by
Contents
None
Call graph
pwl_nearest calls abort_psblas, pwl_nearest
abort_psblas calls abort_psblas, psb_abort
pwl_deriv_x_s calls pwl_nearest, pwl_deriv_x_s
pwl_interp_x_vec calls pwl_nearest, pwl_interp_x_vec
pwl_deriv_x_vec calls pwl_nearest, pwl_deriv_x_vec
pwl_deriv_x_v calls pwl_nearest, pwl_deriv_x_v
get_motion_displacement calls pwl_nearest, pwl_interp, get_motion_displacement
pwl_interp_x_s calls pwl_nearest, pwl_interp_x_s
pwl_interp_x_v calls pwl_nearest, pwl_interp_x_v
pwl_interp calls pwl_interp_x_vec, pwl_interp_x_v, pwl_interp_x_s
pwl_deriv calls pwl_deriv_x_s, pwl_deriv_x_v, pwl_deriv_x_vec
get_motion_velocity calls pwl_interp, pwl_deriv, get_motion_velocity