pwl_deriv_x_vec – Morfeus Framework
pwl_deriv_x_vec Module Procedure
16 statements
Source File
module procedure pwl_deriv_x_vec module subroutine pwl_deriv_x_vec(dydx, x, y_data, x_data) Interface →
Uses
class_psblas
tools_math
class_vector
Arguments
Type Intent Optional Attributes Name
type(vector), intent(out) :: dydx
real(kind=psb_dpk_), intent(in) :: x
type(vector), intent(in) :: y_data(:)
real(kind=psb_dpk_), intent(in) :: x_data(:)
Calls
Called by
Contents
None
Call graph
pwl_deriv_x_vec calls pwl_nearest, abort_psblas, pwl_deriv_x_vec
pwl_nearest calls pwl_nearest, abort_psblas
abort_psblas calls abort_psblas, psb_abort
pwl_deriv calls pwl_deriv_x_vec
get_motion_velocity calls pwl_deriv, get_motion_velocity