pwl_interp_x_s – Morfeus Framework
pwl_interp_x_s Module Procedure
21 statements
Source File
module procedure pwl_interp_x_s module subroutine pwl_interp_x_s(y, x, y_data, x_data) Interface →
Uses
class_psblas
tools_math
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(out) :: y
real(kind=psb_dpk_), intent(in) :: x
real(kind=psb_dpk_), intent(in) :: y_data(:)
real(kind=psb_dpk_), intent(in) :: x_data(:)
Calls
Called by
Contents
None
Call graph
pwl_interp_x_s calls pwl_nearest, abort_psblas, pwl_interp_x_s
pwl_nearest calls pwl_nearest, abort_psblas
abort_psblas calls abort_psblas, psb_abort
pwl_interp calls pwl_interp_x_s
get_motion_velocity calls pwl_interp, get_motion_velocity
get_motion_displacement calls pwl_interp, get_motion_displacement