pwl_interp_x_vec – Morfeus Framework
pwl_interp_x_vec Module Procedure
23 statements
Source File
module procedure pwl_interp_x_vec module subroutine pwl_interp_x_vec(y, x, y_data, x_data) Interface →
Uses
class_psblas
class_vector
tools_math
Arguments
Type Intent Optional Attributes Name
type(vector), intent(out) :: y
real(kind=psb_dpk_), intent(in) :: x
type(vector), intent(in) :: y_data(:)
real(kind=psb_dpk_), intent(in) :: x_data(:)
Calls
Called by
Contents
None
Call graph
pwl_interp_x_vec calls pwl_nearest, abort_psblas, pwl_interp_x_vec
pwl_nearest calls pwl_nearest, abort_psblas
abort_psblas calls abort_psblas, psb_abort
pwl_interp calls pwl_interp_x_vec
get_motion_displacement calls pwl_interp, get_motion_displacement
get_motion_velocity calls pwl_interp, get_motion_velocity