rd_cgns_mesh – Morfeus Framework
rd_cgns_mesh Module Procedure
840 statements
Source File
module procedure rd_cgns_mesh module subroutine rd_cgns_mesh(mesh_file, mesh_id, nbc, ncd, verts, faces, cells, v2f, v2c, f2c, c2g) Interface →
Uses
cgns
class_psblas
class_cell
class_connectivity
class_face
class_vertex
tools_math
type_table
Note
Compatible only with CGNS v3.3.0 and above. Earlier versions are not supported. Note: CGNS functionality is not working for Morfeus. Currently set to pre-process entire module procedure so that the implementation exists but is empty. IP - 6/6/2019
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mesh_file
character(len=*), intent(out) :: mesh_id
integer, intent(out) :: nbc
integer, intent(out) :: ncd
type(vertex), intent(out), allocatable :: verts(:)
type(face), intent(out), allocatable :: faces(:)
type(cell), intent(out), allocatable :: cells(:)
type(connectivity), intent(out) :: v2f
type(connectivity), intent(out) :: v2c
type(connectivity), intent(out) :: f2c
type(connectivity), intent(out) :: c2g
Calls
Called by
Contents
None
Call graph
rd_cgns_mesh calls cg_coord_read_f, cg_nbocos_f, abort_psblas, cg_nzones_f, cg_nbases_f, cell_, cg_close_f, 8, cg_coord_info_f, cg_base_read_f, get_dual_table, alloc_vertex, alloc_cell, vertex_, cg_zone_read_f, alloc_face, cg_nsections_f, cg_section_read_f, 6, face_, 3, rd_cgns_mesh
abort_psblas calls abort_psblas, psb_abort
cell_ calls cell_
alloc_vertex calls alloc_vertex, abort_psblas, vector_
alloc_cell calls alloc_cell, abort_psblas
alloc_face calls alloc_face, abort_psblas
face_ calls face_
vector_ calls vector_