rd_exodus_mesh – Morfeus Framework
rd_exodus_mesh Module Procedure
592 statements
Source File
module procedure rd_exodus_mesh module subroutine rd_exodus_mesh(mesh_file, mesh_id, nbc, ncd, verts, faces, cells, v2f, v2c, f2c, c2g) Interface →
Uses
iso_fortran_env
class_psblas
class_cell
class_connectivity
class_face
class_vertex
tools_math
type_table
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mesh_file
character(len=*), intent(out) :: mesh_id
integer, intent(out) :: nbc
integer, intent(out) :: ncd
type(vertex), allocatable :: verts(:)
type(face), allocatable :: faces(:)
type(cell), allocatable :: cells(:)
type(connectivity), intent(out) :: v2f
type(connectivity), intent(out) :: v2c
type(connectivity), intent(out) :: f2c
type(connectivity), intent(out) :: c2g
Calls
Called by
Contents
None
Call graph
rd_exodus_mesh calls exgmap, alloc_face, cell_, face_, 6, exclos, abort_psblas, exgcor, exgebi, alloc_cell, exgssi, exopen, vertex_, exgini, exgcon, 3, 8, alloc_vertex, rd_exodus_mesh
alloc_face calls alloc_face, abort_psblas
cell_ calls cell_
face_ calls face_
abort_psblas calls abort_psblas, psb_abort
alloc_cell calls alloc_cell, abort_psblas
alloc_vertex calls alloc_vertex, abort_psblas, vector_
vector_ calls vector_