rd_gambit_mesh – Morfeus Framework
rd_gambit_mesh Module Procedure
633 statements
Source File
module procedure rd_gambit_mesh module subroutine rd_gambit_mesh(mesh_file, mesh_id, nbc, ncd, verts, faces, cells, v2f, v2c, f2c, c2g) Interface →
Uses
class_psblas
class_cell
class_face
class_vertex
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mesh_file
character(len=*), intent(out) :: mesh_id
integer, intent(out) :: nbc
integer, intent(out) :: ncd
type(vertex), allocatable :: verts(:)
type(face), allocatable :: faces(:)
type(cell), allocatable :: cells(:)
type(connectivity), intent(out) :: v2f
type(connectivity), intent(out) :: v2c
type(connectivity), intent(out) :: f2c
type(connectivity), intent(out) :: c2g
Calls
Called by
Contents
None
Call graph
rd_gambit_mesh calls abort_psblas, alloc_face, alloc_cell, alloc_vertex, 8, face_, 3, 6, vertex_, cell_, rd_gambit_mesh
abort_psblas calls abort_psblas, psb_abort
alloc_face calls alloc_face, abort_psblas
alloc_cell calls alloc_cell, abort_psblas
alloc_vertex calls alloc_vertex, abort_psblas, vector_
face_ calls face_
cell_ calls cell_
vector_ calls vector_
import_mesh calls rd_gambit_mesh
create_mesh calls import_mesh, create_mesh