rd_gmsh_mesh – Morfeus Framework
rd_gmsh_mesh Module Procedure
668 statements
Source File
module procedure rd_gmsh_mesh module subroutine rd_gmsh_mesh(mesh_file, mesh_id, nbc, ncd, verts, faces, cells, v2f, v2c, f2c, c2g) Interface →
Uses
class_psblas
class_cell
class_face
class_vertex
$MeshFormat statement
Version, filetype (0=ASCII,1=binary), datasize
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mesh_file
character(len=*), intent(out) :: mesh_id
integer, intent(out) :: nbc
integer, intent(out) :: ncd
type(vertex), allocatable :: verts(:)
type(face), allocatable :: faces(:)
type(cell), allocatable :: cells(:)
type(connectivity), intent(out) :: v2f
type(connectivity), intent(out) :: v2c
type(connectivity), intent(out) :: f2c
type(connectivity), intent(out) :: c2g
Calls
Called by
Contents
None
Call graph
rd_gmsh_mesh calls alloc_face, 6, alloc_vertex, alloc_cell, vertex_, abort_psblas, cell_, face_, 8, rd_gmsh_mesh
alloc_face calls alloc_face, abort_psblas
alloc_vertex calls alloc_vertex, abort_psblas, vector_
alloc_cell calls alloc_cell, abort_psblas
abort_psblas calls abort_psblas, psb_abort
cell_ calls cell_
face_ calls face_
vector_ calls vector_
import_mesh calls rd_gmsh_mesh
create_mesh calls import_mesh, create_mesh