rd_inp_mesh – Morfeus Framework
rd_inp_mesh Module Procedure
64 statements
Source File
module procedure rd_inp_mesh module subroutine rd_inp_mesh(input_file, sec, mesh_file, scale, irenum, ipart, nswpref, mtx_pat) Interface →
Uses
class_psblas
json_module
tools_input
$Id: rd_inp_mesh.f90 3093 2008-04-22 14:51:09Z sfilippo $
Description: To be added...
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
character(len=nlen), intent(inout) :: mesh_file
real(kind=psb_dpk_), intent(inout) :: scale
integer, intent(inout) :: irenum
integer, intent(inout) :: ipart
integer, intent(inout) :: nswpref
logical, intent(inout) :: mtx_pat
Calls
Called by
Contents
None
Call graph
rd_inp_mesh calls mypnum_, open_file, psb_bcast, icontxt_, rd_inp_mesh
mypnum_ calls mypnum_
open_file calls open_file, abort_psblas
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort
create_mesh calls rd_inp_mesh, create_mesh