rd_inp_bc_math – Morfeus Framework
rd_inp_bc_math Module Procedure
101 statements
Source File
module procedure rd_inp_bc_math module subroutine rd_inp_bc_math(input_file, sec, nbf, id, a, b, c) Interface →
Uses
class_psblas
json_module
tools_bc
tools_input
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
integer, intent(in) :: nbf
integer, intent(out) :: id
real(kind=psb_dpk_), intent(out), allocatable :: a(:)
real(kind=psb_dpk_), intent(out), allocatable :: b(:)
real(kind=psb_dpk_), intent(out), allocatable :: c(:)
Calls
Called by
Contents
None
Call graph
rd_inp_bc_math calls mypnum_, open_file, abort_psblas, find_section, icontxt_, psb_bcast, rd_inp_bc_math
mypnum_ calls mypnum_
open_file calls open_file, abort_psblas
abort_psblas calls abort_psblas, psb_abort
find_section calls find_section, abort_psblas
icontxt_ calls icontxt_
create_bc_math calls rd_inp_bc_math, create_bc_math