rd_inp_material – Morfeus Framework
rd_inp_material Module Procedure
74 statements
Source File
module procedure rd_inp_material module subroutine rd_inp_material(input_file, bid, name, ilaw, type, id) Interface →
Uses
class_psblas
json_module
tools_input
tools_material
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_file
integer, intent(in) :: bid
character(len=*), intent(out) :: name
integer, intent(out) :: ilaw(:)
character(len=*), intent(out) :: type
integer, intent(out) :: id
Calls
Called by
Contents
None
Call graph
rd_inp_material calls 4, mypnum_, open_file, icontxt_, psb_bcast, rd_inp_material
mypnum_ calls mypnum_
open_file calls open_file, abort_psblas
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort
create_material calls rd_inp_material, create_material