rd_inp_bc – Morfeus Framework
rd_inp_bc Module Procedure
65 statements
Source File
module procedure rd_inp_bc module subroutine rd_inp_bc(input_file, sec, nbc_msh, id, mot) Interface →
Uses
class_psblas
json_module
tools_bc
tools_input
tools_mesh_move
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
integer, intent(in) :: nbc_msh
integer, intent(inout) :: id(nbc_msh)
type(motion), intent(inout) :: mot(nbc_msh)
Calls
Called by
Contents
None
Call graph
rd_inp_bc calls abort_psblas, psb_bcast, open_file, icontxt_, mypnum_, rd_inp_bc
abort_psblas calls abort_psblas, psb_abort
open_file calls open_file, abort_psblas
icontxt_ calls icontxt_
mypnum_ calls mypnum_