rd_inp_motion_law – Morfeus Framework
rd_inp_motion_law Module Procedure
41 statements
Source File
module procedure rd_inp_motion_law module subroutine rd_inp_motion_law(ml_file, iml, law_x, law_y) Interface →
Uses
class_psblas
json_module
class_vector
tools_input
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: ml_file
integer, intent(out) :: iml
real(kind=psb_dpk_), allocatable :: law_x(:)
type(vector), allocatable :: law_y(:)
Calls
Called by
Contents
None
Call graph
rd_inp_motion_law calls open_file, vector_, alloc_vector, abort_psblas, icontxt_, psb_bcast, mypnum_, bcast_vector, rd_inp_motion_law
open_file calls open_file, abort_psblas
vector_ calls vector_
alloc_vector calls alloc_vector, abort_psblas
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
mypnum_ calls mypnum_
bcast_vector calls bcast_vector, alloc_vector, abort_psblas, icontxt_, psb_bcast, mypnum_, free_vector
free_vector calls free_vector, abort_psblas
create_motion calls rd_inp_motion_law, create_motion