read_par_i – Morfeus Framework
read_par_i Procedure
18 statements
Source File
module procedure read_par_i module procedure read_par_i()
Uses
class_psblas
tools_input
Arguments
None
Calls
Contents
None
Call graph
read_par_i calls open_file, get_par, find_section, icontxt_, psb_bcast, mypnum_
open_file calls open_file, abort_psblas
find_section calls find_section, abort_psblas
icontxt_ calls icontxt_
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort