read_par_discretization – Morfeus Framework
read_par_discretization Procedure
46 statements
Source File
module procedure read_par_discretization module procedure read_par_discretization()
Uses
class_psblas
json_module
tools_input
$ case(id_tvd_) ! Any scheme requiring a blending factor too $ read(inp,*) r%blend
Arguments
None
Calls
Contents
None
Call graph
read_par_discretization calls icontxt_, psb_bcast, mypnum_, find_section, abort_psblas, open_file
icontxt_ calls icontxt_
mypnum_ calls mypnum_
find_section calls find_section, abort_psblas
abort_psblas calls abort_psblas, psb_abort
open_file calls open_file, abort_psblas