read_par_h – Morfeus Framework
read_par_h Procedure
18 statements
Source File
module procedure read_par_h module procedure read_par_h()
Uses
class_psblas
tools_input
Arguments
None
Calls
Contents
None
Call graph
read_par_h calls icontxt_, psb_bcast, mypnum_, find_section, open_file, get_par
icontxt_ calls icontxt_
mypnum_ calls mypnum_
find_section calls find_section, abort_psblas
open_file calls open_file, abort_psblas
abort_psblas calls abort_psblas, psb_abort