read_par_d – Morfeus Framework
read_par_d Procedure
23 statements
Source File
module procedure read_par_d module procedure read_par_d()
Uses
class_psblas
json_module
tools_input
Arguments
None
Calls
Contents
None
Call graph
read_par_d calls mypnum_, psb_bcast, open_file, icontxt_
mypnum_ calls mypnum_
open_file calls open_file, abort_psblas
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort