read_par_v – Morfeus Framework
read_par_v Procedure
24 statements
Source File
module procedure read_par_v module procedure read_par_v()
Uses
class_psblas
class_vector
tools_input
Arguments
None
Calls
Contents
None
Call graph
read_par_v calls get_par, find_section, vector_, psb_bcast, open_file, icontxt_, mypnum_
find_section calls find_section, abort_psblas
vector_ calls vector_
open_file calls open_file, abort_psblas
icontxt_ calls icontxt_
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort