rhie_chow – Morfeus Framework
rhie_chow Module Procedure
68 statements
Source File
module procedure rhie_chow module function rhie_chow(phi, fld) result(res) Interface →
Uses
class_psblas
class_connectivity
class_dimensions
class_field
class_scalar_field
class_vector_field
class_vector
class_mesh
class_face
class_vector
Arguments
Type Intent Optional Attributes Name
type(scalar_field), intent(in) :: phi
type(scalar_field), intent(in) :: fld
Return Value type(scalar_field)
Calls
Called by
Contents
None
Call graph
rhie_chow calls abort_psblas, rhie_chow
abort_psblas calls abort_psblas, psb_abort