scalar_pde_laplacian_gamma_phi – Morfeus Framework
scalar_pde_laplacian_gamma_phi Module Procedure
3 statements
Source File
module procedure scalar_pde_laplacian_gamma_phi module subroutine scalar_pde_laplacian_gamma_phi(sign, pde, gamma, phi, side) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: gamma
type(scalar_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
scalar_pde_laplacian calls scalar_pde_laplacian, psb_get_loc_to_glob, mypnum_, pde_sign, abort_psblas, free_vector, fld_grad, size_blk, check_mesh_consistency
mypnum_ calls mypnum_
pde_sign calls pde_sign, abort_psblas
abort_psblas calls abort_psblas, psb_abort
free_vector calls free_vector, abort_psblas
fld_grad calls scalar_field_grad, vector_field_grad
size_blk calls size_blk
check_mesh_consistency calls check_mesh_consistency, abort_psblas
scalar_field_grad calls scalar_field_grad, abort_psblas, psb_cd_get_local_rows, vector_, update_vector_halo
vector_field_grad calls vector_field_grad, abort_psblas, psb_cd_get_local_rows, vector_
vector_ calls vector_
update_vector_halo calls update_vector_halo, abort_psblas, icontxt_, psb_check_error, psb_halo, psb_cd_get_local_cols, psb_erractionsave, psb_erractionrestore
icontxt_ calls icontxt_
pde_laplacian calls scalar_pde_laplacian_gamma_phi