scalar_pde_laplacian – Morfeus Framework
scalar_pde_laplacian Module Procedure
297 statements
Source File
module procedure scalar_pde_laplacian module subroutine scalar_pde_laplacian(sign, pde, phi, gamma, side) Interface →
Uses
class_psblas
class_bc
class_dimensions
class_mesh
class_vector
op_grad
tools_bc
tools_operators
class_mesh
class_mesh
This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: phi
type(scalar_field), intent(in), optional :: gamma
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
scalar_pde_laplacian calls psb_get_loc_to_glob, free_vector, abort_psblas, pde_sign, mypnum_, fld_grad, size_blk, check_mesh_consistency, scalar_pde_laplacian
free_vector calls free_vector, abort_psblas
abort_psblas calls abort_psblas, psb_abort
pde_sign calls pde_sign, abort_psblas
mypnum_ calls mypnum_
fld_grad calls vector_field_grad, scalar_field_grad
size_blk calls size_blk
check_mesh_consistency calls check_mesh_consistency, abort_psblas
vector_field_grad calls vector_field_grad, abort_psblas, psb_cd_get_local_rows, vector_
scalar_field_grad calls scalar_field_grad, abort_psblas, psb_cd_get_local_rows, vector_, update_vector_halo
vector_ calls vector_
update_vector_halo calls update_vector_halo, abort_psblas, psb_erractionsave, icontxt_, psb_check_error, psb_halo, psb_cd_get_local_cols, psb_erractionrestore
icontxt_ calls icontxt_
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
pde_laplacian calls scalar_pde_laplacian_phi, scalar_pde_laplacian_gamma_phi