scalar_pde_laplacian_phi – Morfeus Framework
scalar_pde_laplacian_phi Module Procedure
3 statements
Source File
module procedure scalar_pde_laplacian_phi module subroutine scalar_pde_laplacian_phi(sign, pde, phi, side) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
scalar_pde_laplacian calls scalar_pde_laplacian, free_vector, mypnum_, abort_psblas, psb_get_loc_to_glob, fld_grad, check_mesh_consistency, pde_sign, size_blk
free_vector calls free_vector, abort_psblas
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
fld_grad calls scalar_field_grad, vector_field_grad
check_mesh_consistency calls check_mesh_consistency, abort_psblas
pde_sign calls pde_sign, abort_psblas
size_blk calls size_blk
scalar_field_grad calls scalar_field_grad, abort_psblas, vector_, psb_cd_get_local_rows, update_vector_halo
vector_field_grad calls vector_field_grad, abort_psblas, vector_, psb_cd_get_local_rows
vector_ calls vector_
update_vector_halo calls update_vector_halo, abort_psblas, psb_check_error, psb_erractionsave, psb_cd_get_local_cols, icontxt_, psb_erractionrestore, psb_halo
icontxt_ calls icontxt_
pde_laplacian calls scalar_pde_laplacian_phi