scalar_pde_d2dt2 – Morfeus Framework
scalar_pde_d2dt2 Module Procedure
117 statements
Source File
module procedure scalar_pde_d2dt2 module subroutine scalar_pde_d2dt2(sign, pde, phi, dt, fld, side) Interface →
Uses
class_psblas
class_dimensions
class_mesh
tools_operators
class_mesh
class_mesh
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in) :: dt
type(scalar_field), intent(in), optional :: fld
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
scalar_pde_d2dt2 calls abort_psblas, pde_sign, psb_cd_get_local_rows, check_mesh_consistency, size_blk, psb_get_loc_to_glob, mypnum_, scalar_pde_d2dt2
pde_sign calls pde_sign, abort_psblas
check_mesh_consistency calls check_mesh_consistency, abort_psblas
size_blk calls size_blk
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
scalar_pde_d2dt2_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_phi
scalar_pde_d2dt2_fld_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_fld_phi
pde_d2dt2 calls scalar_pde_d2dt2_phi, scalar_pde_d2dt2_fld_phi