scalar_pde_source – Morfeus Framework
scalar_pde_source Module Procedure
70 statements
Source File
module procedure scalar_pde_source module subroutine scalar_pde_source(sign, pde, phi, mats, src, side) Interface →
Uses
class_psblas
class_dimensions
class_mesh
tools_operators
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: phi
type(matptr), intent(in), target :: mats(:)
type(scalar_source), intent(in) :: src
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
scalar_pde_source calls psb_get_loc_to_glob, mypnum_, abort_psblas, pde_sign, psb_cd_get_local_rows, size_blk, scalar_pde_source
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
pde_sign calls pde_sign, abort_psblas
size_blk calls size_blk
pde_source calls scalar_pde_source