scalar_pde_div – Morfeus Framework
scalar_pde_div Module Procedure
235 statements
Source File
module procedure scalar_pde_div module subroutine scalar_pde_div(sign, pde, phi, flux, side, ds) Interface →
Uses
class_psblas
class_bc
class_discretization
class_dimensions
tools_bc
tools_operators
class_mesh
class_mesh
This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: phi
type(scalar_field), intent(inout) :: flux
real(kind=psb_dpk_), intent(in), optional :: side
type(discretization), intent(in), optional :: ds
Calls
Called by
Contents
None
Call graph
scalar_pde_div calls psb_get_loc_to_glob, abort_psblas, pde_sign, mypnum_, size_blk, check_mesh_consistency, scalar_pde_div
pde_sign calls pde_sign, abort_psblas
mypnum_ calls mypnum_
size_blk calls size_blk
check_mesh_consistency calls check_mesh_consistency, abort_psblas
abort_psblas calls abort_psblas, psb_abort
pde_div calls scalar_pde_div