scalar_pde_ddt_phi – Morfeus Framework
scalar_pde_ddt_phi Module Procedure
3 statements
Source File
module procedure scalar_pde_ddt_phi module subroutine scalar_pde_ddt_phi(sign, pde, phi, dt, side) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in) :: dt
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
scalar_pde_ddt_phi calls scalar_pde_ddt, scalar_pde_ddt_phi
scalar_pde_ddt calls scalar_pde_ddt, psb_get_loc_to_glob, mypnum_, abort_psblas, pde_sign, psb_cd_get_local_rows, size_blk, check_mesh_consistency
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
pde_sign calls pde_sign, abort_psblas
size_blk calls size_blk
check_mesh_consistency calls check_mesh_consistency, abort_psblas
pde_ddt calls scalar_pde_ddt_phi