scalar_pde_ddt – Morfeus Framework
scalar_pde_ddt Module Procedure
118 statements
Source File
module procedure scalar_pde_ddt module subroutine scalar_pde_ddt(sign, pde, phi, dt, fld, side) Interface →
Uses
class_psblas
class_dimensions
class_mesh
tools_operators
class_mesh
class_mesh
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in) :: dt
type(scalar_field), intent(in), optional :: fld
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
scalar_pde_ddt calls mypnum_, abort_psblas, psb_get_loc_to_glob, check_mesh_consistency, psb_cd_get_local_rows, pde_sign, size_blk, scalar_pde_ddt
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
check_mesh_consistency calls check_mesh_consistency, abort_psblas
pde_sign calls pde_sign, abort_psblas
size_blk calls size_blk
scalar_pde_ddt_phi calls scalar_pde_ddt, scalar_pde_ddt_phi
scalar_pde_ddt_fld_phi calls scalar_pde_ddt, scalar_pde_ddt_fld_phi
pde_ddt calls scalar_pde_ddt_fld_phi, scalar_pde_ddt_phi