scalar_field_mul – Morfeus Framework
scalar_field_mul Module Procedure
20 statements
Source File
module procedure scalar_field_mul module function scalar_field_mul(f1, f2) result(r) Interface →
Uses
class_dimensions
Arguments
Type Intent Optional Attributes Name
class(scalar_field), intent(in) :: f1
type(scalar_field), intent(in) :: f2
Return Value type(scalar_field)
Calls
Called by
Contents
None
Call graph
scalar_field_mul calls abort_psblas, scalar_field_mul
abort_psblas calls abort_psblas, psb_abort