scalar_field_grad – Morfeus Framework
scalar_field_grad Module Procedure
105 statements
Source File
module procedure scalar_field_grad module function scalar_field_grad(phi) result(grad) Interface →
Uses
class_psblas
class_connectivity
class_face
class_least_squares
class_mesh
class_scalar_field
class_vector
Arguments
Type Intent Optional Attributes Name
type(scalar_field), intent(in) :: phi
Return Value type(vector), allocatable,(:)
Calls
Called by
Contents
None
Call graph
scalar_field_grad calls psb_cd_get_local_rows, abort_psblas, vector_, update_vector_halo, scalar_field_grad
abort_psblas calls abort_psblas, psb_abort
vector_ calls vector_
update_vector_halo calls update_vector_halo, abort_psblas, psb_erractionsave, icontxt_, psb_halo, psb_cd_get_local_cols, psb_check_error, psb_erractionrestore
icontxt_ calls icontxt_
fld_grad calls scalar_field_grad
vector_pde_grad calls fld_grad, vector_pde_grad
scalar_pde_laplacian calls fld_grad, scalar_pde_laplacian
vector_pde_laplacian calls fld_grad, vector_pde_laplacian
pde_grad calls vector_pde_grad
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
pde_laplacian calls scalar_pde_laplacian_phi, vector_pde_laplacian_phi, vector_pde_laplacian_gamma_phi, scalar_pde_laplacian_gamma_phi