scalar_fld_vector_mul – Morfeus Framework
scalar_fld_vector_mul Module Procedure
20 statements
Source File
module procedure scalar_fld_vector_mul impure module function scalar_fld_vector_mul(fld_s, v) result(res) Interface →
Uses
class_dimensions
class_field
class_scalar_field
class_vector_field
class_vector
class_psblas
Arguments
Type Intent Optional Attributes Name
type(scalar_field), intent(in) :: fld_s
type(vector), intent(in) :: v
Return Value type(vector_field)
Calls
Called by
Contents
None
Call graph
scalar_fld_vector_mul calls vector_, scalar_fld_vector_mul
vector_ calls vector_
operator(*) calls scalar_fld_vector_mul