scalar_pde_d2dt2_fld_phi – Morfeus Framework
scalar_pde_d2dt2_fld_phi Module Procedure
4 statements
Source File
module procedure scalar_pde_d2dt2_fld_phi module subroutine scalar_pde_d2dt2_fld_phi(sign, pde, fld, phi, dt, side) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(scalar_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: fld
type(scalar_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in) :: dt
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
scalar_pde_d2dt2_fld_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_fld_phi
scalar_pde_d2dt2 calls scalar_pde_d2dt2, mypnum_, abort_psblas, psb_get_loc_to_glob, check_mesh_consistency, psb_cd_get_local_rows, pde_sign, size_blk
mypnum_ calls mypnum_
check_mesh_consistency calls check_mesh_consistency, abort_psblas
pde_sign calls pde_sign, abort_psblas
size_blk calls size_blk
abort_psblas calls abort_psblas, psb_abort
pde_d2dt2 calls scalar_pde_d2dt2_fld_phi