scalar_field_scal – Morfeus Framework
scalar_field_scal Module Procedure
15 statements
Source File
module procedure scalar_field_scal module function scalar_field_scal(a, f) result(r) Interface →
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(in) :: a
class(scalar_field), intent(in) :: f
Return Value type(scalar_field)
Calls
Called by
Contents
None
Call graph
scalar_field_scal calls abort_psblas, scalar_field_scal
abort_psblas calls abort_psblas, psb_abort