set_vector_field_group – Morfeus Framework
set_vector_field_group Module Procedure
28 statements
Source File
module procedure set_vector_field_group module subroutine set_vector_field_group(f, ig, x) Interface →
Uses
class_connectivity
class_mesh
class_vector
Arguments
Type Intent Optional Attributes Name
class(vector_field), intent(inout) :: f
integer, intent(in) :: ig
type(vector), intent(in) :: x
Calls
Called by
Contents
None
Call graph
set_vector_field_group calls abort_psblas, set_vector_field_group
abort_psblas calls abort_psblas, psb_abort