set_scalar_field_group – Morfeus Framework
set_scalar_field_group Module Procedure
26 statements
Source File
module procedure set_scalar_field_group module subroutine set_scalar_field_group(f, ig, x) Interface →
Uses
class_connectivity
class_mesh
Arguments
Type Intent Optional Attributes Name
class(scalar_field), intent(inout) :: f
integer, intent(in) :: ig
real(kind=psb_dpk_), intent(in) :: x
Calls
Called by
Contents
None
Call graph
set_scalar_field_group calls abort_psblas, set_scalar_field_group
abort_psblas calls abort_psblas, psb_abort