set_least_squares – Morfeus Framework
set_least_squares Module Procedure
104 statements
Source File
module procedure set_least_squares module subroutine set_least_squares(lsr, ncd, desc, c2c, f2b, faces, cell_cntr, face_cntr) Interface →
Uses
class_connectivity
tools_math
psb_base_mod
Arguments
Type Intent Optional Attributes Name
type(least_squares), allocatable :: lsr(:)
integer, intent(in) :: ncd
type(psb_desc_type), intent(in) :: desc
type(connectivity), intent(in) :: c2c
type(connectivity), intent(in) :: f2b
type(face), intent(in) :: faces(:)
type(vector), intent(in) :: cell_cntr(:)
type(vector), intent(in) :: face_cntr(:)
Calls
Called by
Contents
None
Call graph
set_least_squares calls psb_cd_get_local_rows, mypnum_, alloc_least_squares, set_least_squares
mypnum_ calls mypnum_
alloc_least_squares calls alloc_least_squares, abort_psblas
abort_psblas calls abort_psblas, psb_abort
create_mesh calls set_least_squares, create_mesh
smooth_mesh calls set_least_squares, smooth_mesh