set_output_path_iter – Morfeus Framework
set_output_path_iter Module Procedure
8 statements
Source File
module procedure set_output_path_iter module subroutine set_output_path_iter(out, iter) Interface →
Uses
tools_output_basics
Arguments
Type Intent Optional Attributes Name
class(output), intent(inout) :: out
type(iterating), intent(in) :: iter
Calls
Called by
Contents
None
Call graph
set_output_path_iter calls itoh, set_output_path_iter
itoh calls itoh, abort_psblas
abort_psblas calls abort_psblas, psb_abort