set_block_metadata – Morfeus Framework
set_block_metadata Module Procedure
13 statements
Source File
module procedure set_block_metadata module subroutine set_block_metadata(this) Interface →
Uses
emulated_intrinsics_interface
Arguments
Type Intent Optional Attributes Name
class(sphere_1d), intent(inout) :: this
Calls
Called by
Contents
None
Call graph
set_block_metadata calls read_wrappers_components, read_core_components, verify_core_components, set_metadata, verify_wrappers_components, verify_layers, set_block_metadata
read_wrappers_components calls assert, names
read_core_components calls assert, names
set_metadata calls assert, theta_domain, phi_domain, r_domain
verify_wrappers_components calls assert
assert calls assert