set_up_div_scalar_flux – Morfeus Framework
set_up_div_scalar_flux Module Procedure
112 statements
Source File
module procedure set_up_div_scalar_flux module subroutine set_up_div_scalar_flux(this, vertices, block_surfaces, div_flux_internal_points) Interface →
Evaluate 2nd partial derivatives in each coordinate direction according to equations (2.2) & (2.4) in Sundqvist & Veronis (1969) "A simple finite-difference grid with non-constant intervals", Tellus 22:1
compute scalar flux divergence at internal points and boundary points excluding x-direction boundaries
(dx_b + dx_f)/2 forward flux in x direction backward flux in x direction forward flux in y direction backward flux in y direction forward flux in z direction backward flux in z direction
Arguments
Type Intent Optional Attributes Name
class(cylindrical_grid), intent(in) :: this
class(structured_grid), intent(in) :: vertices
type(surfaces), intent(inout) :: block_surfaces
class(structured_grid), intent(inout) :: div_flux_internal_points
Calls
Called by
Contents
None
Call graph
set_up_div_scalar_flux calls npoints, positions, assert, s, set_up_div_scalar_flux
assert calls assert