set_block_metadata – Morfeus Framework
set_block_metadata Module Procedure
13 statements
Source File
module procedure set_block_metadata module subroutine set_block_metadata(this) Interface →
Uses
emulated_intrinsics_interface
Arguments
Type Intent Optional Attributes Name
class(plate_3d), intent(inout) :: this
Calls
Called by
Contents
None
Call graph
set_block_metadata calls verify_layers, verify_core_components, read_core_components, set_metadata, verify_wrappers_components, read_wrappers_components, set_block_metadata
read_core_components calls assert, names
set_metadata calls assert, y_domain, z_domain, x_domain
verify_wrappers_components calls assert
read_wrappers_components calls assert, names
assert calls assert