set_bc_wall_map_s – Morfeus Framework
set_bc_wall_map_s Module Procedure
13 statements
Source File
module procedure set_bc_wall_map_s module subroutine set_bc_wall_map_s(bc, i, a, b, c) Interface →
Uses
tools_bc
class_bc_math
Arguments
Type Intent Optional Attributes Name
class(bc_wall), intent(inout) :: bc
integer, intent(in) :: i
real(kind=psb_dpk_), intent(in) :: a
real(kind=psb_dpk_), intent(in) :: b
real(kind=psb_dpk_), intent(in) :: c
Calls
Called by
Contents
None
Call graph
set_bc_wall_map_s calls abort_psblas, set_bc_wall_map_s
abort_psblas calls abort_psblas, psb_abort