set_grid_specification – Morfeus Framework
set_grid_specification Module Procedure
17 statements
Source File
module procedure set_grid_specification module subroutine set_grid_specification(this, grid_description_file) Interface →
Uses
string_functions_interface
units_interface
Arguments
Type Intent Optional Attributes Name
class(plate_3d), intent(out) :: this
character(len=*), intent(in) :: grid_description_file
Calls
Called by
Contents
None
Call graph
set_grid_specification calls assert, file_extension, set_grid_specification
assert calls assert
file_extension calls file_extension