smooth_interior_vtx – Morfeus Framework
smooth_interior_vtx Module Procedure
151 statements
Source File
module procedure smooth_interior_vtx module subroutine smooth_interior_vtx(iv, msh, c2v, shared_flag, all_tets) Interface →
Uses
class_psblas
class_cell
class_connectivity
class_keytable
class_mesh
class_vector
class_vertex
tools_mesh_basics
tools_mesh_check
tools_mesh_optimize
$ j = 0 $ random_iteration: do $ j = j + 1 $ $ ! set up connectivity array and check if any cells are tangled $ local_tangled = 0 $ $ update_volume: do itet = 1,num_incident_tet $ $ if (shared_flag(iv)) then ! use global id's set above $ ic = ic2v(itet) $ $ !lookup vertex numbers, global cell and vertex id's $ call get_kt_row (msh%ov2c_sup, ic, iv2c) $ $ ! make a copy to dereference iv2c $ index_copy(1:4) = iv2c(1:4) $
$ call psb_glob_to_loc(index_copy,msh%desc_v,info) $ $ else $ ic = ic2v(itet) ! look up cell id number from ith conn $ $ !get the vertices for this cell $ call get_ith_conn(iv2c,msh%v2c,ic) $ $ ! make a copy to dereference iv2c $ index_copy(1:4) = iv2c(1:4) $ endif $ $ ! check to see if the cell is inverted $ iv1 = index_copy(1) $ iv2 = index_copy(2) $ iv3 = index_copy(3) $ iv4 = index_copy(4) $ $ valid_flag = right_handed(vtx1, vtx2, vtx3, vtx4) $ $ if (valid_flag /= 1) local_tangled = 1 $ end do update_volume $ $ if ((local_tangled == 0) .or. (j >=50)) exit $ $ if (local_tangled == 1) call optimize_vertex_rand(msh,c2v,iv) $
$ end do random_iteration $ $ deallocate(relative_numbering) $ $ deallocate(tet_pos,tet_verts) $ $ if (allocated(idloc)) deallocate(idloc) $ $ if (allocated(idglob)) deallocate(idglob) $
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iv
type(mesh), intent(inout) :: msh
type(connectivity), intent(in) :: c2v
logical, intent(in) :: shared_flag(:)
logical, intent(in) :: all_tets(:)
Calls
Called by
Contents
None
Call graph
smooth_interior_vtx calls call_smooth, loc_to_glob_, vector_, abort_psblas, right_handed, psb_glob_to_loc, psb_loc_to_glob, mypnum_, smooth_interior_vtx
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
mypnum_ calls mypnum_