smooth_mesh – Morfeus Framework
smooth_mesh Module Procedure
211 statements
Source File
module procedure smooth_mesh module subroutine smooth_mesh(msh, bc, surface_iter, interior_iter) Interface →
Uses
class_bc
class_psblas
class_cell
class_connectivity
class_keytable
class_least_squares
class_mesh
class_vector
class_vertex
tools_mesh_basics
tools_mesh_check
tools_mesh_optimize
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(inout) :: msh
type(bc_poly), intent(in) :: bc(:)
type(iterating), intent(inout) :: surface_iter
type(iterating), intent(inout) :: interior_iter
Calls
Called by
Contents
None
Call graph
smooth_mesh calls abort_psblas, free_conn, psb_geall, psb_cd_get_local_rows, vector_, initoptms, geom_cell, geom_diff, mypnum_, psb_sum, freeoptms, laplacian_smooth, geom_face, freeoptms2d, update_vertex_halo, mobile_verts, psb_gefree, psb_amx, check_right_handed, psb_ovrl, icontxt_, psb_get_overlap, free_least_squares, set_least_squares, initoptms2d, psb_erractionsave, smooth_mesh
abort_psblas calls abort_psblas, psb_abort
free_conn calls free_conn, abort_psblas
vector_ calls vector_
geom_cell calls geom_cell, abort_psblas, vector_, geom_tet_center, vertex_, geom_tet_volume, alloc_vector, 3
geom_diff calls geom_diff, abort_psblas, vector_, mypnum_, psb_sum, icontxt_, 3
mypnum_ calls mypnum_
laplacian_smooth calls laplacian_smooth, abort_psblas, psb_geall, psb_cd_get_local_rows, vector_, psb_gefree, psb_ovrl, icontxt_, psb_erractionsave, psb_spasb, loc_to_glob_, build_prec, psb_precfree, solve_sys, psb_geasb, psb_spall, psb_erractionrestore, psb_geins, psb_spins, psb_spfree, psb_check_error
geom_face calls geom_face, abort_psblas, vector_, alloc_vector, 3
update_vertex_halo calls update_vertex_halo, update_vector_halo
mobile_verts calls mobile_verts, free_conn, psb_cd_get_local_rows, loc_to_glob_
check_right_handed calls check_right_handed, abort_psblas, psb_cd_get_local_rows, psb_glob_to_loc, loc_to_glob_, right_handed
icontxt_ calls icontxt_
free_least_squares calls free_least_squares, abort_psblas
set_least_squares calls set_least_squares, psb_cd_get_local_rows, mypnum_, alloc_least_squares
update_vector_halo calls update_vector_halo, abort_psblas, icontxt_, psb_erractionsave, psb_erractionrestore, psb_check_error, psb_halo, psb_cd_get_local_cols
geom_tet_center calls geom_tet_center
geom_tet_volume calls geom_tet_volume
build_prec calls psb_build_prec
alloc_vector calls alloc_vector, abort_psblas
solve_sys calls psb_solve_sys, lu_solve, cholesky_solve_v, cholesky_solve_m
alloc_least_squares calls alloc_least_squares, abort_psblas
psb_solve_sys calls psb_solve_sys, mypnum_, icontxt_, psb_erractionsave, psb_erractionrestore, psb_check_error, psb_krylov
lu_solve calls lu_solve
cholesky_solve_v calls cholesky_solve_v
cholesky_solve_m calls cholesky_solve_m