smooth_surf_vtx – Morfeus Framework
smooth_surf_vtx Module Procedure
239 statements
Source File
module procedure smooth_surf_vtx module subroutine smooth_surf_vtx(iv, ib, msh, f2v, shared_flag, tangled, all_tets) Interface →
Uses
class_psblas
class_cell
class_connectivity
class_face
class_keytable
class_mesh
class_surface
class_vector
class_vertex
tools_mesh_basics
tools_mesh_check
tools_mesh_optimize
iso_c_binding
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iv
integer, intent(in) :: ib
type(mesh), intent(inout) :: msh
type(connectivity), intent(in) :: f2v
logical, intent(in) :: shared_flag(:)
integer, intent(in) :: tangled
logical, intent(in) :: all_tets(:)
Calls
Called by
Contents
None
Call graph
smooth_surf_vtx calls glob_to_loc_, abort_psblas, mypnum_, psb_glob_to_loc, loc_to_glob_, call_smooth2d, psb_loc_to_glob, right_handed2d, smooth_surf_vtx
abort_psblas calls abort_psblas, psb_abort
mypnum_ calls mypnum_