solve_least_squares – Morfeus Framework
solve_least_squares Module Procedure
6 statements
Source File
module procedure solve_least_squares module subroutine solve_least_squares(lsr, rhs) Interface →
Uses
tools_math
Arguments
Type Intent Optional Attributes Name
class(least_squares), intent(in) :: lsr
real(kind=psb_dpk_), intent(inout) :: rhs(:)
Calls
Called by
Contents
None
Call graph
solve_least_squares calls solve_sys, solve_least_squares
solve_sys calls lu_solve, cholesky_solve_v, cholesky_solve_m, psb_solve_sys
lu_solve calls lu_solve
cholesky_solve_v calls cholesky_solve_v
cholesky_solve_m calls cholesky_solve_m
psb_solve_sys calls psb_solve_sys, psb_krylov, psb_erractionsave, icontxt_, psb_check_error, mypnum_, psb_erractionrestore
icontxt_ calls icontxt_
mypnum_ calls mypnum_