start_psblas – Morfeus Framework
start_psblas Module Procedure
46 statements
Source File
module procedure start_psblas module subroutine start_psblas() Interface →
Arguments
None
Calls
Called by
Contents
None
Call graph
start_psblas calls psb_set_errverbosity, abort_psblas, psb_snd, psb_rcv, psb_set_erraction, stopwatch_, psb_init, psb_barrier, psb_info, start_psblas
abort_psblas calls abort_psblas, psb_abort
stopwatch_ calls stopwatch_