start_renum – Morfeus Framework
start_renum Module Procedure
25 statements
Source File
module procedure start_renum module subroutine start_renum(irenum, c2c) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: irenum
type(connectivity), intent(in) :: c2c
Calls
Called by
Contents
None
Call graph
start_renum calls mypnum_, abort_psblas, build_pinv, perm, cmp_gps, start_renum
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
build_pinv calls build_pinv, mypnum_, abort_psblas, perm, pinv, icontxt_
cmp_gps calls cmp_gps, abort_psblas, perm, psb_gps_reduce
icontxt_ calls icontxt_
cmp_mesh_renum calls start_renum, cmp_mesh_renum
create_mesh calls cmp_mesh_renum, create_mesh