supplement_v2c – Morfeus Framework
supplement_v2c Module Procedure
72 statements
Source File
module procedure supplement_v2c module subroutine supplement_v2c(v2c, desc_v, ov2c_suppl, c2ov_suppl) Interface →
Uses
class_psblas
class_connectivity
class_keytable
$Id: supplement_v2c.f90 3093 2008-04-22 14:51:09Z sfilippo $
Description: Creates supplementary connectivity info about cells connected to overlap (shared) vertices. The data are saved as keytables using global indexing
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(in) :: v2c
type(psb_desc_type), intent(in) :: desc_v
type(keytable), intent(out) :: ov2c_suppl
type(keytable), intent(out) :: c2ov_suppl
Calls
Called by
Contents
None
Call graph
supplement_v2c calls mypnum_, psb_erractionsave, free_conn, abort_psblas, nprocs_, psb_get_overlap, icontxt_, psb_loc_to_glob, psb_erractionrestore, supplement_v2c
mypnum_ calls mypnum_
free_conn calls free_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort
nprocs_ calls nprocs_
icontxt_ calls icontxt_
create_mesh calls supplement_v2c, create_mesh