supplement_v2f – Morfeus Framework
supplement_v2f Module Procedure
87 statements
Source File
module procedure supplement_v2f module subroutine supplement_v2f(v2f, faces, desc_v, ov2f_suppl, f2ov_suppl) Interface →
Uses
class_psblas
class_connectivity
class_keytable
$Id: supplement_v2f.f90 8157 2014-10-09 13:02:44Z sfilippo $
Description: Creates supplementary connectivity info about cells connected to overlap (shared) vertices. The data are saved as keytables using global indexing. Since this routine is called prior to re- allocating the mesh data, all indices (except the call to get overlap vertex id's) use global ID numbers.
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(inout) :: v2f
type(face) :: faces(:)
type(psb_desc_type), intent(in) :: desc_v
type(keytable), intent(out) :: ov2f_suppl
type(keytable), intent(out) :: f2ov_suppl
Calls
Called by
Contents
None
Call graph
supplement_v2f calls icontxt_, nprocs_, psb_loc_to_glob, bcast_conn, mypnum_, abort_psblas, psb_erractionsave, psb_get_overlap, psb_erractionrestore, free_conn, supplement_v2f
icontxt_ calls icontxt_
nprocs_ calls nprocs_
bcast_conn calls bcast_conn, icontxt_, mypnum_, abort_psblas, alloc_conn, psb_bcast
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
free_conn calls free_conn, abort_psblas
alloc_conn calls alloc_conn, abort_psblas
create_mesh calls supplement_v2f, create_mesh