update_boundary_wall_s – Morfeus Framework
update_boundary_wall_s Procedure
45 statements
Source File
module procedure update_boundary_wall_s module procedure update_boundary_wall_s()
Uses
class_dimensions
class_material
class_mesh
tools_bc
Arguments
None
Calls
Contents
None
Call graph
update_boundary_wall_s calls abort_psblas, im, bx, apply_abc_to_boundary, get_abc_math
abort_psblas calls abort_psblas, psb_abort