update_vector_halo – Morfeus Framework
update_vector_halo Module Procedure
21 statements
Source File
module procedure update_vector_halo module subroutine update_vector_halo(v, desc) Interface →
Uses
psb_base_mod
Arguments
Type Intent Optional Attributes Name
type(vector), intent(inout) :: v(:)
type(psb_desc_type), intent(in) :: desc
Calls
Called by
Contents
None
Call graph
update_vector_halo calls icontxt_, psb_check_error, psb_halo, abort_psblas, psb_cd_get_local_cols, psb_erractionsave, psb_erractionrestore, update_vector_halo
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort
update_vertex_halo calls update_vector_halo, update_vertex_halo
update_vector_field calls update_vector_halo, update_vector_field
scalar_field_grad calls update_vector_halo, scalar_field_grad
fld_grad calls scalar_field_grad
smooth_mesh calls update_vertex_halo, smooth_mesh
vector_pde_grad calls fld_grad, vector_pde_grad
scalar_pde_laplacian calls fld_grad, scalar_pde_laplacian
vector_pde_laplacian calls fld_grad, vector_pde_laplacian
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
pde_grad calls vector_pde_grad
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
pde_laplacian calls vector_pde_laplacian_gamma_phi, scalar_pde_laplacian_gamma_phi, vector_pde_laplacian_phi, scalar_pde_laplacian_phi