update_vector_field – Morfeus Framework
update_vector_field Module Procedure
29 statements
Source File
module procedure update_vector_field module subroutine update_vector_field(fld) Interface →
Uses
class_bc
class_dimensions
class_material
class_mesh
$ msh => msh_(fld%field) $ mat => mat_(fld%field)
Arguments
Type Intent Optional Attributes Name
class(vector_field), intent(inout) :: fld
Calls
Called by
Contents
None
Call graph
update_vector_field calls update_vector_halo, psb_erractionsave, psb_erractionrestore, abort_psblas, update_vector_field
update_vector_halo calls update_vector_halo, psb_erractionsave, psb_erractionrestore, abort_psblas, psb_check_error, psb_halo, psb_cd_get_local_cols, icontxt_
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_