update_scalar_field – Morfeus Framework
update_scalar_field Module Procedure
71 statements
Source File
module procedure update_scalar_field module subroutine update_scalar_field(fld, mats, temp) Interface →
Uses
class_bc
class_connectivity
class_dimensions
class_face
class_material
class_mesh
tools_math
$ msh => msh_(fld%field)
Arguments
Type Intent Optional Attributes Name
class(scalar_field), intent(inout) :: fld
type(matptr), intent(in), pointer :: mats(:)
type(scalar_field), intent(in), optional :: temp
temperature
Calls
Called by
Contents
None
Call graph
update_scalar_field calls matlaw, abort_psblas, psb_erractionsave, psb_halo, psb_erractionrestore, icontxt_, lin_interp, update_scalar_field
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
lin_interp calls lin_interp_v, lin_interp_s
lin_interp_v calls lin_interp_v
lin_interp_s calls lin_interp_s