update_vertex_halo – Morfeus Framework
update_vertex_halo Module Procedure
3 statements
Source File
module procedure update_vertex_halo module subroutine update_vertex_halo(verts, desc) Interface →
Arguments
Type Intent Optional Attributes Name
type(vertex) :: verts(:)
type(psb_desc_type), intent(in) :: desc
Calls
Called by
Contents
None
Call graph
update_vertex_halo calls update_vector_halo, update_vertex_halo
update_vector_halo calls update_vector_halo, icontxt_, psb_check_error, psb_halo, abort_psblas, psb_cd_get_local_cols, psb_erractionsave, psb_erractionrestore
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort
smooth_mesh calls update_vertex_halo, smooth_mesh