vector_field_dif – Morfeus Framework
vector_field_dif Module Procedure
23 statements
Source File
module procedure vector_field_dif module function vector_field_dif(f1, f2) result(r) Interface →
Uses
class_dimensions
Arguments
Type Intent Optional Attributes Name
class(vector_field), intent(in) :: f1
type(vector_field), intent(in) :: f2
Return Value type(vector_field)
Calls
Called by
Contents
None
Call graph
vector_field_dif calls abort_psblas, vector_field_dif
abort_psblas calls abort_psblas, psb_abort