vector_ – Morfeus Framework
vector_ Module Procedure
5 statements
Source File
module procedure vector_ elemental module function vector_(x, y, z) Interface →
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(in) :: x
real(kind=psb_dpk_), intent(in) :: y
real(kind=psb_dpk_), intent(in) :: z
Return Value type(vector)
Called by
Contents
None
Call graph
vector_ calls vector_
geom_diff calls vector_, geom_diff
vector_field_grad calls vector_, vector_field_grad
vector_pde_div calls vector_, vector_pde_div
laplacian_smooth calls vector_, laplacian_smooth
geom_cell calls vector_, geom_cell
alloc_cylinder calls vector_, try_cylinder_r2, alloc_cylinder
alloc_plane calls vector_, alloc_plane
smooth_mesh calls vector_, geom_cell, geom_diff, laplacian_smooth, geom_face, smooth_mesh
create_vector_field calls vector_, create_vector_field
fcn calls vector_
vertex_1_ calls vector_
rd_inp_motion_law calls vector_, rd_inp_motion_law
read_par_v calls vector_
geom_face calls vector_, geom_face
vector_pde_laplacian calls vector_, fld_grad, vector_pde_laplacian
solve_vector_pde calls vector_, solve_vector_pde
try_cylinder_r2 calls vector_
scalar_fld_vector_mul calls vector_, scalar_fld_vector_mul
smooth_interior_vtx calls vector_, smooth_interior_vtx
scalar_field_grad calls vector_, scalar_field_grad
get_motion_velocity calls vector_, get_motion_velocity
get_par_v calls vector_
alloc_vertex calls vector_, alloc_vertex
get_motion_displacement calls vector_, get_motion_displacement
get_abc_math_v calls vector_
create_mesh calls geom_cell, geom_diff, geom_face, g2l_mesh, import_mesh, create_mesh
g2l_vertex calls alloc_vertex, g2l_vertex
pde_div calls vector_pde_div
rd_gmsh_mesh calls alloc_vertex, rd_gmsh_mesh
l2g_vertex calls alloc_vertex, l2g_vertex
rd_exodus_mesh calls alloc_vertex, rd_exodus_mesh
create_motion calls rd_inp_motion_law, create_motion
operator(*) calls scalar_fld_vector_mul
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
rd_cgns_mesh calls alloc_vertex, rd_cgns_mesh
rd_gambit_mesh calls alloc_vertex, rd_gambit_mesh
bcast_vertex calls alloc_vertex, bcast_vertex
fld_grad calls vector_field_grad, scalar_field_grad
alloc_surface calls alloc_plane, alloc_surface
vector_pde_grad calls fld_grad, vector_pde_grad
scalar_pde_laplacian calls fld_grad, scalar_pde_laplacian
write_exo_morfeus calls l2g_vertex, write_exo_morfeus
g2l_mesh calls g2l_vertex, bcast_vertex
import_mesh calls rd_gambit_mesh, rd_gmsh_mesh
write_mesh calls l2g_vertex, write_mesh
pde_laplacian calls vector_pde_laplacian_gamma_phi, vector_pde_laplacian_phi, scalar_pde_laplacian_phi, scalar_pde_laplacian_gamma_phi
pde_grad calls vector_pde_grad
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi