vector_field_grad – Morfeus Framework
vector_field_grad Module Procedure
141 statements
Source File
module procedure vector_field_grad module function vector_field_grad(phi) result(grad) Interface →
Uses
class_psblas
class_connectivity
class_face
class_least_squares
class_mesh
class_vector_field
class_vector
Arguments
Type Intent Optional Attributes Name
type(vector_field), intent(in) :: phi
Return Value type(vector), allocatable,(:,:)
Calls
Called by
Contents
None
Call graph
vector_field_grad calls psb_cd_get_local_rows, vector_, abort_psblas, vector_field_grad
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
fld_grad calls vector_field_grad
vector_pde_grad calls fld_grad, vector_pde_grad
vector_pde_laplacian calls fld_grad, vector_pde_laplacian
scalar_pde_laplacian calls fld_grad, scalar_pde_laplacian
pde_grad calls vector_pde_grad
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
pde_laplacian calls scalar_pde_laplacian_phi, scalar_pde_laplacian_gamma_phi, vector_pde_laplacian_phi, vector_pde_laplacian_gamma_phi