vector_pde_d2dt2_fld_phi – Morfeus Framework
vector_pde_d2dt2_fld_phi Module Procedure
4 statements
Source File
module procedure vector_pde_d2dt2_fld_phi module subroutine vector_pde_d2dt2_fld_phi(sign, pde, fld, phi, dt, side) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(vector_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: fld
type(vector_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in) :: dt
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
vector_pde_d2dt2_fld_phi calls vector_pde_d2dt2, vector_pde_d2dt2_fld_phi
vector_pde_d2dt2 calls vector_pde_d2dt2, psb_cd_get_local_rows, mypnum_, psb_get_loc_to_glob, pde_sign, abort_psblas, size_blk
mypnum_ calls mypnum_
pde_sign calls pde_sign, abort_psblas
abort_psblas calls abort_psblas, psb_abort
size_blk calls size_blk
pde_d2dt2 calls vector_pde_d2dt2_fld_phi