vector_field_sum – Morfeus Framework
vector_field_sum Module Procedure
23 statements
Source File
module procedure vector_field_sum module function vector_field_sum(f1, f2) result(r) Interface →
Uses
class_dimensions
Arguments
Type Intent Optional Attributes Name
class(vector_field), intent(in) :: f1
type(vector_field), intent(in) :: f2
Return Value type(vector_field)
Calls
Called by
Contents
None
Call graph
vector_field_sum calls abort_psblas, vector_field_sum
abort_psblas calls abort_psblas, psb_abort