vector_pde_laplacian – Morfeus Framework
vector_pde_laplacian Module Procedure
308 statements
Source File
module procedure vector_pde_laplacian module subroutine vector_pde_laplacian(sign, pde, phi, gamma, side) Interface →
Uses
class_psblas
class_bc
class_connectivity
class_dimensions
class_face
class_scalar_field
class_vector_field
class_mesh
class_vector_pde
class_vector
op_grad
tools_bc
tools_operators
class_mesh
class_mesh
This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface $ write(0,*) 'Vector pde laplacian',i, if, ibf,& $ & gamma_bx(ibf), msh%area(if), msh%dist(if)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(vector_pde), intent(inout) :: pde
type(vector_field), intent(in) :: phi
type(scalar_field), intent(in), optional :: gamma
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
vector_pde_laplacian calls fld_grad, pde_sign, vector_, abort_psblas, check_mesh_consistency, size_blk, psb_get_loc_to_glob, mypnum_, vector_pde_laplacian
fld_grad calls scalar_field_grad, vector_field_grad
pde_sign calls pde_sign, abort_psblas
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
check_mesh_consistency calls check_mesh_consistency, abort_psblas
size_blk calls size_blk
mypnum_ calls mypnum_
scalar_field_grad calls scalar_field_grad, vector_, abort_psblas, update_vector_halo, psb_cd_get_local_rows
vector_field_grad calls vector_field_grad, vector_, abort_psblas, psb_cd_get_local_rows
update_vector_halo calls update_vector_halo, abort_psblas, psb_erractionsave, psb_check_error, psb_halo, psb_erractionrestore, psb_cd_get_local_cols, icontxt_
icontxt_ calls icontxt_
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
pde_laplacian calls vector_pde_laplacian_phi, vector_pde_laplacian_gamma_phi