vector_field_flux – Morfeus Framework
vector_field_flux Module Procedure
68 statements
Source File
module procedure vector_field_flux module function vector_field_flux(fld) result(res) Interface →
Uses
class_psblas
class_connectivity
class_dimensions
class_field
class_scalar_field
class_vector_field
class_vector
class_mesh
Arguments
Type Intent Optional Attributes Name
type(vector_field), intent(in) :: fld
Return Value type(scalar_field)
Calls
Called by
Contents
None
Call graph
vector_field_flux calls abort_psblas, free_vector, vector_field_flux
abort_psblas calls abort_psblas, psb_abort
free_vector calls free_vector, abort_psblas
fld_flux calls vector_field_flux