vector_pde_grad – Morfeus Framework
vector_pde_grad Module Procedure
93 statements
Source File
module procedure vector_pde_grad module subroutine vector_pde_grad(sign, pde, phi, side) Interface →
Uses
class_psblas
class_connectivity
class_dimensions
class_face
class_scalar_field
class_mesh
class_vector_pde
class_vector
tools_math
tools_operators
class_mesh
This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
class(vector_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
vector_pde_grad calls mypnum_, abort_psblas, geins_pde, psb_get_loc_to_glob, fld_grad, check_mesh_consistency, psb_cd_get_local_rows, pde_sign, size_blk, vector_pde_grad
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
fld_grad calls scalar_field_grad, vector_field_grad
check_mesh_consistency calls check_mesh_consistency, abort_psblas
pde_sign calls pde_sign, abort_psblas
size_blk calls size_blk
scalar_field_grad calls scalar_field_grad, abort_psblas, psb_cd_get_local_rows, vector_, update_vector_halo
vector_field_grad calls vector_field_grad, abort_psblas, psb_cd_get_local_rows, vector_
vector_ calls vector_
update_vector_halo calls update_vector_halo, abort_psblas, psb_check_error, psb_erractionsave, psb_cd_get_local_cols, icontxt_, psb_erractionrestore, psb_halo
icontxt_ calls icontxt_
pde_grad calls vector_pde_grad