vector_pde_d2dt2 – Morfeus Framework
vector_pde_d2dt2 Module Procedure
126 statements
Source File
module procedure vector_pde_d2dt2 module subroutine vector_pde_d2dt2(sign, pde, phi, dt, fld, side) Interface →
Uses
class_psblas
class_dimensions
class_mesh
class_scalar_field
class_vector_field
class_vector_pde
class_vector
tools_operators
$ write(0,*) 'From vector_pde_ddt: A',i,ic_glob,& $ & a(i),dtinv, x_(b(i)),& $ & y_(b(i)),z_(b(i))
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(vector_pde), intent(inout) :: pde
type(vector_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in) :: dt
type(scalar_field), intent(in), optional :: fld
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
vector_pde_d2dt2 calls pde_sign, abort_psblas, psb_cd_get_local_rows, size_blk, psb_get_loc_to_glob, mypnum_, vector_pde_d2dt2
pde_sign calls pde_sign, abort_psblas
abort_psblas calls abort_psblas, psb_abort
size_blk calls size_blk
mypnum_ calls mypnum_
vector_pde_d2dt2_phi calls vector_pde_d2dt2, vector_pde_d2dt2_phi
vector_pde_d2dt2_fld_phi calls vector_pde_d2dt2, vector_pde_d2dt2_fld_phi
pde_d2dt2 calls vector_pde_d2dt2_fld_phi, vector_pde_d2dt2_phi