vector_pde_div – Morfeus Framework
vector_pde_div Module Procedure
262 statements
Source File
module procedure vector_pde_div module subroutine vector_pde_div(sign, pde, phi, flux, side, ds) Interface →
Uses
class_psblas
class_bc
class_discretization
class_dimensions
class_vector
class_mesh
class_vector_pde
tools_bc
tools_operators
class_mesh
class_mesh
This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface This is in a block statement due to gfortran-8.3 issue w/ not being able to find this interface $ write(0,*) 'From vector_pde_div: scale for A',i,im_glob,is_glob,& $ & coeff_a(1:4),fsign, flux_x(i),msh%interp(if)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(vector_pde), intent(inout) :: pde
type(vector_field), intent(in) :: phi
type(scalar_field), intent(inout) :: flux
real(kind=psb_dpk_), intent(in), optional :: side
type(discretization), intent(in), optional :: ds
Calls
Called by
Contents
None
Call graph
vector_pde_div calls psb_get_loc_to_glob, vector_, abort_psblas, pde_sign, mypnum_, size_blk, check_mesh_consistency, vector_pde_div
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
pde_sign calls pde_sign, abort_psblas
mypnum_ calls mypnum_
size_blk calls size_blk
check_mesh_consistency calls check_mesh_consistency, abort_psblas
pde_div calls vector_pde_div