vector_pde_laplacian_gamma_phi – Morfeus Framework
vector_pde_laplacian_gamma_phi Module Procedure
3 statements
Source File
module procedure vector_pde_laplacian_gamma_phi module subroutine vector_pde_laplacian_gamma_phi(sign, pde, gamma, phi, side) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: sign
type(vector_pde), intent(inout) :: pde
type(scalar_field), intent(in) :: gamma
type(vector_field), intent(in) :: phi
real(kind=psb_dpk_), intent(in), optional :: side
Calls
Called by
Contents
None
Call graph
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
vector_pde_laplacian calls vector_pde_laplacian, psb_get_loc_to_glob, vector_, abort_psblas, pde_sign, mypnum_, fld_grad, size_blk, check_mesh_consistency
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
pde_sign calls pde_sign, abort_psblas
mypnum_ calls mypnum_
fld_grad calls vector_field_grad, scalar_field_grad
size_blk calls size_blk
check_mesh_consistency calls check_mesh_consistency, abort_psblas
vector_field_grad calls vector_field_grad, vector_, abort_psblas, psb_cd_get_local_rows
scalar_field_grad calls scalar_field_grad, vector_, abort_psblas, psb_cd_get_local_rows, update_vector_halo
update_vector_halo calls update_vector_halo, abort_psblas, psb_erractionsave, icontxt_, psb_check_error, psb_halo, psb_cd_get_local_cols, psb_erractionrestore
icontxt_ calls icontxt_
pde_laplacian calls vector_pde_laplacian_gamma_phi