wr_mtx_vector – Morfeus Framework
wr_mtx_vector Module Procedure
34 statements
Source File
module procedure wr_mtx_vector module subroutine wr_mtx_vector(loc_vect, desc, name) Interface →
Uses
class_psblas
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_) :: loc_vect(:)
type(psb_desc_type), intent(in) :: desc
character(len=*), intent(in) :: name
Calls
Called by
Contents
None
Call graph
wr_mtx_vector calls mypnum_, psb_erractionsave, abort_psblas, icontxt_, psb_cd_get_global_cols, psb_gather, psb_erractionrestore, wr_mtx_vector
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
write_vector_pde calls wr_mtx_vector, write_vector_pde
write_scalar_pde calls wr_mtx_vector, write_scalar_pde