wr_mtx_matrix – Morfeus Framework
wr_mtx_matrix Module Procedure
66 statements
Source File
module procedure wr_mtx_matrix module subroutine wr_mtx_matrix(a, desc, name) Interface →
Uses
class_psblas
Arguments
Type Intent Optional Attributes Name
type(psb_dspmat_type), intent(in) :: a
type(psb_desc_type), intent(in) :: desc
character(len=*), intent(in) :: name
Calls
Called by
Contents
None
Call graph
wr_mtx_matrix calls psb_get_loc_to_glob, abort_psblas, psb_erractionsave, icontxt_, psb_snd, nprocs_, psb_check_error, psb_rcv, mypnum_, psb_sum, psb_amx, psb_erractionrestore, wr_mtx_matrix
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
nprocs_ calls nprocs_
mypnum_ calls mypnum_
write_pde calls wr_mtx_matrix, write_pde