write_scalar_field – Morfeus Framework
write_scalar_field Module Procedure
45 statements
Source File
module procedure write_scalar_field module subroutine write_scalar_field(fld, field, out, iter) Interface →
Uses
class_psblas
$ msh => msh_(fld)
Arguments
Type Intent Optional Attributes Name
type(scalar_field), intent(in) :: fld
character(len=*), intent(in) :: field
type(output), intent(inout) :: out
type(iterating), intent(in), optional :: iter
Calls
Called by
Contents
None
Call graph
write_scalar_field calls icontxt_, l2g_cell, psb_check_error, psb_gather, abort_psblas, mypnum_, get_mesh, get_x, psb_erractionsave, psb_erractionrestore, psb_cd_get_global_cols, write_scalar_field
icontxt_ calls icontxt_
mypnum_ calls mypnum_
write_field calls write_scalar_field