write_vector_field – Morfeus Framework
write_vector_field Module Procedure
51 statements
Source File
module procedure write_vector_field module subroutine write_vector_field(fld, field, out, iter) Interface →
Uses
class_psblas
class_cell
class_vector
class_iterating
class_mesh
class_output
class_vector_field
tools_output_basics
$ msh => msh_(fld) $ call psb_check_error(info,'write_scalar_field','psb_gather',icontxt)
Arguments
Type Intent Optional Attributes Name
type(vector_field), intent(in) :: fld
character(len=*), intent(in) :: field
type(output), intent(inout) :: out
type(iterating), intent(in), optional :: iter
Calls
Called by
Contents
None
Call graph
write_vector_field calls l2g_cell, l2g_vector, psb_cd_get_global_cols, abort_psblas, psb_erractionsave, get_x, psb_erractionrestore, icontxt_, mypnum_, get_mesh, write_vector_field
l2g_cell calls l2g_cell, psb_cd_get_global_cols, abort_psblas, psb_erractionsave, psb_erractionrestore, icontxt_, mypnum_, psb_geall, psb_check_error, psb_gefree, alloc_cell, psb_gather
l2g_vector calls l2g_vector, psb_cd_get_global_cols, abort_psblas, psb_erractionsave, psb_erractionrestore, icontxt_, mypnum_, psb_geall, alloc_vector, psb_check_error, psb_gefree, psb_gather, psb_ovrl
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
mypnum_ calls mypnum_
alloc_vector calls alloc_vector, abort_psblas
alloc_cell calls alloc_cell, abort_psblas
write_field calls write_vector_field