write_mesh – Morfeus Framework
write_mesh Module Procedure
77 statements
Source File
module procedure write_mesh module subroutine write_mesh(msh, out, iter) Interface →
Uses
class_psblas
class_cell
class_connectivity
class_face
class_iterating
class_mesh
class_output
class_vertex
tools_output_basics
Arguments
Type Intent Optional Attributes Name
type(mesh), intent(in) :: msh
type(output), intent(inout) :: out
type(iterating), intent(in), optional :: iter
Calls
Called by
Contents
None
Call graph
write_mesh calls icontxt_, l2g_face, psb_gefree, psb_check_error, psb_gather, mypnum_, psb_geall, abort_psblas, psb_erractionsave, l2g_cell, l2g_conn, free_conn, psb_erractionrestore, psb_cd_get_global_cols, l2g_vertex, write_mesh
icontxt_ calls icontxt_
l2g_face calls l2g_face, icontxt_, psb_gefree, psb_check_error, psb_gather, mypnum_, psb_geall, abort_psblas, psb_erractionsave, psb_erractionrestore, psb_cd_get_global_cols, alloc_face, psb_get_loc_to_glob
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
l2g_cell calls l2g_cell, icontxt_, psb_gefree, psb_check_error, psb_gather, mypnum_, psb_geall, abort_psblas, psb_erractionsave, psb_erractionrestore, psb_cd_get_global_cols, alloc_cell
l2g_conn calls l2g_conn, icontxt_, psb_gefree, psb_check_error, psb_gather, mypnum_, psb_geall, abort_psblas, psb_erractionsave, free_conn, psb_erractionrestore, psb_amx, psb_get_loc_to_glob, alloc_conn
free_conn calls free_conn, abort_psblas
l2g_vertex calls l2g_vertex, icontxt_, mypnum_, psb_erractionsave, psb_erractionrestore, psb_cd_get_global_cols, alloc_vector, l2g_vector, free_vector, alloc_vertex
alloc_face calls alloc_face, abort_psblas
alloc_vector calls alloc_vector, abort_psblas
l2g_vector calls l2g_vector, icontxt_, psb_gefree, psb_check_error, psb_gather, mypnum_, psb_geall, abort_psblas, psb_erractionsave, psb_erractionrestore, psb_cd_get_global_cols, alloc_vector, psb_ovrl
free_vector calls free_vector, abort_psblas
alloc_cell calls alloc_cell, abort_psblas
alloc_conn calls alloc_conn, abort_psblas
alloc_vertex calls alloc_vertex, abort_psblas, vector_
vector_ calls vector_