write_output – Morfeus Framework
write_output Module Procedure
Ian Porter
11/25/2019
17 statements
Source File
module procedure write_output module subroutine write_output(this, filename) Interface →
Uses
string_functions_interface
This is a generic procedure for writing output files. This procedure eliminates the DTIO to allow for linking to external libraries that handle all of the file output
Arguments
Type Intent Optional Attributes Name
class(problem_discretization), intent(in) :: this
character(len=*), intent(in) :: filename
Calls
Called by
Contents
None
Call graph
write_output calls vtk_output, csv_output, file_extension, base_name, write_output
vtk_output calls flux_divergence_attributes, ncells, scalar_attributes, vtk_serial_write
file_extension calls file_extension
base_name calls base_name