write_vtk_morfeus – Morfeus Framework
write_vtk_morfeus Module Procedure
101 statements
Source File
module procedure write_vtk_morfeus module subroutine write_vtk_morfeus(out, msh, sfield, vfield, iter) Interface →
Uses
class_psblas
vtk_attributes
vtk_cells
vtk_datasets
vtk
class_vector
This collapses all images to one
This keeps things local Take the # of vertices and convert it to the type of cell Triangle Tetra Quad Pyramid Wedge Hexahedron Sets the proper type of cell based on value of icverts Need to fill in an array of connectivity Set cell into array of cells Set up the geometry using a vtk structured grid
Set cell values Program supplied scalars Program supplied vectors Set cell values Supplied values Finish writing the serial file for each image
Arguments
Type Intent Optional Attributes Name
class(vtk_output_), intent(inout) :: out
DT of output file info
type(mesh), intent(in) :: msh
DT of mesh info
type(scalar_field), intent(in), optional dimension(:) :: sfield
DT of scalar info
type(vector_field), intent(in), optional dimension(:) :: vfield
DT of vector info
type(iterating), intent(in), optional :: iter
DT of iteration info
Calls
Called by
Contents
None
Call graph
write_vtk_morfeus calls vtk_serial_write, write_vtk_mesh, set_cell_type, x_loc, write_vtk_morfeus
write_vtk_mesh calls psb_cd_get_global_cols, abort_psblas, psb_geall, psb_erractionsave, psb_check_error, psb_gefree, free_conn, psb_erractionrestore, psb_gather, wr_vtk_mesh, icontxt_, mypnum_
abort_psblas calls abort_psblas, psb_abort
free_conn calls free_conn, abort_psblas
wr_vtk_mesh calls abort_psblas
icontxt_ calls icontxt_
mypnum_ calls mypnum_