alloc_cylinder – Morfeus Framework
alloc_cylinder Interface
48 statements
Source File
interface
Calls
public module subroutine alloc_cylinder(vertices, this_cylinder) Implementation →
Arguments
Type Intent Optional Attributes Name
type(vertex), intent(in) :: vertices(:)
type(cylinder), pointer :: this_cylinder
Description
Constructs cylinder by using steepest descents to fit a cylinder to the vertices' locations. We make our figure of merit f = 1 - error
Call graph
alloc_cylinder calls alloc_cylinder, abort_psblas, my_vertices, vector_, try_cylinder_r2
abort_psblas calls abort_psblas, psb_abort
vector_ calls vector_
try_cylinder_r2 calls vector_, float, calc_error
calc_error calls float