alloc_conn – Morfeus Framework
alloc_conn Interface
92 statements
Source File
interface
**m Connectivity/free_conn
NAME free_conn USAGE call free_conn(a2b)
DESCRIPTION Destructor
INPUTS a2b :: type(connectivity) The connectivity to be destroyed;
**f Connectivity/bcast_conn
NAME bcast_conn USAGE
 call bcast_conn(a2b)
DESCRIPTION Distribute a copy of the connectivity from process 0 to everybody else.
INPUTS a2b :: type(connectivity) The connectivity to be broadcast;
**m Connectivity/get_ith_conn
NAME get_ith_conn USAGE call get_ith_conn(ith_conn,a2b,i)
DESCRIPTION Getter. Access the I-th row in the connectivity table. Returns a pointer to the requested row. Note: returning a pointer and not a copy, because it is used in tight loops; user should NEVER modify nor deallocate the returned pointer.
INPUTS a2b :: type(connectivity), intent(in), target The connectivity to be accessed; i :: integer Request access to the I-th row; OUTPUT ith_conn(:) :: integer, pointer A pointer to the i-th row;
**m Connectivity/get_conn_csr
NAME get_conn_csr USAGE call get_conn_csr(a2b,lookup,conn)
DESCRIPTION Get a full copy of the connectivity table in CSR format. Being a copy the user may do as he/she pleases with it, and should remember to deallocate it.
INPUTS a2b :: type(connectivity), intent(in) The connectivity to be accessed; OUTPUT lookup(:) :: integer, allocatable conn(:) :: integer, allocatable A copy of the lookup table. The neighbours of item I are listed at CONN(lookup(i):lookup(i+1)-1)
Calls
Called by
public module subroutine alloc_conn(a2b, nel, nconn, lb) Implementation →
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(inout) :: a2b
integer, intent(in) :: nel
integer, intent(in) :: nconn
integer, intent(in), optional :: lb
Call graph
alloc_conn calls alloc_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort
g2l_conn_core calls alloc_conn, g2l_conn_core
cmp_mesh_v2b calls alloc_conn, cmp_mesh_v2b
cmp_mesh_c2c calls alloc_conn, cmp_mesh_c2c
cmp_mesh_v2ve calls alloc_conn, cmp_mesh_v2e, cmp_mesh_v2ve
cmp_mesh_v2v calls alloc_conn, cmp_mesh_v2v
get_dual_conn calls alloc_conn, get_dual_conn
l2g_conn calls alloc_conn, l2g_conn
cmp_mesh_v2e calls alloc_conn, cmp_mesh_v2e
bcast_conn calls alloc_conn, bcast_conn
cmp_mesh_f2b calls alloc_conn, cmp_mesh_f2b
copy_conn calls alloc_conn
cmp_mesh_f2f calls alloc_conn, cmp_mesh_f2f
write_mesh calls l2g_conn, write_mesh
create_mesh calls cmp_mesh_v2b, cmp_mesh_f2f, cmp_mesh_v2ve, cmp_mesh_c2c, cmp_mesh_f2b, g2l_mesh, supplement_v2f, cmp_mesh_desc, create_mesh
cmp_mesh_desc calls bcast_conn, cmp_mesh_desc
g2l_mesh calls bcast_conn
supplement_v2f calls bcast_conn, supplement_v2f
write_exo_morfeus calls l2g_conn, write_exo_morfeus