apply_abc_to_boundary – Morfeus Framework
apply_abc_to_boundary Interface
29 statements
Source File
public interface apply_abc_to_boundary
Called by
Contents
Subroutines
apply_abc_to_boundary_s apply_abc_to_boundary_v
Subroutines
public subroutine apply_abc_to_boundary_s(id, a, b, c, ib, msh, x, bx)
WARNING! - Use intent(inout) for BX(:) - Do loop on the faces subset corresponding to IB bc. - Only this section of BX(:) is going to be modified. - BX(:) indexing starts from 1: when BX(:) is referenced an offset equal to the # of boundary faces with flag > 0 and < IB must be added to the I counter.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: id
real(kind=psb_dpk_), intent(in) :: a(:)
real(kind=psb_dpk_), intent(in) :: b(:)
real(kind=psb_dpk_), intent(in) :: c(:)
integer, intent(in) :: ib
type(mesh), intent(in) :: msh
real(kind=psb_dpk_), intent(in) :: x(:)
real(kind=psb_dpk_), intent(inout) :: bx(:)
public subroutine apply_abc_to_boundary_v(id, a, b, c, ib, msh, x, bx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: id
real(kind=psb_dpk_), intent(in) :: a(:)
real(kind=psb_dpk_), intent(in) :: b(:)
type(vector), intent(in) :: c(:)
integer, intent(in) :: ib
type(mesh), intent(in) :: msh
type(vector), intent(in) :: x(:)
type(vector), intent(inout) :: bx(:)
Call graph
update_boundary_wall_v calls apply_abc_to_boundary
update_boundary_math calls apply_abc_to_boundary, update_boundary_math
update_boundary_wall_s calls apply_abc_to_boundary
update_boundary_s calls update_boundary_math