assert – Morfeus Framework
assert Interface
9 statements
Source File
interface
Calls
Called by
public impure elemental module subroutine assert(assertion, description, diagnostic_data, success) Implementation →
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: assertion
Most assertions will be expressions, e.g., call assert(i>0, "positive i")
character(len=*), intent(in) :: description
Brief statement of what is being asserted
class(*), intent(in), optional :: diagnostic_data
Optional assertion result
logical, intent(out), optional :: success
Optional assertion result
Description
Report on the truth of an assertion or error-terminate on assertion failure
Call graph
assert calls assert
build_surfaces calls assert, build_surfaces
read_wrappers_components calls assert
block_identifier calls assert, block_identifier
set_metadata calls assert
findloc_logical_dim1 calls assert, findloc_logical_dim1
block_load calls assert, block_load
verify_wrappers_components calls assert
read_core_components calls assert
set_grid_specification calls assert, set_grid_specification
compare calls assert, compare
write_formatted calls assert, write_formatted
evaluate calls assert, evaluate
set_up_div_scalar_flux calls assert, set_up_div_scalar_flux
findloc_character_dim1 calls assert, findloc_character_dim1
get_scalar calls assert, get_scalar
div_scalar_flux calls assert, div_scalar_flux
set_vector_components calls assert, set_vector_components
findloc_integer_dim1 calls assert, findloc_integer_dim1
set_scalar calls assert, set_scalar
vectors calls assert, vectors
partition calls assert, partition
set_scalar_flux_divergence calls assert, set_scalar_flux_divergence
set_analytical_scalars calls assert, set_analytical_scalars
set_block_metadata calls read_wrappers_components, verify_wrappers_components, set_metadata, read_core_components, set_block_metadata
findloc calls findloc_integer_dim1, findloc_character_dim1, findloc_logical_dim1