build_surfaces – Morfeus Framework
build_surfaces Interface
49 statements
Source File
interface
Calls
private module subroutine build_surfaces(this, problem_geometry, vertices, block_faces, block_partitions, num_scalars) Implementation →
Arguments
Type Intent Optional Attributes Name
class(cylindrical_grid), intent(in) :: this
class(geometry), intent(in) :: problem_geometry
class(structured_grid), intent(in), dimension(:), allocatable :: vertices
type(surfaces), intent(inout) :: block_faces
integer, intent(in), dimension(:) :: block_partitions
integer, intent(in) :: num_scalars
Description
allocate the surfaces array for use in halo exchanges and boundary conditions
Call graph
build_surfaces calls build_surfaces, positions, assert, my_blocks
assert calls assert