build_pde_prec – Morfeus Framework
build_pde_prec Interface
104 statements
Source File
interface
Constructor
----- Destructor -----
----- Getters -----
----- Temporary up to Gfortran patch ----- ----- Output -----
----- Status Inquirer -----
----- Linear System Solving -----
Calls
private module subroutine build_pde_prec(eqn) Implementation →
Arguments
Type Intent Optional Attributes Name
class(pde), intent(inout) :: eqn
Call graph
build_pde_prec calls build_pde_prec, mypnum_, build_prec, abort_psblas
mypnum_ calls mypnum_
build_prec calls psb_build_prec
abort_psblas calls abort_psblas, psb_abort