check_field_operands – Morfeus Framework
check_field_operands Interface
90 statements
Source File
interface
----- Destructor -----
----- Getters -----
----- Temporary up to Gfortran patch ----- Check operations ----- Setters -----
----- Auxiliary Routines -----
Calls
private module subroutine check_field_operands(f1, f2, where) Implementation →
Arguments
Type Intent Optional Attributes Name
class(field), intent(in) :: f1
type(field), intent(in) :: f2
character(len=*), intent(in) :: where
Call graph
check_field_operands calls check_field_operands, abort_psblas, check_mesh_consistency, check_material_consistency
abort_psblas calls abort_psblas, psb_abort
check_mesh_consistency calls check_mesh_consistency, abort_psblas
check_material_consistency calls check_material_consistency, abort_psblas