check_material_consistency – Morfeus Framework
check_material_consistency Interface
24 statements
Source File
interface
Calls
Called by
public module subroutine check_material_consistency(mat1, mat2, where) Implementation →
Arguments
Type Intent Optional Attributes Name
type(matptr), pointer :: mat1(:)
type(matptr), pointer :: mat2(:)
character(len=*), intent(in) :: where
Call graph
check_material_consistency calls check_material_consistency, abort_psblas
abort_psblas calls abort_psblas, psb_abort
check_field_operands calls check_material_consistency, check_field_operands