check_mesh_consistency – Morfeus Framework
check_mesh_consistency Interface
26 statements
Source File
interface
----- Constructors -----
----- Check Operations -----
Calls
Called by
public module subroutine check_mesh_consistency(msh1, msh2, where) Implementation →
Arguments
Type Intent Optional Attributes Name
type(mesh), pointer :: msh1
type(mesh), pointer :: msh2
character(len=*), intent(in) :: where
Description
Checks the consistency of two meshes: MSH1 and MSH2
Call graph
check_mesh_consistency calls check_mesh_consistency, abort_psblas
abort_psblas calls abort_psblas, psb_abort
vector_pde_grad calls check_mesh_consistency, vector_pde_grad
scalar_pde_laplacian calls check_mesh_consistency, scalar_pde_laplacian
flux_pde_div calls check_mesh_consistency, flux_pde_div
scalar_pde_d2dt2 calls check_mesh_consistency, scalar_pde_d2dt2
scalar_pde_div calls check_mesh_consistency, scalar_pde_div
vector_pde_laplacian calls check_mesh_consistency, vector_pde_laplacian
scalar_pde_ddt calls check_mesh_consistency, scalar_pde_ddt
check_mesh_consistency_bf calls check_mesh_consistency, check_mesh_consistency_bf
vector_pde_div calls check_mesh_consistency, vector_pde_div
check_field_operands calls check_mesh_consistency, check_field_operands
scalar_pde_ddt_phi calls scalar_pde_ddt, scalar_pde_ddt_phi
pde_grad calls vector_pde_grad
pde_div calls vector_pde_div, flux_pde_div, scalar_pde_div
scalar_pde_d2dt2_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_phi
scalar_pde_ddt_fld_phi calls scalar_pde_ddt, scalar_pde_ddt_fld_phi
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
scalar_pde_d2dt2_fld_phi calls scalar_pde_d2dt2, scalar_pde_d2dt2_fld_phi
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
pde_ddt calls scalar_pde_ddt_fld_phi, scalar_pde_ddt_phi
pde_laplacian calls scalar_pde_laplacian_phi, vector_pde_laplacian_gamma_phi, scalar_pde_laplacian_gamma_phi, vector_pde_laplacian_phi
pde_d2dt2 calls scalar_pde_d2dt2_fld_phi, scalar_pde_d2dt2_phi