check_mesh_consistency_bf – Morfeus Framework
check_mesh_consistency_bf Interface
90 statements
Source File
interface
----- Destructor -----
----- Getters -----
----- Temporary up to Gfortran patch ----- Check operations ----- Setters -----
----- Auxiliary Routines -----
Calls
private module subroutine check_mesh_consistency_bf(f1, f2, where) Implementation →
Arguments
Type Intent Optional Attributes Name
class(field), intent(in) :: f1
type(field), intent(in) :: f2
character(len=*), intent(in) :: where
Call graph
check_mesh_consistency_bf calls check_mesh_consistency_bf, check_mesh_consistency
check_mesh_consistency calls check_mesh_consistency, abort_psblas
abort_psblas calls abort_psblas, psb_abort