cholesky_fact_m – Morfeus Framework
cholesky_fact_m Interface
145 statements
Source File
interface
Calls
Called by
private module subroutine cholesky_fact_m(a) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(inout) :: a(:,:)
Call graph
cholesky_fact_m calls cholesky_fact_m
factorize calls cholesky_fact_m
alloc_plane calls factorize, alloc_plane
alloc_surface calls alloc_plane, alloc_surface