create_pde – Morfeus Framework
create_pde Interface
104 statements
Source File
interface
Constructor
----- Destructor -----
----- Getters -----
----- Temporary up to Gfortran patch ----- ----- Output -----
----- Status Inquirer -----
----- Linear System Solving -----
Calls
private module subroutine create_pde(eqn, input_file, sec, msh, dim) Implementation →
Arguments
Type Intent Optional Attributes Name
class(pde), intent(out) :: eqn
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: sec
type(mesh), intent(inout), target :: msh
type(dimensions), intent(in) :: dim
Call graph
create_pde calls create_pde, icontxt_, mypnum_, abort_psblas, psb_spall, psb_erractionsave, open_file, psb_erractionrestore
icontxt_ calls icontxt_
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
open_file calls open_file, abort_psblas