create_vector_field – Morfeus Framework
create_vector_field Interface
125 statements
Source File
interface
----- Getters for Additional Members -----
Getters for Additional Members
----- Setters -----
----- Check Procedures -----
Calls
private module subroutine create_vector_field(fld, msh, dim, bc, mats, on_faces, x0, name) Implementation →
Arguments
Type Intent Optional Attributes Name
class(vector_field), intent(out) :: fld
type(mesh), intent(in), target :: msh
Optional arguments
type(dimensions), intent(in), optional :: dim
type(bc_poly), intent(in), optional target :: bc(:)
type(matptr), intent(in), optional target :: mats(:)
logical, intent(in), optional :: on_faces
type(vector), intent(in), optional :: x0
character(len=*), intent(in), optional :: name
Description
Constructor Mandatory arguments
Call graph
create_vector_field calls create_vector_field, alloc_vector, vector_, abort_psblas
alloc_vector calls alloc_vector, abort_psblas
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort