div_scalar_flux – Morfeus Framework
div_scalar_flux Interface
49 statements
Source File
interface
Calls
private pure module subroutine div_scalar_flux(this, vertices, block_surfaces, div_flux) Implementation →
Arguments
Type Intent Optional Attributes Name
class(cylindrical_grid), intent(in) :: this
class(structured_grid), intent(in) :: vertices
type(surfaces), intent(in) :: block_surfaces
class(structured_grid), intent(inout) :: div_flux
Description
communicate scalar fluxes between block neighbors in a halo exchange; compute scalar flux divergence at block boundaries
Call graph
div_scalar_flux calls div_scalar_flux, div_flux_z, div_flux_y, assert, npoints, positions, div_flux_x
assert calls assert