factorize – Morfeus Framework
factorize Interface
5 statements
Source File
public interface factorize
Calls
Called by
Contents
Module Procedures
lu_fact cholesky_fact_m choloesky_fact_v
Module Procedures
private interface lu_fact()
Arguments
None
private interface cholesky_fact_m()
Arguments
None
private interface choloesky_fact_v()
Arguments
None
Call graph
factorize calls lu_fact, cholesky_fact_m, choloesky_fact_v
lu_fact calls lu_fact, lu_fact_2, lu_fact_4, lu_fact_3
cholesky_fact_m calls cholesky_fact_m
choloesky_fact_v calls choloesky_fact_v
alloc_plane calls factorize, alloc_plane
alloc_surface calls alloc_plane, alloc_surface