fld_grad – Morfeus Framework
fld_grad Interface
4 statements
Source File
public interface fld_grad
Calls
Called by
Contents
Module Procedures
scalar_field_grad vector_field_grad
Module Procedures
private interface scalar_field_grad()
Arguments
None
private interface vector_field_grad()
Arguments
None
Call graph
fld_grad calls vector_field_grad, scalar_field_grad
vector_field_grad calls vector_field_grad, psb_cd_get_local_rows, vector_, abort_psblas
scalar_field_grad calls scalar_field_grad, psb_cd_get_local_rows, vector_, update_vector_halo, abort_psblas
vector_ calls vector_
update_vector_halo calls update_vector_halo, abort_psblas, icontxt_, psb_check_error, psb_halo, psb_cd_get_local_cols, psb_erractionsave, psb_erractionrestore
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
vector_pde_grad calls fld_grad, vector_pde_grad
scalar_pde_laplacian calls fld_grad, scalar_pde_laplacian
vector_pde_laplacian calls fld_grad, vector_pde_laplacian
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
vector_pde_laplacian_phi calls vector_pde_laplacian, vector_pde_laplacian_phi
pde_grad calls vector_pde_grad
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian, vector_pde_laplacian_gamma_phi
pde_laplacian calls vector_pde_laplacian_gamma_phi, scalar_pde_laplacian_gamma_phi, vector_pde_laplacian_phi, scalar_pde_laplacian_phi