free_cell – Morfeus Framework
free_cell Interface
63 statements
Source File
interface
Calls
Called by
public module subroutine free_cell(cells) Implementation →
Arguments
Type Intent Optional Attributes Name
type(cell), allocatable :: cells(:)
Call graph
free_cell calls free_cell, abort_psblas
abort_psblas calls abort_psblas, psb_abort
free_mesh calls free_cell, free_mesh
apply_renum_cell calls free_cell