free_vector – Morfeus Framework
free_vector Interface
45 statements
Source File
interface
Calls
Called by
public module subroutine free_vector(vect) Implementation →
Arguments
Type Intent Optional Attributes Name
type(vector), allocatable :: vect(:)
Call graph
free_vector calls free_vector, abort_psblas
abort_psblas calls abort_psblas, psb_abort
free_mesh calls free_vector, free_mesh
bcast_vector calls free_vector, bcast_vector
l2g_vertex calls free_vector, l2g_vertex
g2l_vector calls free_vector, g2l_vector
scalar_pde_laplacian calls free_vector, scalar_pde_laplacian
free_field calls free_vector, free_field
vector_field_flux calls free_vector, vector_field_flux
write_exo_morfeus calls l2g_vertex, write_exo_morfeus
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian, scalar_pde_laplacian_gamma_phi
rd_inp_motion_law calls bcast_vector, rd_inp_motion_law
write_mesh calls l2g_vertex, write_mesh
bcast_vertex calls bcast_vector, bcast_vertex
fld_flux calls vector_field_flux
scalar_pde_laplacian_phi calls scalar_pde_laplacian, scalar_pde_laplacian_phi
create_motion calls rd_inp_motion_law, create_motion
pde_laplacian calls scalar_pde_laplacian_phi, scalar_pde_laplacian_gamma_phi
g2l_mesh calls bcast_vertex
create_mesh calls g2l_mesh, create_mesh