free_material – Morfeus Framework
free_material Interface
24 statements
Source File
interface
Calls
private module subroutine free_material(mat) Implementation →
Arguments
Type Intent Optional Attributes Name
class(material), intent(inout) :: mat
Call graph
free_material calls free_material, abort_psblas
abort_psblas calls abort_psblas, psb_abort