free_conn – Morfeus Framework
free_conn Interface
92 statements
Source File
interface
**m Connectivity/free_conn
NAME free_conn USAGE call free_conn(a2b)
DESCRIPTION Destructor
INPUTS a2b :: type(connectivity) The connectivity to be destroyed;
**f Connectivity/bcast_conn
NAME bcast_conn USAGE
 call bcast_conn(a2b)
DESCRIPTION Distribute a copy of the connectivity from process 0 to everybody else.
INPUTS a2b :: type(connectivity) The connectivity to be broadcast;
**m Connectivity/get_ith_conn
NAME get_ith_conn USAGE call get_ith_conn(ith_conn,a2b,i)
DESCRIPTION Getter. Access the I-th row in the connectivity table. Returns a pointer to the requested row. Note: returning a pointer and not a copy, because it is used in tight loops; user should NEVER modify nor deallocate the returned pointer.
INPUTS a2b :: type(connectivity), intent(in), target The connectivity to be accessed; i :: integer Request access to the I-th row; OUTPUT ith_conn(:) :: integer, pointer A pointer to the i-th row;
**m Connectivity/get_conn_csr
NAME get_conn_csr USAGE call get_conn_csr(a2b,lookup,conn)
DESCRIPTION Get a full copy of the connectivity table in CSR format. Being a copy the user may do as he/she pleases with it, and should remember to deallocate it.
INPUTS a2b :: type(connectivity), intent(in) The connectivity to be accessed; OUTPUT lookup(:) :: integer, allocatable conn(:) :: integer, allocatable A copy of the lookup table. The neighbours of item I are listed at CONN(lookup(i):lookup(i+1)-1)
Calls
Called by
public module subroutine free_conn(a2b) Implementation →
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(inout) :: a2b
Call graph
free_conn calls free_conn, abort_psblas
abort_psblas calls abort_psblas, psb_abort
supplement_v2c calls free_conn, supplement_v2c
cmp_mesh_desc calls free_conn, cmp_mesh_desc
mobile_verts calls free_conn, mobile_verts
cmp_mesh_v2e calls free_conn, cmp_mesh_v2e
free_mesh calls free_conn, free_mesh
supplement_v2f calls free_conn, supplement_v2f
write_mesh calls free_conn, l2g_conn, write_mesh
smooth_mesh calls free_conn, mobile_verts, smooth_mesh
apply_renum_conn calls free_conn
write_vtk_mesh calls free_conn
l2g_conn calls free_conn, l2g_conn
g2l_conn_core calls free_conn, g2l_conn_core
cmp_mesh_v2ve calls free_conn, cmp_mesh_v2e, cmp_mesh_v2ve
cmp_mesh_v2b calls free_conn, cmp_mesh_v2b
write_vtk_morfeus calls write_vtk_mesh, write_vtk_morfeus
create_mesh calls cmp_mesh_v2b, supplement_v2f, supplement_v2c, cmp_mesh_v2ve, cmp_mesh_desc, create_mesh
write_exo_morfeus calls l2g_conn, write_exo_morfeus