free_vertex – Morfeus Framework
free_vertex Interface
58 statements
Source File
interface
Calls
Called by
public module subroutine free_vertex(verts) Implementation →
Arguments
Type Intent Optional Attributes Name
type(vertex), allocatable :: verts(:)
Call graph
free_vertex calls free_vertex, abort_psblas
abort_psblas calls abort_psblas, psb_abort
free_mesh calls free_vertex, free_mesh
g2l_vertex calls free_vertex, g2l_vertex
bcast_vertex calls free_vertex, bcast_vertex
g2l_mesh calls bcast_vertex, g2l_vertex
create_mesh calls g2l_mesh, create_mesh