g2l_conn – Morfeus Framework
g2l_conn Interface
14 statements
Source File
public interface g2l_conn
Called by
Contents
Subroutines
g2l_conn_1d g2l_conn_2d
Subroutines
public subroutine g2l_conn_1d(a2b, desc_a, is_a2a)
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(inout) :: a2b
type(psb_desc_type), intent(in) :: desc_a
logical, intent(in), optional :: is_a2a
public subroutine g2l_conn_2d(a2b, desc_a, desc_b)
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(inout) :: a2b
type(psb_desc_type), intent(in) :: desc_a
type(psb_desc_type), intent(in) :: desc_b
Call graph
cmp_mesh_desc calls g2l_conn, cmp_mesh_desc
g2l_mesh calls g2l_conn
create_mesh calls g2l_mesh, cmp_mesh_desc, create_mesh