geins_vector_pde_r – Morfeus Framework
geins_vector_pde_r Interface
65 statements
Source File
interface
----- Constructor -----
----- Destructor -----
----- Getters -----
----- Linear System Solving -----
Output
Calls
Called by
private module subroutine geins_vector_pde_r(n, ia, cloud, pde) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: ia(:)
real(kind=psb_dpk_), intent(in) :: cloud(:,:)
class(vector_pde), intent(inout) :: pde
Description
Inserts a ``cloud'' of RHS terms into pde%b
Call graph
geins_vector_pde_r calls geins_vector_pde_r, icontxt_, abort_psblas, psb_erractionsave, psb_geins, psb_erractionrestore
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort
geins_vector_pde_v calls geins_vector_pde_r, geins_vector_pde_v