geins_vector_pde_v – Morfeus Framework
geins_vector_pde_v Interface
65 statements
Source File
interface
----- Constructor -----
----- Destructor -----
----- Getters -----
----- Linear System Solving -----
Output
Calls
private module subroutine geins_vector_pde_v(n, ia, cloud, pde) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: ia(:)
type(vector), intent(in) :: cloud(:)
class(vector_pde), intent(inout) :: pde
Description
Wrapper for ``clouds'' of VECTOR type
Call graph
geins_vector_pde_v calls geins_vector_pde_v, geins_vector_pde_r
geins_vector_pde_r calls geins_vector_pde_r, psb_geins, abort_psblas, psb_erractionsave, icontxt_, psb_erractionrestore
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_