geins_scalar_pde – Morfeus Framework
geins_scalar_pde Interface
62 statements
Source File
interface
Getters
----- Temporary up to Gfortran patch -----
Linear System Solving Output
Calls
private module subroutine geins_scalar_pde(n, ia, cloud, pde) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: ia(:)
real(kind=psb_dpk_), intent(in) :: cloud(:)
class(scalar_pde), intent(inout) :: pde
Description
Inserts a ``cloud'' of RHS terms into pde%b
Call graph
geins_scalar_pde calls geins_scalar_pde, psb_erractionrestore, psb_erractionsave, icontxt_, psb_geins
icontxt_ calls icontxt_