get_abc_math – Morfeus Framework
get_abc_math Interface
23 statements
Source File
public interface get_abc_math
Called by
Contents
Subroutines
get_abc_math_s get_abc_math_v
Subroutines
public subroutine get_abc_math_s(bc, id, a, b, c)
Arguments
Type Intent Optional Attributes Name
type(bc_math), intent(in) :: bc
integer, intent(out) :: id
real(kind=psb_dpk_), intent(inout) :: a(:)
real(kind=psb_dpk_), intent(inout) :: b(:)
real(kind=psb_dpk_), intent(inout) :: c(:)
public subroutine get_abc_math_v(bc, id, a, b, c)
Arguments
Type Intent Optional Attributes Name
type(bc_math), intent(in) :: bc(:)
integer, intent(out) :: id
real(kind=psb_dpk_), intent(inout) :: a(:)
real(kind=psb_dpk_), intent(inout) :: b(:)
type(vector), intent(inout) :: c(:)
Call graph
get_abc_s calls get_abc_math, get_abc_s
get_abc_wall_s calls get_abc_math, get_abc_wall_s
update_boundary_wall_s calls get_abc_math
update_boundary_wall_v calls get_abc_math
get_abc_wall_v calls get_abc_math, get_abc_wall_v