get_dual_table – Morfeus Framework
get_dual_table Interface
22 statements
Source File
interface
Calls
private module subroutine get_dual_table(a2b, b2a) Implementation →
Arguments
Type Intent Optional Attributes Name
class(table), intent(in) :: a2b
type(table), intent(out) :: b2a
Call graph
get_dual_table calls get_dual_table, abort_psblas
abort_psblas calls abort_psblas, psb_abort