get_par – Morfeus Framework
get_par Interface
44 statements
Source File
public interface get_par
Called by
Contents
Functions
get_par_d get_par_h get_par_i get_par_l get_par_v
Functions
public function get_par_d(inp, sec, par, default)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: inp
character(len=*), intent(in) :: sec
character(len=*), intent(in) :: par
real(kind=psb_dpk_), intent(in) :: default
Return Value real(kind=psb_dpk_)
public function get_par_h(inp, sec, par, default)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: inp
character(len=*), intent(in) :: sec
character(len=*), intent(in) :: par
character(len=*), intent(in) :: default
Return Value character(len=:), allocatable
public function get_par_i(inp, sec, par, default)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: inp
character(len=*), intent(in) :: sec
character(len=*), intent(in) :: par
integer, intent(in) :: default
Return Value integer
public function get_par_l(inp, sec, par, default)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: inp
character(len=*), intent(in) :: sec
character(len=*), intent(in) :: par
logical, intent(in) :: default
Return Value logical
public function get_par_v(inp, sec, par, default)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: inp
character(len=*), intent(in) :: sec
character(len=*), intent(in) :: par
type(vector), intent(in) :: default
Return Value type(vector)
Call graph
read_par_h calls get_par
read_par_i calls get_par
read_par_v calls get_par
read_par_l calls get_par