get_abc_wall_s – Morfeus Framework
get_abc_wall_s Interface
49 statements
Source File
interface
Calls
private module subroutine get_abc_wall_s(bc, dim, id, a, b, c) Implementation →
Arguments
Type Intent Optional Attributes Name
class(bc_wall), intent(in) :: bc
type(dimensions), intent(in) :: dim
integer, intent(out) :: id
real(kind=psb_dpk_), intent(inout) :: a(:)
real(kind=psb_dpk_), intent(inout) :: b(:)
real(kind=psb_dpk_), intent(inout) :: c(:)
Description
Getter
Warning
Use intent(inout) for ABC.
Call graph
get_abc_wall_s calls get_abc_wall_s, get_abc_math, abort_psblas
abort_psblas calls abort_psblas, psb_abort