get_vector_field_xp_r – Morfeus Framework
get_vector_field_xp_r Interface
125 statements
Source File
interface
----- Getters for Additional Members -----
Getters for Additional Members
----- Setters -----
----- Check Procedures -----
Calls
private module subroutine get_vector_field_xp_r(fld, xp) Implementation →
Arguments
Type Intent Optional Attributes Name
class(vector_field), intent(in) :: fld
real(kind=psb_dpk_), intent(out), allocatable :: xp(:,:)
Call graph
get_vector_field_xp_r calls get_vector_field_xp_r, abort_psblas
abort_psblas calls abort_psblas, psb_abort