glob_to_loc_ – Morfeus Framework
glob_to_loc_ Interface
13 statements
Source File
interface
Calls
public module function glob_to_loc_(desc, iglob) Implementation →
Arguments
Type Intent Optional Attributes Name
type(psb_desc_type), intent(in) :: desc
integer, intent(in) :: iglob
Return Value integer
Call graph
glob_to_loc_ calls glob_to_loc_, psb_cd_get_context, psb_erractionsave, psb_check_error, psb_glob_to_loc, psb_erractionrestore
psb_check_error calls psb_check_error, psb_error, psb_errpush