interp_on_faces_s – Morfeus Framework
interp_on_faces_s Interface
144 statements
Source File
interface
----- Algebra Operations -----
Calls
private module function interp_on_faces_s(fld) result(r) Implementation →
Arguments
Type Intent Optional Attributes Name
class(scalar_field), intent(in) :: fld
Return Value type(scalar_field)
Description
Result contains scalar_field cell values interpolated onto cell faces
Call graph
interp_on_faces_s calls interp_on_faces_s, abort_psblas, lin_interp
abort_psblas calls abort_psblas, psb_abort
lin_interp calls lin_interp_s, lin_interp_v
lin_interp_s calls lin_interp_s
lin_interp_v calls lin_interp_v