interp_on_faces_v – Morfeus Framework
interp_on_faces_v Interface
125 statements
Source File
interface
----- Getters for Additional Members -----
Getters for Additional Members
----- Setters -----
----- Check Procedures -----
Calls
private module function interp_on_faces_v(fld) result(r) Implementation →
Arguments
Type Intent Optional Attributes Name
class(vector_field), intent(in) :: fld
Return Value type(vector_field)
Call graph
interp_on_faces_v calls interp_on_faces_v, alloc_vector, lin_interp, abort_psblas
alloc_vector calls alloc_vector, abort_psblas
lin_interp calls lin_interp_v, lin_interp_s
abort_psblas calls abort_psblas, psb_abort
lin_interp_v calls lin_interp_v
lin_interp_s calls lin_interp_s