l2g_conn – Morfeus Framework
l2g_conn Interface
92 statements
Source File
interface
**m Connectivity/free_conn
NAME free_conn USAGE call free_conn(a2b)
DESCRIPTION Destructor
INPUTS a2b :: type(connectivity) The connectivity to be destroyed;
**f Connectivity/bcast_conn
NAME bcast_conn USAGE
 call bcast_conn(a2b)
DESCRIPTION Distribute a copy of the connectivity from process 0 to everybody else.
INPUTS a2b :: type(connectivity) The connectivity to be broadcast;
**m Connectivity/get_ith_conn
NAME get_ith_conn USAGE call get_ith_conn(ith_conn,a2b,i)
DESCRIPTION Getter. Access the I-th row in the connectivity table. Returns a pointer to the requested row. Note: returning a pointer and not a copy, because it is used in tight loops; user should NEVER modify nor deallocate the returned pointer.
INPUTS a2b :: type(connectivity), intent(in), target The connectivity to be accessed; i :: integer Request access to the I-th row; OUTPUT ith_conn(:) :: integer, pointer A pointer to the i-th row;
**m Connectivity/get_conn_csr
NAME get_conn_csr USAGE call get_conn_csr(a2b,lookup,conn)
DESCRIPTION Get a full copy of the connectivity table in CSR format. Being a copy the user may do as he/she pleases with it, and should remember to deallocate it.
INPUTS a2b :: type(connectivity), intent(in) The connectivity to be accessed; OUTPUT lookup(:) :: integer, allocatable conn(:) :: integer, allocatable A copy of the lookup table. The neighbours of item I are listed at CONN(lookup(i):lookup(i+1)-1)
Calls
Called by
public module subroutine l2g_conn(a2b_loc, a2b_glob, desc_a, desc_b) Implementation →
Arguments
Type Intent Optional Attributes Name
type(connectivity), intent(in) :: a2b_loc
type(connectivity), intent(out) :: a2b_glob
type(psb_desc_type), intent(in) :: desc_a
type(psb_desc_type), intent(in) :: desc_b
Call graph
l2g_conn calls l2g_conn, psb_amx, icontxt_, psb_gefree, psb_check_error, psb_gather, psb_get_loc_to_glob, mypnum_, psb_geall, abort_psblas, psb_erractionsave, free_conn, psb_erractionrestore, alloc_conn
icontxt_ calls icontxt_
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
free_conn calls free_conn, abort_psblas
alloc_conn calls alloc_conn, abort_psblas
write_mesh calls l2g_conn, write_mesh
write_exo_morfeus calls l2g_conn, write_exo_morfeus