l2g_cell – Morfeus Framework
l2g_cell Interface
63 statements
Source File
interface
Calls
Called by
public module subroutine l2g_cell(cells_loc, cells_glob, desc_c) Implementation →
Arguments
Type Intent Optional Attributes Name
type(cell), allocatable :: cells_loc(:)
type(cell), allocatable :: cells_glob(:)
type(psb_desc_type), intent(in) :: desc_c
Description
WARNING! The global results is allocated only on P0. After its usage it must be deallocated in the calling unit by means of the statement: "if(associated(glob_res)) deallocate(glob_res)"
Call graph
l2g_cell calls l2g_cell, psb_check_error, psb_geall, abort_psblas, psb_erractionsave, mypnum_, psb_gefree, alloc_cell, icontxt_, psb_cd_get_global_cols, psb_gather, psb_erractionrestore
abort_psblas calls abort_psblas, psb_abort
mypnum_ calls mypnum_
alloc_cell calls alloc_cell, abort_psblas
icontxt_ calls icontxt_
write_mesh calls l2g_cell, write_mesh
write_vector_field calls l2g_cell, write_vector_field
get_vector_field calls l2g_cell, get_vector_field
write_exo_morfeus calls l2g_cell, write_exo_morfeus
get_scalar_field calls l2g_cell, get_scalar_field
write_field calls write_vector_field