lin_interp_s – Morfeus Framework
lin_interp_s Interface
145 statements
Source File
interface
Calls
Called by
private module function lin_interp_s(f1, f2, fac) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_), intent(in) :: f1
real(kind=psb_dpk_), intent(in) :: f2
real(kind=psb_dpk_), intent(in) :: fac
Return Value real(kind=psb_dpk_)
Call graph
lin_interp_s calls lin_interp_s
lin_interp calls lin_interp_s
interp_on_faces_s calls lin_interp, interp_on_faces_s
update_scalar_field calls lin_interp, update_scalar_field
interp_on_faces_v calls lin_interp, interp_on_faces_v