load_water – Morfeus Framework
load_water Interface
7 statements
Source File
interface
Calls
Called by
public module subroutine load_water(state, dtemp, tmin, tmax, rho, mu, lambda, sh) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(out) :: state
real(kind=psb_dpk_), intent(out) :: dtemp
real(kind=psb_dpk_), intent(out) :: tmin
real(kind=psb_dpk_), intent(out) :: tmax
real(kind=psb_dpk_), intent(out), allocatable :: rho(:)
real(kind=psb_dpk_), intent(out), allocatable :: mu(:)
real(kind=psb_dpk_), intent(out), allocatable :: lambda(:)
real(kind=psb_dpk_), intent(out), allocatable :: sh(:)
Call graph
load_water calls load_water, abort_psblas
abort_psblas calls abort_psblas, psb_abort
load_material calls load_water, load_material
create_material calls load_material, create_material