lu_fact – Morfeus Framework
lu_fact Interface
145 statements
Source File
interface
Calls
Called by
private module subroutine lu_fact(n, a, ipiv, info) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=psb_dpk_), intent(inout) :: a(n,n)
integer, intent(out) :: ipiv(n)
integer, intent(out) :: info
Call graph
lu_fact calls lu_fact, lu_fact_3, lu_fact_2, lu_fact_4
factorize calls lu_fact
alloc_plane calls factorize, alloc_plane
alloc_surface calls alloc_plane, alloc_surface