metis_partgraphkway – Morfeus Framework
metis_partgraphkway Interface
20 statements
Source File
interface
Called by
private subroutine metis_partgraphkway(n, xadj_glob, adjncy_glob, vwgt, adjwgt, wgtflag, numflag, nparts, options, edgecut, part)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in), dimension(*) :: xadj_glob
integer, intent(in), dimension(*) :: adjncy_glob
integer, intent(in), dimension(*) :: vwgt
integer, intent(in), dimension(*) :: adjwgt
integer, intent(in) :: wgtflag
integer, intent(in) :: numflag
integer, intent(in) :: nparts
integer, intent(in) :: options(*)
integer, intent(out) :: edgecut
integer, intent(out), dimension(*) :: part
Call graph
bld_part_graph calls metis_partgraphkway, bld_part_graph
cmp_mesh_part calls bld_part_graph, cmp_mesh_part
create_mesh calls cmp_mesh_part, create_mesh