my_blocks – Morfeus Framework
my_blocks Interface
97 statements
Source File
interface
Calls
Called by
private pure module function my_blocks(this) result(block_identifier_range) Implementation →
Arguments
Type Intent Optional Attributes Name
class(problem_discretization), intent(in) :: this
Return Value integer (num_bounds)
Description
Result contains the first & last identifiers for blocks owned by this image
Call graph
my_blocks calls my_blocks
initialize_from_plate_3d calls my_blocks, initialize_from_plate_3d
initialize_from_sphere_1d calls my_blocks, initialize_from_sphere_1d
initialize_from_cylinder_2d calls my_blocks, initialize_from_cylinder_2d