partition – Morfeus Framework
partition Interface
97 statements
Source File
interface
Calls
private module subroutine partition(this, global_block_shape, prototype) Implementation →
Arguments
Type Intent Optional Attributes Name
class(problem_discretization), intent(inout) :: this
integer, intent(in) :: global_block_shape(:)
class(structured_grid), intent(in) :: prototype
Description
Define the distribution of blocks across images for the given shape of the block-structured partitions (impure because of image-control statement in emulated co_sum -- may be pure when replaced by intrinsic co_sum)
Call graph
partition calls partition, first_block, last_block, assert
first_block calls overflow
last_block calls first_block, overflow
assert calls assert