pde_laplacian – Morfeus Framework
pde_laplacian Interface
6 statements
Source File
public interface pde_laplacian
Calls
Contents
Module Procedures
scalar_pde_laplacian_phi scalar_pde_laplacian_gamma_phi vector_pde_laplacian_phi vector_pde_laplacian_gamma_phi
Module Procedures
private interface scalar_pde_laplacian_phi()
Arguments
None
private interface scalar_pde_laplacian_gamma_phi()
Arguments
None
private interface vector_pde_laplacian_phi()
Arguments
None
private interface vector_pde_laplacian_gamma_phi()
Arguments
None
Call graph
pde_laplacian calls scalar_pde_laplacian_phi, scalar_pde_laplacian_gamma_phi, vector_pde_laplacian_phi, vector_pde_laplacian_gamma_phi
scalar_pde_laplacian_phi calls scalar_pde_laplacian_phi, scalar_pde_laplacian
scalar_pde_laplacian_gamma_phi calls scalar_pde_laplacian_gamma_phi, scalar_pde_laplacian
vector_pde_laplacian_phi calls vector_pde_laplacian_phi, vector_pde_laplacian
vector_pde_laplacian_gamma_phi calls vector_pde_laplacian_gamma_phi, vector_pde_laplacian
scalar_pde_laplacian calls scalar_pde_laplacian, fld_grad, pde_sign, abort_psblas, check_mesh_consistency, size_blk, psb_get_loc_to_glob, free_vector, mypnum_
vector_pde_laplacian calls vector_pde_laplacian, fld_grad, pde_sign, vector_, abort_psblas, check_mesh_consistency, size_blk, psb_get_loc_to_glob, mypnum_
fld_grad calls scalar_field_grad, vector_field_grad
pde_sign calls pde_sign, abort_psblas
vector_ calls vector_
abort_psblas calls abort_psblas, psb_abort
check_mesh_consistency calls check_mesh_consistency, abort_psblas
size_blk calls size_blk
free_vector calls free_vector, abort_psblas
mypnum_ calls mypnum_
scalar_field_grad calls scalar_field_grad, vector_, abort_psblas, update_vector_halo, psb_cd_get_local_rows
vector_field_grad calls vector_field_grad, vector_, abort_psblas, psb_cd_get_local_rows
update_vector_halo calls update_vector_halo, abort_psblas, psb_erractionsave, psb_check_error, psb_halo, psb_erractionrestore, psb_cd_get_local_cols, icontxt_
icontxt_ calls icontxt_