pde_ddt – Morfeus Framework
pde_ddt Interface
6 statements
Source File
public interface pde_ddt
Calls
Contents
Module Procedures
scalar_pde_ddt_phi scalar_pde_ddt_fld_phi vector_pde_ddt_phi vector_pde_ddt_fld_phi
Module Procedures
private interface scalar_pde_ddt_phi()
Arguments
None
private interface scalar_pde_ddt_fld_phi()
Arguments
None
private interface vector_pde_ddt_phi()
Arguments
None
private interface vector_pde_ddt_fld_phi()
Arguments
None
Call graph
pde_ddt calls scalar_pde_ddt_fld_phi, vector_pde_ddt_fld_phi, vector_pde_ddt_phi, scalar_pde_ddt_phi
scalar_pde_ddt_fld_phi calls scalar_pde_ddt_fld_phi, scalar_pde_ddt
vector_pde_ddt_fld_phi calls vector_pde_ddt_fld_phi, vector_pde_ddt
vector_pde_ddt_phi calls vector_pde_ddt_phi, vector_pde_ddt
scalar_pde_ddt_phi calls scalar_pde_ddt_phi, scalar_pde_ddt
vector_pde_ddt calls vector_pde_ddt, pde_sign, abort_psblas, psb_cd_get_local_rows, size_blk, psb_get_loc_to_glob, mypnum_
scalar_pde_ddt calls scalar_pde_ddt, pde_sign, abort_psblas, psb_cd_get_local_rows, check_mesh_consistency, size_blk, psb_get_loc_to_glob, mypnum_
pde_sign calls pde_sign, abort_psblas
abort_psblas calls abort_psblas, psb_abort
check_mesh_consistency calls check_mesh_consistency, abort_psblas
size_blk calls size_blk
mypnum_ calls mypnum_