pde_source – Morfeus Framework
pde_source Interface
3 statements
Source File
public interface pde_source
Calls
Contents
Module Procedures
scalar_pde_source
Module Procedures
private interface scalar_pde_source()
Arguments
None
Call graph
pde_source calls scalar_pde_source
scalar_pde_source calls scalar_pde_source, psb_get_loc_to_glob, mypnum_, abort_psblas, pde_sign, psb_cd_get_local_rows, size_blk
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
pde_sign calls pde_sign, abort_psblas
size_blk calls size_blk