pde_grad – Morfeus Framework
pde_grad Interface
3 statements
Source File
public interface pde_grad
Calls
Contents
Module Procedures
vector_pde_grad
Module Procedures
private interface vector_pde_grad()
Arguments
None
Call graph
pde_grad calls vector_pde_grad
vector_pde_grad calls vector_pde_grad, fld_grad, pde_sign, abort_psblas, geins_pde, psb_cd_get_local_rows, check_mesh_consistency, size_blk, psb_get_loc_to_glob, mypnum_
fld_grad calls scalar_field_grad, vector_field_grad
pde_sign calls pde_sign, abort_psblas
abort_psblas calls abort_psblas, psb_abort
check_mesh_consistency calls check_mesh_consistency, abort_psblas
size_blk calls size_blk
mypnum_ calls mypnum_
scalar_field_grad calls scalar_field_grad, abort_psblas, psb_cd_get_local_rows, update_vector_halo, vector_
vector_field_grad calls vector_field_grad, abort_psblas, psb_cd_get_local_rows, vector_
update_vector_halo calls update_vector_halo, abort_psblas, psb_erractionsave, psb_check_error, psb_halo, psb_erractionrestore, psb_cd_get_local_cols, icontxt_
vector_ calls vector_
icontxt_ calls icontxt_