pwl_interp – Morfeus Framework
pwl_interp Interface
7 statements
Source File
public interface pwl_interp
Calls
Called by
Contents
Module Procedures
pwl_interp_dx_s pwl_interp_dx_v pwl_interp_x_s pwl_interp_x_v pwl_interp_x_vec
Module Procedures
private interface pwl_interp_dx_s()
Arguments
None
private interface pwl_interp_dx_v()
Arguments
None
private interface pwl_interp_x_s()
Arguments
None
private interface pwl_interp_x_v()
Arguments
None
private interface pwl_interp_x_vec()
Arguments
None
Call graph
pwl_interp calls pwl_interp_x_vec, pwl_interp_x_s, pwl_interp_x_v, pwl_interp_dx_s, pwl_interp_dx_v
pwl_interp_x_vec calls pwl_interp_x_vec, pwl_nearest, abort_psblas
pwl_interp_x_s calls pwl_interp_x_s, pwl_nearest, abort_psblas
pwl_interp_x_v calls pwl_interp_x_v, pwl_nearest, abort_psblas
pwl_interp_dx_s calls pwl_interp_dx_s
pwl_interp_dx_v calls pwl_interp_dx_v, abort_psblas
pwl_nearest calls pwl_nearest, abort_psblas
abort_psblas calls abort_psblas, psb_abort
get_motion_displacement calls pwl_interp, get_motion_displacement
get_motion_velocity calls pwl_interp, get_motion_velocity