pwl_deriv – Morfeus Framework
pwl_deriv Interface
5 statements
Source File
public interface pwl_deriv
Calls
Called by
Contents
Module Procedures
pwl_deriv_x_s pwl_deriv_x_v pwl_deriv_x_vec
Module Procedures
private interface pwl_deriv_x_s()
Arguments
None
private interface pwl_deriv_x_v()
Arguments
None
private interface pwl_deriv_x_vec()
Arguments
None
Call graph
pwl_deriv calls pwl_deriv_x_v, pwl_deriv_x_vec, pwl_deriv_x_s
pwl_deriv_x_v calls pwl_deriv_x_v, pwl_nearest, abort_psblas
pwl_deriv_x_vec calls pwl_deriv_x_vec, pwl_nearest, abort_psblas
pwl_deriv_x_s calls pwl_deriv_x_s, pwl_nearest, abort_psblas
pwl_nearest calls pwl_nearest, abort_psblas
abort_psblas calls abort_psblas, psb_abort
get_motion_velocity calls pwl_deriv, get_motion_velocity