right_handed – Morfeus Framework
right_handed Interface
119 statements
Source File
interface
Called by
public function right_handed(p1, p2, p3, p4)
Arguments
Type Intent Optional Attributes Name
real(kind=psb_dpk_) :: p1(3)
real(kind=psb_dpk_) :: p2(3)
real(kind=psb_dpk_) :: p3(3)
real(kind=psb_dpk_) :: p4(3)
Return Value integer
Call graph
tet_valid calls right_handed
smooth_interior_vtx calls right_handed, smooth_interior_vtx
check_right_handed calls right_handed, check_right_handed
smooth_mesh calls check_right_handed, smooth_mesh