scalar_field_dif – Morfeus Framework
scalar_field_dif Interface
144 statements
Source File
interface
----- Algebra Operations -----
Calls
private module function scalar_field_dif(f1, f2) result(r) Implementation →
Arguments
Type Intent Optional Attributes Name
class(scalar_field), intent(in) :: f1
type(scalar_field), intent(in) :: f2
Return Value type(scalar_field)
Description
Result is the arithmetic difference of the two scalar_field operands
Call graph
scalar_field_dif calls scalar_field_dif, abort_psblas
abort_psblas calls abort_psblas, psb_abort