set_bc_wall_map_v – Morfeus Framework
set_bc_wall_map_v Interface
49 statements
Source File
interface
Calls
private module subroutine set_bc_wall_map_v(bc, i, a, b, c) Implementation →
Arguments
Type Intent Optional Attributes Name
class(bc_wall), intent(inout) :: bc
integer, intent(in) :: i
real(kind=psb_dpk_), intent(in) :: a
real(kind=psb_dpk_), intent(in) :: b
type(vector), intent(in) :: c
Call graph
set_bc_wall_map_v calls set_bc_wall_map_v, abort_psblas
abort_psblas calls abort_psblas, psb_abort