solve_vector_pde – Morfeus Framework
solve_vector_pde Interface
65 statements
Source File
interface
----- Constructor -----
----- Destructor -----
----- Getters -----
----- Linear System Solving -----
Output
Calls
private module subroutine solve_vector_pde(pde, phi, var) Implementation →
Arguments
Type Intent Optional Attributes Name
class(vector_pde), intent(inout) :: pde
type(vector_field), intent(inout) :: phi
real(kind=psb_dpk_), intent(out), optional :: var
Description
Assigns the solution to the vector field
Call graph
solve_vector_pde calls solve_vector_pde, psb_check_error, abort_psblas, psb_erractionsave, icontxt_, vector_, psb_erractionrestore, psb_genrm2
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_
vector_ calls vector_