solve_scalar_pde – Morfeus Framework
solve_scalar_pde Interface
62 statements
Source File
interface
Getters
----- Temporary up to Gfortran patch -----
Linear System Solving Output
Calls
private module subroutine solve_scalar_pde(pde, mats, phi, var) Implementation →
Arguments
Type Intent Optional Attributes Name
class(scalar_pde), intent(inout) :: pde
type(matptr), intent(in), optional pointer :: mats(:)
type(scalar_field), intent(inout) :: phi
real(kind=psb_dpk_), intent(out), optional :: var
Call graph
solve_scalar_pde calls solve_scalar_pde, icontxt_, psb_check_error, psb_genrm2, abort_psblas, psb_erractionsave, psb_erractionrestore
icontxt_ calls icontxt_
abort_psblas calls abort_psblas, psb_abort