solve_pde_sys – Morfeus Framework
solve_pde_sys Interface
104 statements
Source File
interface
Constructor
----- Destructor -----
----- Getters -----
----- Temporary up to Gfortran patch ----- ----- Output -----
----- Status Inquirer -----
----- Linear System Solving -----
Calls
private module subroutine solve_pde_sys(eqn, b, x, iter, err) Implementation →
Arguments
Type Intent Optional Attributes Name
class(pde), intent(inout) :: eqn
real(kind=psb_dpk_), intent(in) :: b(:)
real(kind=psb_dpk_), intent(out) :: x(:)
integer, intent(out) :: iter
real(kind=psb_dpk_), intent(out) :: err
Call graph
solve_pde_sys calls solve_pde_sys, solve_sys, psb_csprt
solve_sys calls lu_solve, cholesky_solve_v, cholesky_solve_m, psb_solve_sys
lu_solve calls lu_solve
cholesky_solve_v calls cholesky_solve_v
cholesky_solve_m calls cholesky_solve_m
psb_solve_sys calls psb_solve_sys, psb_krylov, psb_erractionsave, icontxt_, psb_check_error, mypnum_, psb_erractionrestore
icontxt_ calls icontxt_
mypnum_ calls mypnum_