solve_sys – Morfeus Framework
solve_sys Interface
6 statements
Source File
public interface solve_sys
Calls
Called by
Contents
Module Procedures
lu_solve cholesky_solve_m cholesky_solve_v psb_solve_sys
Module Procedures
private interface lu_solve()
Arguments
None
private interface cholesky_solve_m()
Arguments
None
private interface cholesky_solve_v()
Arguments
None
private interface psb_solve_sys()
Arguments
None
Call graph
solve_sys calls cholesky_solve_m, cholesky_solve_v, psb_solve_sys, lu_solve
cholesky_solve_m calls cholesky_solve_m
cholesky_solve_v calls cholesky_solve_v
psb_solve_sys calls psb_solve_sys, icontxt_, psb_check_error, mypnum_, psb_erractionsave, psb_erractionrestore, psb_krylov
lu_solve calls lu_solve
icontxt_ calls icontxt_
mypnum_ calls mypnum_
laplacian_smooth calls solve_sys, laplacian_smooth
solve_pde_sys calls solve_sys, solve_pde_sys
solve_least_squares calls solve_sys, solve_least_squares
alloc_plane calls solve_sys, alloc_plane
alloc_surface calls alloc_plane, alloc_surface
smooth_mesh calls laplacian_smooth, smooth_mesh