spins_pde – Morfeus Framework
spins_pde Interface
104 statements
Source File
interface
Constructor
----- Destructor -----
----- Getters -----
----- Temporary up to Gfortran patch ----- ----- Output -----
----- Status Inquirer -----
----- Linear System Solving -----
Calls
private module subroutine spins_pde(n, ia, ja, cloud, eqn) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: ia(:)
integer, intent(in) :: ja(:)
real(kind=psb_dpk_), intent(in) :: cloud(:)
class(pde), intent(inout) :: eqn
Description
Linear System Solving Inserts a ``cloud'' of coefficients into eqn%A
Call graph
spins_pde calls spins_pde, psb_erractionsave, icontxt_, psb_spins, psb_erractionrestore
icontxt_ calls icontxt_