time_advance_heat_equation – Morfeus Framework
time_advance_heat_equation Interface
29 statements
Source File
interface
Calls
private module subroutine time_advance_heat_equation(this, duration) Implementation →
Arguments
Type Intent Optional Attributes Name
class(spherical_1d_solver), intent(inout) :: this
real(kind=r8k), intent(in) :: duration
Call graph
time_advance_heat_equation calls time_advance_heat_equation, time_advancing, error_calculation, analytical_solution
time_advancing calls kc, tridiagonal_matrix_algorithm