write_exo_morfeus – Morfeus Framework
write_exo_morfeus Interface
11 statements
Source File
interface
Calls
private module subroutine write_exo_morfeus(out, msh, sfield, vfield, iter) Implementation →
Arguments
Type Intent Optional Attributes Name
class(vtk_output_), intent(inout) :: out
DT of output file info
type(mesh), intent(in) :: msh
DT of mesh info
type(scalar_field), intent(in), optional dimension(:) :: sfield
DT of scalar info
type(vector_field), intent(in), optional dimension(:) :: vfield
DT of vector info
type(iterating), intent(in), optional :: iter
DT of iteration info
Description
This subroutine translates morfeus data structure into an exodus data structure and writes the exodus file
Call graph
write_exo_morfeus calls write_exo_morfeus, mypnum_, abort_psblas, l2g_cell, exclos, icontxt_, l2g_vector, expcon, psb_erractionsave, expini, l2g_face, exopts, psb_geall, expcor, psb_check_error, psb_gather, l2g_conn, excre, psb_cd_get_global_cols, l2g_vertex
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
l2g_cell calls l2g_cell, mypnum_, abort_psblas, icontxt_, psb_erractionsave, psb_geall, psb_check_error, psb_gather, psb_cd_get_global_cols, psb_gefree, alloc_cell, psb_erractionrestore
icontxt_ calls icontxt_
l2g_vector calls l2g_vector, mypnum_, abort_psblas, icontxt_, psb_erractionsave, psb_geall, psb_check_error, psb_gather, psb_cd_get_global_cols, psb_gefree, alloc_vector, psb_ovrl, psb_erractionrestore
l2g_face calls l2g_face, mypnum_, abort_psblas, icontxt_, psb_erractionsave, psb_geall, psb_check_error, psb_gather, psb_cd_get_global_cols, psb_gefree, alloc_face, psb_get_loc_to_glob, psb_erractionrestore
l2g_conn calls l2g_conn, mypnum_, abort_psblas, icontxt_, psb_erractionsave, psb_geall, psb_check_error, psb_gather, psb_amx, psb_gefree, psb_get_loc_to_glob, psb_erractionrestore, alloc_conn, free_conn
l2g_vertex calls l2g_vertex, mypnum_, icontxt_, l2g_vector, psb_erractionsave, psb_cd_get_global_cols, alloc_vector, free_vector, psb_erractionrestore, alloc_vertex
alloc_face calls alloc_face, abort_psblas
alloc_vector calls alloc_vector, abort_psblas
free_vector calls free_vector, abort_psblas
alloc_cell calls alloc_cell, abort_psblas
alloc_conn calls alloc_conn, abort_psblas
alloc_vertex calls alloc_vertex, abort_psblas, vector_
free_conn calls free_conn, abort_psblas
vector_ calls vector_