write_scalar_pde – Morfeus Framework
write_scalar_pde Interface
62 statements
Source File
interface
Getters
----- Temporary up to Gfortran patch -----
Linear System Solving Output
Calls
private module subroutine write_scalar_pde(eqn, mat, rhs) Implementation →
Arguments
Type Intent Optional Attributes Name
class(scalar_pde), intent(in) :: eqn
character(len=*), intent(in) :: mat
character(len=*), intent(in) :: rhs
Description
----- Output -----
Call graph
write_scalar_pde calls write_scalar_pde, wr_mtx_vector, mypnum_
wr_mtx_vector calls wr_mtx_vector, mypnum_, psb_cd_get_global_cols, abort_psblas, psb_erractionsave, psb_erractionrestore, psb_gather, icontxt_
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_