write_pde – Morfeus Framework
write_pde Interface
104 statements
Source File
interface
Constructor
----- Destructor -----
----- Getters -----
----- Temporary up to Gfortran patch ----- ----- Output -----
----- Status Inquirer -----
----- Linear System Solving -----
Calls
private module subroutine write_pde(eqn, mat, mtx_rhs) Implementation →
Arguments
Type Intent Optional Attributes Name
class(pde), intent(in) :: eqn
character(len=*), intent(in) :: mat
logical, intent(out) :: mtx_rhs
Description
Output
Call graph
write_pde calls write_pde, wr_mtx_matrix
wr_mtx_matrix calls wr_mtx_matrix, psb_check_error, mypnum_, psb_erractionsave, abort_psblas, psb_snd, psb_rcv, psb_sum, nprocs_, icontxt_, psb_get_loc_to_glob, psb_amx, psb_erractionrestore
mypnum_ calls mypnum_
abort_psblas calls abort_psblas, psb_abort
nprocs_ calls nprocs_
icontxt_ calls icontxt_