write_vector_pde – Morfeus Framework
write_vector_pde Interface
65 statements
Source File
interface
----- Constructor -----
----- Destructor -----
----- Getters -----
----- Linear System Solving -----
Output
Calls
private module subroutine write_vector_pde(eqn, mat, rhs) Implementation →
Arguments
Type Intent Optional Attributes Name
class(vector_pde), intent(in) :: eqn
character(len=*), intent(in) :: mat
character(len=*), intent(in) :: rhs
Description
----- Output -----
Call graph
write_vector_pde calls write_vector_pde, mypnum_, wr_mtx_vector
mypnum_ calls mypnum_
wr_mtx_vector calls wr_mtx_vector, mypnum_, psb_gather, abort_psblas, psb_erractionsave, icontxt_, psb_cd_get_global_cols, psb_erractionrestore
abort_psblas calls abort_psblas, psb_abort
icontxt_ calls icontxt_