write_field – Morfeus Framework
write_field Interface
4 statements
Source File
public interface write_field
Calls
Contents
Module Procedures
write_scalar_field write_vector_field
Module Procedures
private interface write_scalar_field()
Arguments
None
private interface write_vector_field()
Arguments
None
Call graph
write_field calls write_vector_field, write_scalar_field
write_vector_field calls write_vector_field, icontxt_, mypnum_, l2g_vector, get_mesh, get_x, abort_psblas, psb_erractionsave, l2g_cell, psb_erractionrestore, psb_cd_get_global_cols
write_scalar_field calls write_scalar_field, icontxt_, l2g_cell, psb_check_error, psb_gather, abort_psblas, mypnum_, get_mesh, get_x, psb_erractionsave, psb_erractionrestore, psb_cd_get_global_cols
icontxt_ calls icontxt_
mypnum_ calls mypnum_
l2g_vector calls l2g_vector, icontxt_, psb_check_error, psb_gather, mypnum_, abort_psblas, psb_erractionsave, psb_erractionrestore, psb_cd_get_global_cols, psb_gefree, alloc_vector, psb_geall, psb_ovrl
abort_psblas calls abort_psblas, psb_abort
l2g_cell calls l2g_cell, icontxt_, psb_check_error, psb_gather, mypnum_, abort_psblas, psb_erractionsave, psb_erractionrestore, psb_cd_get_global_cols, psb_gefree, psb_geall, alloc_cell
alloc_vector calls alloc_vector, abort_psblas
alloc_cell calls alloc_cell, abort_psblas